import React, { useEffect, useMemo, useState } from 'react';
import { Loader2, Save, Wrench } from 'lucide-react';
import { fleetFetch } from '../../lib/fleetApi';
import { VehicleServiceSpecificationsCard, type VehicleServiceSpecificationsValue } from './VehicleServiceSpecificationsCard';
import { VehicleServiceSpecificationsFields } from './VehicleServiceSpecificationsFields';

type StoredVehicle={id:string;unit_number:string;vin:string|null;year:number|null;make:string|null;model:string|null;trim:string|null;engine:string|null;fuel_type:string|null;license_plate:string|null;registration_state:string|null;mileage:number|null;engine_hours:number|null;status:'active'|'down'|'out_of_service'|'retired';assigned_driver:string|null;department:string|null;in_service_date:string|null;notes:string|null;specifications:VehicleServiceSpecificationsValue|null;metadata?:{type?:string|null;assignment?:string|null}|null};
const toUpdate=(v:StoredVehicle,s:VehicleServiceSpecificationsValue)=>({unitNumber:v.unit_number,vin:v.vin,year:v.year,make:v.make,model:v.model,trim:v.trim,engine:v.engine,fuelType:v.fuel_type,licensePlate:v.license_plate,registrationState:v.registration_state,mileage:v.mileage,engineHours:v.engine_hours,status:v.status,assignedDriver:v.assigned_driver,department:v.department,inServiceDate:v.in_service_date,notes:v.notes,specifications:s,type:v.metadata?.type||null,assignment:v.metadata?.assignment||null});

export function VehicleSpecificationsManager(){
 const[vehicles,setVehicles]=useState<StoredVehicle[]>([]),[selectedId,setSelectedId]=useState(''),[value,setValue]=useState<VehicleServiceSpecificationsValue>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;fleetFetch('/api/vehicles').then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Could not load vehicles');if(active){setVehicles(p.vehicles||[]);if(p.vehicles?.[0])setSelectedId(p.vehicles[0].id)}}).catch(e=>active&&setMessage(e instanceof Error?e.message:'Could not load vehicles')).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const selected=useMemo(()=>vehicles.find(v=>v.id===selectedId)||null,[vehicles,selectedId]);
 useEffect(()=>{setValue(selected?.specifications||{});setMessage('')},[selectedId,selected]);
 const save=async()=>{if(!selected)return;setSaving(true);setMessage('');try{const r=await fleetFetch(`/api/vehicles/${selected.id}`,{method:'PUT',body:JSON.stringify(toUpdate(selected,value))});const p=await r.json();if(!r.ok||!p.vehicle)throw new Error(p.error||'Specifications could not be saved');setVehicles(current=>current.map(v=>v.id===selected.id?p.vehicle:v));setMessage('Service specifications saved. Future technician work packets will use this data.')}catch(e){setMessage(e instanceof Error?e.message:'Specifications could not be saved')}finally{setSaving(false)}};
 if(loading)return <section className="mx-6 mb-8 rounded-2xl border bg-white p-8 text-center text-sm text-slate-500 lg:mx-8"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin"/>Loading service specifications…</section>;
 if(!vehicles.length)return null;
 return <section className="mx-6 mb-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:mx-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-blue-600"><Wrench className="h-4 w-4"/>Technician service data</p><h2 className="mt-1 text-xl font-bold text-slate-950">Vehicle specifications</h2><p className="mt-1 text-sm text-slate-500">Persist oil, filters, fluids, tire, battery, wiper and torque data once per unit.</p></div><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold">{vehicles.map(v=><option key={v.id} value={v.id}>Unit {v.unit_number} · {[v.year,v.make,v.model].filter(Boolean).join(' ')}</option>)}</select></div>{selected&&<div className="mt-5 grid gap-5 xl:grid-cols-2"><VehicleServiceSpecificationsCard specifications={value}/><div className="overflow-hidden rounded-2xl border border-slate-200"><VehicleServiceSpecificationsFields value={value} onChange={setValue}/><div className="flex items-center justify-between border-t border-slate-200 bg-white p-4"><p className={`text-xs ${message.includes('saved')?'text-emerald-700':'text-slate-500'}`}>{message}</p><button onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save specifications</button></div></div></div>}</section>;
}
