-- Canonical schema source: src/db/drizzleSchema.ts
-- Generate PostgreSQL DDL with: npm run db:generate
-- Then apply src/db/migrations/0001_multitenant_rls.sql.
-- This stub intentionally replaces the prototype schema whose nullable user_id
-- policies permitted cross-tenant/anonymous access.
