import { ArrowRight, Check, Menu, X } from 'lucide-react';
import { useState } from 'react';

interface HomePageProps { onNavigate: (path: string) => void }

const capabilities = [
  ['Email becomes operations','Fleet requests, attachments, replies, and documents stay connected to the customer and the work instead of disappearing into an inbox.'],
  ['A Fleet Agent that knows the business','Ask about fleet accounts, people, vehicles, work orders, email, documents, or the public web. FleetOS uses your records first and external tools only when needed.'],
  ['Vehicle intelligence at intake','Read VINs from email, uploads, camera scans, and forms, then enrich valid VINs with NHTSA vehicle data before work is created.'],
  ['Built for the whole service team','Owners govern the business. Dispatchers coordinate the day. Technicians execute assigned work from a focused mobile workspace.'],
  ['Schedule and dispatch real work','Move from service request to work order, appointment, assignment, inspection, recommendation, authorization, and completion.'],
  ['Close the operational loop','Keep invoices, payments, profitability, documents, and customer history attached to the same fleet account and work history.'],
  ['Switch systems without starting over','Bring customers, fleet accounts, vehicles, service history, invoices, and documents into one normalized FleetOS workspace.'],
  ['Automation with authority boundaries','Manual, assisted, and policy-driven automation remain governed by user permissions, service agreements, workflow state, and approval rules.'],
];

const workflow = [
  ['01','Receive','A fleet customer emails a request, uploads a list, or your team captures a card, document, or vehicle.'],
  ['02','Understand','Fleet Agent resolves the company and people, extracts vehicles and VINs, reads attachments, and enriches the request with context.'],
  ['03','Plan','FleetOS matches existing records, applies the account service agreement, builds proposed work, and identifies exceptions.'],
  ['04','Operate','Schedule, dispatch, technician execution, inspection, authorization, documents, and completion stay in one operational chain.'],
  ['05','Close','Completed work becomes invoice and payment history while messages and decisions remain attached to the account.'],
  ['06','Automate','Approved service rules move repeatable work from review-once Assisted mode toward safe Autopilot without unlimited agent authority.'],
];

export function HomePage({ onNavigate }: HomePageProps) {
  const [menuOpen,setMenuOpen]=useState(false);
  return <main className="min-h-screen overflow-hidden bg-[#f7f8f6] text-[#17211d] selection:bg-[#c9f5dc]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-black/[0.07] bg-[#f7f8f6]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><button onClick={()=>onNavigate('/')} className="flex items-center gap-2.5" aria-label="Fleet OS home"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#173d2d] text-sm font-bold text-white">F</span><span className="text-base font-semibold tracking-[-.02em]">Fleet OS</span></button><nav className="hidden items-center gap-8 md:flex"><a href="#platform" className="text-sm text-[#66716b] hover:text-[#17211d]">Platform</a><a href="#workflow" className="text-sm text-[#66716b] hover:text-[#17211d]">Operating loop</a><a href="#automation" className="text-sm text-[#66716b] hover:text-[#17211d]">Automation</a><a href="#security" className="text-sm text-[#66716b] hover:text-[#17211d]">Security</a></nav><div className="hidden items-center gap-2 md:flex"><button onClick={()=>onNavigate('/sign-in')} className="px-4 py-2.5 text-sm font-medium">Sign in</button><button onClick={()=>onNavigate('/sign-up')} className="rounded-full bg-[#173d2d] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#0e2d20]">Start free</button></div><button onClick={()=>setMenuOpen(v=>!v)} className="grid h-10 w-10 place-items-center md:hidden" aria-label="Toggle navigation">{menuOpen?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</button></div>{menuOpen&&<div className="border-t border-black/[0.07] bg-[#f7f8f6] px-5 py-5 md:hidden"><div className="grid gap-1">{[['Platform','#platform'],['Operating loop','#workflow'],['Automation','#automation'],['Security','#security']].map(([label,href])=><a key={label} href={href} onClick={()=>setMenuOpen(false)} className="py-2.5 text-sm text-[#56625c]">{label}</a>)}<div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>onNavigate('/sign-in')} className="rounded-full border border-black/10 px-4 py-2.5 text-sm">Sign in</button><button onClick={()=>onNavigate('/sign-up')} className="rounded-full bg-[#173d2d] px-4 py-2.5 text-sm font-semibold text-white">Start free</button></div></div></div>}</header>

    <section className="px-5 pb-24 pt-36 sm:px-8 sm:pt-44 lg:px-10 lg:pb-32"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[1fr_.92fr] lg:items-center"><div className="max-w-3xl"><p className="text-sm font-semibold text-[#287451]">From first fleet email to final payment</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[76px]">Run fleet service from one operating system.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#64706a]">Turn customer communication into organized fleet work—from the first request and VIN to scheduling, technician execution, invoicing, and payment.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={()=>onNavigate('/sign-up')} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-[#173d2d] px-6 text-sm font-semibold text-white hover:bg-[#0e2d20]">Start your workspace <ArrowRight className="h-4 w-4"/></button><button onClick={()=>onNavigate('/sign-in')} className="h-12 rounded-full border border-black/10 bg-white px-6 text-sm font-semibold hover:border-black/20">Open Fleet OS</button></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[#748078]">{['Role-based access','AgentMail inbox','NHTSA VIN intelligence','Browserbase research'].map(item=><span key={item} className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#287451]"/>{item}</span>)}</div></div>
      <div className="relative"><div className="absolute -inset-8 rounded-full bg-[#dff3e6] blur-3xl"/><div className="relative overflow-hidden rounded-[24px] border border-black/[0.08] bg-white shadow-[0_30px_80px_rgba(31,49,40,.12)]"><div className="flex items-center justify-between border-b border-black/[0.07] px-6 py-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#287451]">Fleet Agent</p><p className="mt-1 text-sm font-medium">Inbox → operation</p></div><span className="rounded-full bg-[#edf7f0] px-3 py-1 text-xs font-medium text-[#287451]">Ready</span></div><div className="p-6"><p className="text-lg font-medium leading-7">“Bob at Closet World sent 10 vans for Sunday service.”</p><div className="mt-6 border-l border-[#b7c7bd] pl-5">{['Resolve customer + fleet account','Extract and identify 10 vehicles','Decode valid VINs','Apply Sunday service agreement','Prepare work, schedule, and dispatch'].map((item,index)=><div key={item} className="relative pb-5 last:pb-0"><span className="absolute -left-[25px] top-1.5 h-2 w-2 rounded-full bg-[#287451]"/><p className="text-sm font-medium">{item}</p><p className="mt-1 text-xs text-[#7b867f]">{index<4?'Context verified':'Ready for approval'}</p></div>)}</div></div></div></div></div></div></section>

    <section id="platform" className="border-y border-black/[0.07] bg-white px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div className="max-w-md"><p className="text-sm font-semibold text-[#287451]">One operational system</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Every handoff shares the same context.</h2><p className="mt-5 leading-7 text-[#68736d]">FleetOS is not a chatbot attached to a database. The agent and operating system work from the same canonical records.</p></div><div className="divide-y divide-black/[0.08] border-y border-black/[0.08]">{capabilities.map(([title,copy],index)=><article key={title} className="grid gap-3 py-6 sm:grid-cols-[42px_1fr_1.35fr] sm:gap-6"><span className="text-sm tabular-nums text-[#9aa39e]">{String(index+1).padStart(2,'0')}</span><h3 className="font-semibold tracking-[-.01em]">{title}</h3><p className="text-sm leading-6 text-[#68736d]">{copy}</p></article>)}</div></div></div></section>

    <section id="workflow" className="px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-semibold text-[#287451]">The operating loop</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">One request. One chain of responsibility.</h2></div><div className="mt-14 grid gap-x-10 gap-y-12 md:grid-cols-3">{workflow.map(([number,title,copy])=><div key={number} className="border-t border-black/[0.14] pt-5"><span className="text-xs font-semibold text-[#287451]">{number}</span><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#68736d]">{copy}</p></div>)}</div></div></section>

    <section id="automation" className="bg-[#183b2d] px-5 py-24 text-white sm:px-8 lg:px-10"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.85fr_1.15fr]"><div className="max-w-lg"><p className="text-sm font-semibold text-[#a9e0bf]">Service agreements + automation</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em]">Teach FleetOS how each client operates.</h2><p className="mt-5 leading-7 text-white/65">Preferred days, service windows, SLA, approval thresholds, PO requirements, billing cadence, technician rules, recipients, and automation level become deterministic account policy—not facts the AI has to guess.</p></div><div className="divide-y divide-white/15 border-y border-white/15">{[['Manual','Agent understands and prepares. A person controls each operation.'],['Assisted','Agent prepares the complete transaction. A person reviews and approves once.'],['Autopilot','Repeatable work inside approved account policy executes automatically; exceptions stop for review.']].map(([title,copy],i)=><div key={title} className="grid gap-2 py-7 sm:grid-cols-[130px_1fr]"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${i===1?'bg-[#a9e0bf]':'bg-white/35'}`}/><p className="font-semibold">{title}</p></div><p className="text-sm leading-6 text-white/65">{copy}</p></div>)}</div></div></section>

    <section id="security" className="bg-white px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-10 border-y border-black/[0.08] py-14 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><p className="text-sm font-semibold text-[#287451]">Security by architecture</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.045em]">The AI never becomes the permission system.</h2></div><div><p className="leading-7 text-[#68736d]">Neon Auth verifies identity. FleetOS memberships determine the workspace. Server-enforced permissions determine what each role may do. Account policy and workflow state narrow automation further. The agent operates inside those boundaries.</p><button onClick={()=>onNavigate('/sign-up')} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#173d2d]">Build your operation <ArrowRight className="h-4 w-4"/></button></div></div></div></section>

    <footer className="bg-white px-5 py-8 text-sm text-[#78827d] sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-3 border-t border-black/[0.07] pt-8 sm:flex-row sm:items-center sm:justify-between"><span className="font-semibold text-[#34423b]">Fleet OS</span><span>Fleet work from inbox to invoice.</span></div></footer>
  </main>;
}
