import { ArrowRight, Bot, Building2, CalendarDays, CheckCircle2, CircleDollarSign, FileUp, Mail, Menu, ScanLine, ShieldCheck, Truck, Users, Wrench, X, Zap } from 'lucide-react';
import { useState } from 'react';

interface HomePageProps { onNavigate: (path: string) => void }

const capabilities = [
  { icon: Mail, title: 'Email becomes operations', copy: 'Fleet requests, attachments, replies, and documents stay connected to the customer and the work instead of disappearing into an inbox.' },
  { icon: Bot, title: 'A Fleet Agent that knows the business', copy: 'Ask about fleet accounts, people, vehicles, work orders, email, documents, or the public web. The agent uses FleetOS records first and external tools only when needed.' },
  { icon: ScanLine, title: 'Vehicle intelligence at intake', copy: 'Read VINs from email, uploads, camera scans, and forms, then enrich valid VINs with NHTSA vehicle data before work is created.' },
  { icon: Users, title: 'Built for owners, dispatchers, and technicians', copy: 'Each role gets the access and operating surface it needs, backed by server-enforced workspace permissions.' },
  { icon: CalendarDays, title: 'Schedule and dispatch the real work', copy: 'Move from a service request to work orders, appointments, technician assignments, inspections, recommendations, authorizations, and completion.' },
  { icon: CircleDollarSign, title: 'Close the operational loop', copy: 'Keep invoices, payments, profitability, documents, and customer history attached to the same fleet account and work history.' },
  { icon: FileUp, title: 'Switch systems without starting over', copy: 'The migration vision brings customers, fleet accounts, vehicles, service history, invoices, and documents into one normalized FleetOS workspace.' },
  { icon: ShieldCheck, title: 'Automation with authority boundaries', copy: 'Manual, assisted, and policy-driven automation are governed by the signed-in user, workspace permissions, service agreements, and approval rules.' },
];

const workflow = [
  ['01','Receive','A fleet customer emails a request, uploads a list, or a team member scans a card, document, or vehicle.'],
  ['02','Understand','Fleet Agent resolves the company and people, extracts vehicles and VINs, reads attachments, and enriches the request with the right context.'],
  ['03','Plan','FleetOS matches existing records, applies the fleet account service agreement, builds the proposed work, and identifies exceptions.'],
  ['04','Operate','Schedule, dispatch, technician execution, inspection, authorization, documents, and completion stay in one operational chain.'],
  ['05','Close','Completed work becomes invoice and payment history, while every message and decision remains attached to the account.'],
  ['06','Automate','Approved service rules can move repeatable work from review-once Assisted mode toward safe Autopilot without giving the agent unlimited authority.'],
];

export function HomePage({ onNavigate }: HomePageProps) {
  const [menuOpen,setMenuOpen]=useState(false);
  return <main className="min-h-screen overflow-hidden bg-[#07101f] text-white selection:bg-cyan-300 selection:text-slate-950">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#07101f]/85 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><button onClick={()=>onNavigate('/')} className="flex items-center gap-3" aria-label="Fleet OS home"><span className="grid h-9 w-9 place-items-center rounded-lg bg-cyan-400 text-slate-950"><Truck className="h-5 w-5"/></span><span className="text-base font-semibold tracking-tight">Fleet OS</span></button><nav className="hidden items-center gap-8 md:flex"><a href="#platform" className="text-sm text-slate-400 hover:text-white">Platform</a><a href="#workflow" className="text-sm text-slate-400 hover:text-white">Operating loop</a><a href="#automation" className="text-sm text-slate-400 hover:text-white">Automation</a><a href="#security" className="text-sm text-slate-400 hover:text-white">Security</a></nav><div className="hidden items-center gap-3 md:flex"><button onClick={()=>onNavigate('/sign-in')} className="px-4 py-2 text-sm font-medium text-slate-300 hover:text-white">Sign in</button><button onClick={()=>onNavigate('/sign-up')} className="rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-300">Start free</button></div><button onClick={()=>setMenuOpen(v=>!v)} className="grid h-10 w-10 place-items-center rounded-lg border border-white/10 md:hidden" aria-label="Toggle navigation">{menuOpen?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</button></div>{menuOpen&&<div className="border-t border-white/10 px-5 py-5 md:hidden"><div className="grid gap-2">{[['Platform','#platform'],['Operating loop','#workflow'],['Automation','#automation'],['Security','#security']].map(([label,href])=><a key={label} href={href} onClick={()=>setMenuOpen(false)} className="rounded-lg px-3 py-2.5 text-sm text-slate-300 hover:bg-white/5">{label}</a>)}<div className="mt-3 grid grid-cols-2 gap-3"><button onClick={()=>onNavigate('/sign-in')} className="rounded-lg border border-white/10 px-4 py-2.5 text-sm">Sign in</button><button onClick={()=>onNavigate('/sign-up')} className="rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-slate-950">Start free</button></div></div></div>}</header>

    <section className="relative px-5 pb-24 pt-36 sm:px-8 sm:pt-44 lg:px-10 lg:pb-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(34,211,238,0.17),transparent_36%),radial-gradient(circle_at_12%_78%,rgba(20,184,166,0.10),transparent_28%)]"/><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-5xl text-center"><div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[0.08] px-3 py-1.5 text-xs font-medium text-cyan-200"><Zap className="h-3.5 w-3.5"/>From first fleet email to final payment</div><h1 className="mt-7 text-5xl font-semibold leading-[1.01] tracking-[-0.055em] sm:text-6xl lg:text-7xl">The AI operating system for fleet service.</h1><p className="mx-auto mt-7 max-w-3xl text-base leading-7 text-slate-400 sm:text-lg sm:leading-8">Fleet OS is designed to turn customer communication into organized fleet work: understand the request, identify the vehicles, build the work, schedule it, dispatch the team, complete the service, and close the financial loop.</p><div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><button onClick={()=>onNavigate('/sign-up')} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-cyan-400 px-6 text-sm font-semibold text-slate-950 shadow-xl shadow-cyan-500/15 hover:bg-cyan-300 sm:w-auto">Start your workspace <ArrowRight className="h-4 w-4"/></button><button onClick={()=>onNavigate('/sign-in')} className="flex h-12 w-full items-center justify-center rounded-xl border border-white/10 bg-white/[0.035] px-6 text-sm font-medium hover:bg-white/[0.07] sm:w-auto">Open Fleet OS</button></div><div className="mt-6 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs text-slate-500">{['Neon-authenticated workspaces','Role-based team access','AgentMail operations inbox','NHTSA VIN intelligence','Browserbase web research'].map(item=><span key={item} className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-teal-300"/>{item}</span>)}</div></div>

      <div className="mx-auto mt-16 grid max-w-6xl gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[28px] border border-white/10 bg-[#0b1628] p-6 shadow-2xl shadow-black/30 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-300">Fleet Agent</p><h2 className="mt-2 text-2xl font-semibold">Inbox → operation</h2></div><Bot className="h-7 w-7 text-cyan-300"/></div><div className="mt-6 rounded-2xl border border-white/8 bg-[#08111f] p-4"><p className="text-sm leading-6 text-slate-300">“Bob at Closet World sent 10 vans for Sunday service.”</p></div><div className="mt-4 space-y-2 text-sm">{['Resolve Bob + Closet World Fleet Account','Read attachment and extract 10 vehicles','Decode valid VINs with NHTSA','Match existing vehicles and flag new ones','Apply Sunday service agreement and approval rules','Prepare work orders, schedule, dispatch, and confirmation'].map((item,index)=><div key={item} className="flex items-center gap-3 rounded-xl border border-white/7 bg-white/[0.025] px-4 py-3"><span className="grid h-6 w-6 place-items-center rounded-full bg-cyan-400/10 text-[10px] font-bold text-cyan-300">{index+1}</span><span className="text-slate-300">{item}</span></div>)}</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><VisionCard icon={<Building2 className="h-5 w-5"/>} title="Fleet Account 360" copy="Company, contacts, locations, vehicles, work history, documents, financials, communication, and service agreement in one account."/><VisionCard icon={<Users className="h-5 w-5"/>} title="Purpose-built team workspaces" copy="Owners govern the business. Dispatchers run the day. Technicians execute assigned work from a mobile-first operating view."/><VisionCard icon={<ShieldCheck className="h-5 w-5"/>} title="Rules before autonomy" copy="The agent can only act inside user permissions, organization policy, account service agreements, workflow state, and confirmation requirements."/></div></div>
    </div></section>

    <section id="platform" className="border-y border-white/8 bg-white/[0.018] px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">One operational system</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Every important handoff shares the same context.</h2><p className="mt-4 leading-7 text-slate-400">FleetOS is not a chatbot attached to a database. The agent, inbox, fleet accounts, vehicles, scheduling, dispatch, technician execution, documents, and financials are designed to operate on the same canonical records.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{capabilities.map(({icon:Icon,title,copy})=><article key={title} className="rounded-2xl border border-white/8 bg-[#0a1424] p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-300"><Icon className="h-5 w-5"/></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></article>)}</div></div></section>

    <section id="workflow" className="px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">The operating loop</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">One request. One chain of responsibility.</h2></div><div className="mt-10 grid gap-3 lg:grid-cols-2">{workflow.map(([number,title,copy])=><div key={number} className="grid grid-cols-[48px_1fr] gap-4 rounded-2xl border border-white/8 bg-white/[0.025] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-xs font-semibold text-cyan-300">{number}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{copy}</p></div></div>)}</div></div></section>

    <section id="automation" className="border-y border-white/8 bg-[#0a1424] px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Service agreements + automation</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">Teach FleetOS how each client operates.</h2><p className="mt-4 text-sm leading-7 text-slate-400">Preferred service days, service windows, SLA, approval thresholds, PO requirements, billing cadence, technician rules, communication recipients, and automation level become deterministic account policy—not facts the AI has to guess.</p></div><div className="grid gap-4 md:grid-cols-3">{[['Manual','Agent understands and prepares. A person controls each operation.'],['Assisted','Agent prepares the complete transaction. A person reviews and approves once.'],['Autopilot','Repeatable work inside approved account policy executes automatically; exceptions stop for review.']].map(([title,copy],i)=><div key={title} className={`rounded-2xl border p-5 ${i===1?'border-cyan-300/25 bg-cyan-300/[0.06]':'border-white/8 bg-white/[0.025]'}`}><p className="text-sm font-semibold text-white">{title}</p><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></div>)}</div></div></div></section>

    <section id="security" className="px-5 py-24 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl rounded-3xl border border-cyan-300/15 bg-cyan-300/[0.055] p-7 sm:p-10 lg:flex lg:items-center lg:justify-between"><div className="max-w-3xl"><ShieldCheck className="h-8 w-8 text-teal-300"/><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">The AI never becomes the permission system.</h2><p className="mt-4 leading-7 text-slate-400">Neon Auth verifies identity. FleetOS memberships determine the workspace. Server-enforced permissions determine what each role may do. Account policy and workflow state narrow automation further. The agent operates inside those boundaries.</p></div><button onClick={()=>onNavigate('/sign-up')} className="mt-8 inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-6 text-sm font-semibold text-slate-950 lg:mt-0">Build your operation <ArrowRight className="h-4 w-4"/></button></div></section>

    <footer className="border-t border-white/8 px-5 py-8 text-sm text-slate-500 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Truck className="h-4 w-4 text-cyan-300"/><span>Fleet OS · AI Revenue + Operations</span></div><span>Fleet work from inbox to invoice.</span></div></footer>
  </main>;
}

function VisionCard({icon,title,copy}:{icon:React.ReactNode;title:string;copy:string}){return <div className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><div className="text-cyan-300">{icon}</div><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></div>}
