import React, { useEffect, useRef, useState } from 'react';
import { Bot, FileText, Image as ImageIcon, MoreVertical, Paperclip, Send, Sliders, Sparkles, User, Users, X, XCircle } from 'lucide-react';
import confetti from 'canvas-confetti';
import { SendEmailPayload, Contact } from '../types';
import { fleetFetch } from '../lib/fleetApi';

interface ComposeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSendEmail: (payload: SendEmailPayload) => Promise<boolean>;
  initialTo?: string;
  initialSubject?: string;
  initialBody?: string;
  activeInbox: string;
  contacts?: Contact[];
}

type PendingAttachment={id:string;filename:string;contentType:string;size:number;content:string};
const MAX_FILES=4,MAX_BYTES=3_000_000;
const readBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||'').split(',')[1]||'');reader.onerror=()=>reject(reader.error||new Error('Could not read attachment'));reader.readAsDataURL(file);});

export const ComposeModal: React.FC<ComposeModalProps> = ({ isOpen,onClose,onSendEmail,initialTo='',initialSubject='',initialBody='',activeInbox,contacts=[] }) => {
  const [to,setTo]=useState(initialTo),[subject,setSubject]=useState(initialSubject),[body,setBody]=useState(initialBody),[promptInput,setPromptInput]=useState('');
  const [currentTone,setCurrentTone]=useState<'Professional'|'Friendly'|'Concise'>('Professional'),[toneProgress,setToneProgress]=useState(75);
  const [isSending,setIsSending]=useState(false),[isDrafting,setIsDrafting]=useState(false),[isRewritingTone,setIsRewritingTone]=useState(false),[showContactDropdown,setShowContactDropdown]=useState(false);
  const [attachments,setAttachments]=useState<PendingAttachment[]>([]),[attachmentError,setAttachmentError]=useState('');
  const dropdownRef=useRef<HTMLDivElement>(null),fileInputRef=useRef<HTMLInputElement>(null),imageInputRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{if(isOpen){setTo(initialTo);setSubject(initialSubject);setBody(initialBody);setPromptInput('');setShowContactDropdown(false);setAttachments([]);setAttachmentError('');}},[isOpen,initialTo,initialSubject,initialBody]);
  const matchingContacts=contacts.filter(c=>{if(!to)return true;const q=to.toLowerCase().trim();return c.name.toLowerCase().includes(q)||c.email.toLowerCase().includes(q)||(c.company&&c.company.toLowerCase().includes(q));});
  const handleSelectContact=(contact:Contact)=>{setTo(contact.email);setShowContactDropdown(false);};
  const addFiles=async(files:FileList|null)=>{if(!files)return;setAttachmentError('');const selected=Array.from(files).slice(0,Math.max(0,MAX_FILES-attachments.length));const total=attachments.reduce((s,f)=>s+f.size,0)+selected.reduce((s,f)=>s+f.size,0);if(total>MAX_BYTES)return setAttachmentError('Attachments must total 3 MB or less.');try{const next=await Promise.all(selected.map(async file=>({id:crypto.randomUUID(),filename:file.name.slice(0,240),contentType:file.type||'application/octet-stream',size:file.size,content:await readBase64(file)})));setAttachments(current=>[...current,...next].slice(0,MAX_FILES));}catch(e){setAttachmentError(e instanceof Error?e.message:'Could not read attachment.');}finally{if(fileInputRef.current)fileInputRef.current.value='';if(imageInputRef.current)imageInputRef.current.value='';}};
  if(!isOpen)return null;

  const handleSend=async(e?:React.FormEvent)=>{e?.preventDefault();if(!to.trim()||!subject.trim()||!body.trim()||isSending)return;setIsSending(true);setAttachmentError('');try{let success=false;if(attachments.length){const response=await fleetFetch('/api/agentmail/send-with-attachments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inbox:activeInbox,to:to.trim(),subject:subject.trim(),body:body.trim(),attachments:attachments.map(({filename,contentType,content})=>({filename,contentType,content}))})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Message could not be sent');}success=true;}else success=await onSendEmail({inbox:activeInbox,to:to.trim(),subject:subject.trim(),body:body.trim()});if(success){confetti({particleCount:70,spread:60,origin:{y:.8}});onClose();}}catch(e){setAttachmentError(e instanceof Error?e.message:'Message could not be sent');}finally{setIsSending(false);}};
  const handleGenerateDraftFromPrompt=async()=>{if(!promptInput.trim()||isDrafting)return;setIsDrafting(true);try{const res=await fetch('/api/generate-draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({promptText:promptInput,tone:currentTone,recipient:to,contextSubject:subject})});if(res.ok){const data=await res.json();if(data.subject&&!subject)setSubject(data.subject);if(data.body)setBody(data.body);setPromptInput('');}}catch(err){console.error('Draft generation error:',err);}finally{setIsDrafting(false);}};
  const handleToneAdjustment=async(targetTone:'warmer'|'concise'|'professional')=>{if(!body.trim()||isRewritingTone)return;setIsRewritingTone(true);try{const res=await fetch('/api/rewrite-tone',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,subject,tone:targetTone})});if(res.ok){const data=await res.json();if(data.rewrittenBody){setBody(data.rewrittenBody);if(targetTone==='warmer'){setCurrentTone('Friendly');setToneProgress(50);}else if(targetTone==='concise'){setCurrentTone('Concise');setToneProgress(90);}else{setCurrentTone('Professional');setToneProgress(75);}}}}catch(e){console.error('Tone adjust error:',e);}finally{setIsRewritingTone(false);}};

  return <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4 sm:p-6 select-none animate-fadeIn"><div id="compose-modal-container" className="bg-white w-full max-w-5xl h-[85vh] max-h-[780px] rounded-2xl shadow-2xl border border-slate-200 flex flex-col overflow-hidden">
    <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-white shrink-0"><div className="flex items-center gap-3"><button onClick={onClose} className="p-1 rounded-lg text-slate-500 hover:text-slate-800 hover:bg-slate-100"><X className="w-5 h-5"/></button><h2 className="text-lg font-bold text-slate-900">New Message</h2></div><div className="flex items-center gap-3"><button title="Save draft" className="p-2 rounded-lg text-slate-500 hover:bg-slate-100"><FileText className="w-4 h-4"/></button><button title="More options" className="p-2 rounded-lg text-slate-500 hover:bg-slate-100"><MoreVertical className="w-4 h-4"/></button><button id="compose-modal-send-btn" onClick={()=>void handleSend()} disabled={!to.trim()||!subject.trim()||!body.trim()||isSending} className="flex items-center gap-2 px-5 py-2 rounded-xl bg-[#0b57d0] hover:bg-[#0848b0] disabled:opacity-50 text-white text-sm font-semibold"><span>{isSending?'Sending...':'Send'}</span><Send className="w-4 h-4"/></button></div></div>
    <div className="flex-1 flex overflow-hidden"><div className="flex-1 flex flex-col justify-between p-6 overflow-y-auto border-r border-slate-200"><div className="space-y-4">
      <div className="relative border-b border-slate-200 pb-3"><div className="flex items-center gap-3"><span className="text-sm font-medium text-slate-500 w-16 flex items-center gap-1.5"><User className="w-3.5 h-3.5 text-slate-400"/><span>To</span></span><input id="compose-to-input" type="text" placeholder="Enter email or search contacts..." value={to} onChange={e=>{setTo(e.target.value);setShowContactDropdown(true)}} onFocus={()=>setShowContactDropdown(true)} className="flex-1 text-sm text-slate-900 placeholder-slate-400 focus:outline-none bg-transparent"/>{contacts.length>0&&<button type="button" onClick={()=>setShowContactDropdown(!showContactDropdown)} className="text-xs text-[#0b57d0] font-medium flex items-center gap-1 px-2 py-0.5 rounded-md hover:bg-blue-50"><Users className="w-3.5 h-3.5"/><span>Contacts ({contacts.length})</span></button>}</div>{showContactDropdown&&matchingContacts.length>0&&<div ref={dropdownRef} className="absolute left-16 right-0 top-full mt-1 bg-white rounded-xl border border-slate-200 shadow-xl z-50 max-h-56 overflow-y-auto divide-y divide-slate-100"><div className="p-2 bg-slate-50 text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center justify-between"><span>Suggested Contacts</span><button type="button" onClick={()=>setShowContactDropdown(false)}>✕</button></div>{matchingContacts.slice(0,6).map(c=><div key={c.id} onClick={()=>handleSelectContact(c)} className="p-2.5 hover:bg-blue-50/80 cursor-pointer flex items-center justify-between gap-3"><div className="flex items-center gap-2.5 min-w-0"><img src={c.avatarUrl||`https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(c.name||c.email)}`} alt={c.name} className="w-7 h-7 rounded-lg object-cover border border-slate-200 shrink-0"/><div className="min-w-0"><p className="text-xs font-semibold text-slate-900 truncate">{c.name}{c.company&&<span className="text-[11px] font-normal text-slate-500 ml-1.5">({c.company})</span>}</p><p className="text-[11px] font-mono text-slate-500 truncate">{c.email}</p></div></div></div>)}</div>}</div>
      <div className="flex items-center gap-3 border-b border-slate-200 pb-3"><span className="text-sm font-medium text-slate-500 w-16">Subject</span><input id="compose-subject-input" type="text" placeholder="Subject" value={subject} onChange={e=>setSubject(e.target.value)} className="flex-1 text-sm text-slate-900 placeholder-slate-400 focus:outline-none bg-transparent font-medium"/></div>
      <textarea id="compose-body-textarea" rows={14} placeholder="Start writing..." value={body} onChange={e=>setBody(e.target.value)} className="w-full text-sm text-slate-900 placeholder-slate-400 focus:outline-none resize-none bg-transparent leading-relaxed"/>
      {!!attachments.length&&<div className="flex flex-wrap gap-2">{attachments.map(file=><div key={file.id} className="flex max-w-56 items-center gap-2 rounded-xl border bg-slate-50 px-3 py-2 text-xs"><FileText className="h-4 w-4 text-slate-500"/><span className="truncate">{file.filename}</span><button type="button" onClick={()=>setAttachments(a=>a.filter(x=>x.id!==file.id))}><XCircle className="h-4 w-4 text-slate-400"/></button></div>)}</div>}{attachmentError&&<p className="text-xs font-medium text-red-600">{attachmentError}</p>}
    </div><div className="flex items-center gap-3 pt-4 border-t border-slate-100 text-slate-500"><input ref={fileInputRef} type="file" multiple className="hidden" onChange={e=>void addFiles(e.target.files)}/><input ref={imageInputRef} type="file" accept="image/*" multiple className="hidden" onChange={e=>void addFiles(e.target.files)}/><button type="button" title="Attach file" onClick={()=>fileInputRef.current?.click()} disabled={attachments.length>=MAX_FILES} className="p-2 rounded-lg hover:text-slate-900 hover:bg-slate-100 disabled:opacity-40"><Paperclip className="w-5 h-5"/></button><button type="button" title="Attach image" onClick={()=>imageInputRef.current?.click()} disabled={attachments.length>=MAX_FILES} className="p-2 rounded-lg hover:text-slate-900 hover:bg-slate-100 disabled:opacity-40"><ImageIcon className="w-5 h-5"/></button><span className="text-[11px] text-slate-400">Up to 4 files / 3 MB total</span></div></div>
    <div id="ai-assist-sidebar" className="w-80 md:w-96 bg-white p-6 space-y-5 overflow-y-auto shrink-0 select-none"><div className="flex items-center gap-2 text-[#0b57d0]"><Bot className="w-5 h-5"/><h3 className="text-sm font-bold uppercase tracking-wider">AI ASSIST</h3></div><div className="p-4 rounded-2xl border border-slate-200 bg-white space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-slate-800 text-xs font-semibold"><Sliders className="w-4 h-4 text-slate-500"/><span>Tone Analysis</span></div><span className="text-xs font-bold text-[#0b57d0]">{currentTone}</span></div><div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-[#0b57d0] rounded-full" style={{width:`${toneProgress}%`}}/></div><div className="space-y-1.5 pt-1"><button onClick={()=>void handleToneAdjustment('warmer')} disabled={isRewritingTone||!body.trim()} className="w-full text-left px-3 py-1.5 rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50">Make it warmer</button><button onClick={()=>void handleToneAdjustment('concise')} disabled={isRewritingTone||!body.trim()} className="w-full text-left px-3 py-1.5 rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50">More concise</button></div></div><div className="p-4 rounded-2xl border border-slate-200 bg-white space-y-3 text-center"><div className="flex items-center gap-2 text-slate-800 text-xs font-semibold text-left"><Sparkles className="w-4 h-4 text-slate-500"/><span>Suggestions</span></div><div className="py-4 px-2 space-y-2"><FileText className="w-8 h-8 mx-auto text-slate-300"/><p className="text-xs text-slate-500 leading-relaxed max-w-[220px] mx-auto">{body.trim().length>30?'Clarity score: 94%. Your key arguments are well articulated.':'Start writing to get real-time feedback and suggestions.'}</p></div></div><div className="p-4 rounded-2xl border border-slate-200 bg-white space-y-3"><div className="flex items-center gap-2 text-slate-800 text-xs font-semibold"><Sparkles className="w-4 h-4 text-slate-500"/><span>Draft from prompt</span></div><textarea id="ai-prompt-input" rows={3} value={promptInput} onChange={e=>setPromptInput(e.target.value)} placeholder="Briefly describe what you want to say..." className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:border-[#0b57d0] resize-none"/><button id="ai-generate-draft-btn" type="button" onClick={()=>void handleGenerateDraftFromPrompt()} disabled={!promptInput.trim()||isDrafting} className="w-full py-2.5 px-4 rounded-xl bg-slate-100 hover:bg-[#0b57d0] hover:text-white disabled:opacity-50 text-slate-700 text-xs font-semibold">{isDrafting?'Generating Draft...':'Generate Draft'}</button></div></div>
    </div>
  </div></div>;
};
