import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, BadgeDollarSign, Bot, Building2, CalendarClock, Car, CheckCircle2, ClipboardList, Clock3, FileText, RefreshCw, Target, UserRoundCog, Wrench } from 'lucide-react';
import { fleetFetch } from '../lib/fleetApi';
import type { AppTab } from './Sidebar';

type Access={role:string;permissions:string[]};
type AttentionItem={kind:string;title:string;subtitle:string;severity:'critical'|'warning'|'info';target:AppTab};
type OperationItem={id:string;startsAt:string;status:string;customerName:string|null;unitNumber:string|null;workOrderNumber:string|null};
type ActivityItem={id:string;number:string;status:string;customerName:string|null;unitNumber:string|null;updatedAt:string};
type DashboardData={generatedAt:string;role?:string;permissions?:string[];summary:{fleetAccounts:number;vehicles:number;openWorkOrders:number;activeProspects:number};attention:AttentionItem[];upcomingOperations:OperationItem[];financials:{outstanding:string;overdue:string;collected:string};pipeline:{total:number;followUpDue:number;stages:Record<string,number>};recentActivity:ActivityItem[]};
type TechnicianJob={id:string;number:string;status:string;priority:string;complaint:string|null;scheduledAt:string|null;requestedServices:string[]|null;customerName:string|null;unitNumber:string|null;year:number|null;make:string|null;model:string|null};
type TechnicianData={profile:{id:string;name:string;active:boolean}|null;summary:{assigned:number;inProgress:number;completed:number};jobs:TechnicianJob[]};

interface DashboardViewProps{onNavigate:(tab:AppTab)=>void;onAskAgent:(prompt:string)=>void}
const label=(value:string)=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const money=(value:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));
const when=(value:string)=>new Intl.DateTimeFormat(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'}).format(new Date(value));

export const DashboardView:React.FC<DashboardViewProps>=({onNavigate,onAskAgent})=>{
  const[access,setAccess]=useState<Access|null>(null);const[data,setData]=useState<DashboardData|null>(null);const[tech,setTech]=useState<TechnicianData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const accessRes=await fleetFetch('/api/access');const accessBody=await accessRes.json();if(!accessRes.ok)throw new Error(accessBody.error||'Access unavailable');setAccess(accessBody);if(accessBody.role==='technician'){const r=await fleetFetch('/api/technician/me');const body=await r.json();if(!r.ok)throw new Error(body.error||'Technician dashboard unavailable');setTech(body);setData(null);}else{const r=await fleetFetch('/api/dashboard');const body=await r.json();if(!r.ok)throw new Error(body.error||'Dashboard unavailable');setData(body);setTech(null);}}catch(e){setError(e instanceof Error?e.message:'Dashboard unavailable');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  if(loading&&!data&&!tech)return <div className="flex flex-1 items-center justify-center bg-slate-50"><RefreshCw className="h-5 w-5 animate-spin text-blue-600"/></div>;
  if(error&&!data&&!tech)return <div className="flex flex-1 items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-2xl border border-red-200 bg-white p-6 text-center shadow-sm"><AlertTriangle className="mx-auto h-6 w-6 text-red-500"/><p className="mt-3 font-semibold">Dashboard could not load</p><p className="mt-1 text-sm text-slate-500">{error}</p><button onClick={()=>void load()} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Retry</button></div></div>;
  if(access?.role==='technician'&&tech)return <TechnicianDashboard data={tech} onNavigate={onNavigate} onAskAgent={onAskAgent} refresh={load} loading={loading}/>;
  if(!data||!access)return null;
  return <OperationsDashboard data={data} access={access} onNavigate={onNavigate} onAskAgent={onAskAgent} refresh={load} loading={loading}/>;
};

function TechnicianDashboard({data,onNavigate,onAskAgent,refresh,loading}:{data:TechnicianData;onNavigate:(tab:AppTab)=>void;onAskAgent:(prompt:string)=>void;refresh:()=>Promise<void>;loading:boolean}){
  const active=data.jobs.filter(j=>!['complete','completed','cancelled','canceled'].includes(j.status));const current=active.find(j=>['en_route','arrived','in_progress','review','authorization_pending','authorized'].includes(j.status))||active[0]||null;
  return <main className="min-w-0 flex-1 overflow-y-auto bg-slate-50"><div className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6 lg:p-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Technician OS</p><h2 className="mt-1 text-2xl font-bold text-slate-950">{data.profile?.name?`${data.profile.name}'s day`:'My assigned work'}</h2><p className="mt-1 text-sm text-slate-500">Only work assigned to your technician profile is shown.</p></div><button onClick={()=>void refresh()} className="rounded-xl border bg-white p-2.5 text-slate-600"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
    <section className="grid grid-cols-3 gap-3"><TechKpi label="Assigned" value={data.summary.assigned}/><TechKpi label="In progress" value={data.summary.inProgress}/><TechKpi label="Completed" value={data.summary.completed}/></section>
    {current?<section className="rounded-2xl border border-blue-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Current / next job</p><h3 className="mt-1 text-xl font-bold">{current.number} · {current.customerName||'Fleet Account'}</h3><p className="mt-2 text-sm text-slate-600">{[current.unitNumber?`Unit ${current.unitNumber}`:null,current.year,current.make,current.model].filter(Boolean).join(' · ')}</p><p className="mt-2 text-sm text-slate-500">{current.complaint||current.requestedServices?.join(', ')||'Service request'}</p></div><span className="self-start rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{label(current.status)}</span></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={()=>onNavigate('work-orders')} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Open job workflow</button><button onClick={()=>onAskAgent(`Summarize my assigned work order ${current.number} and tell me what I need to do next.`)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700">Ask Fleet Agent</button></div></section>:<section className="rounded-2xl border border-dashed bg-white p-10 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-emerald-500"/><p className="mt-3 font-bold">No active assigned work</p><p className="mt-1 text-sm text-slate-500">New assignments will appear here after dispatch.</p></section>}
    <section className="rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-bold">My work queue</h3><p className="text-xs text-slate-500">Assigned and active work orders</p></div><div className="divide-y">{active.map(job=><button key={job.id} onClick={()=>onNavigate('work-orders')} className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-slate-50"><ClipboardList className="h-4 w-4 text-slate-400"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{job.number} · {job.customerName||'Fleet Account'}</p><p className="mt-0.5 truncate text-xs text-slate-500">{job.unitNumber?`Unit ${job.unitNumber} · `:''}{job.scheduledAt?new Date(job.scheduledAt).toLocaleString():'No scheduled time'}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{label(job.status)}</span></button>)}{!active.length&&<div className="p-8 text-center text-sm text-slate-500">No active jobs.</div>}</div></section>
  </div></main>;
}
function TechKpi({label:copy,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-2xl font-bold text-slate-950">{value}</p><p className="text-xs font-semibold text-slate-500">{copy}</p></div>}

function OperationsDashboard({data,access,onNavigate,onAskAgent,refresh,loading}:{data:DashboardData;access:Access;onNavigate:(tab:AppTab)=>void;onAskAgent:(prompt:string)=>void;refresh:()=>Promise<void>;loading:boolean}){
  const can=(p:string)=>access.permissions.includes(p);const kpis=[can('fleet_accounts.view')&&['Fleet Accounts',data.summary.fleetAccounts,Building2,'customers'],can('vehicles.view')&&['Active Vehicles',data.summary.vehicles,Car,'vehicles'],can('work_orders.view')&&['Open Work Orders',data.summary.openWorkOrders,ClipboardList,'work-orders'],can('prospects.view')&&['Active Prospects',data.summary.activeProspects,Target,'prospects']].filter(Boolean) as [string,number,React.ElementType,AppTab][];
  const quick=[['Fleet Accounts','customers',Building2,'fleet_accounts.view'],['Vehicles','vehicles',Car,'vehicles.view'],['Work Orders','work-orders',ClipboardList,'work_orders.view'],['Maintenance','maintenance',Wrench,'work_orders.view'],['Schedule','schedule',CalendarClock,'schedule.view'],['Dispatch','dispatch',UserRoundCog,'dispatch.view'],['Prospects','prospects',Target,'prospects.view'],['Financials','financials',BadgeDollarSign,'financials.view'],['Documents','documents',FileText,'documents.view']].filter(x=>can(x[3] as string)) as [string,AppTab,React.ElementType,string][];
  return <main className="min-w-0 flex-1 overflow-y-auto bg-slate-50"><div className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Operations command center</p><h2 className="mt-1 text-2xl font-bold">Fleet OS Dashboard</h2><p className="mt-1 text-sm text-slate-500 capitalize">{access.role} workspace · live canonical records</p></div><button onClick={()=>void refresh()} className="rounded-xl border bg-white p-2.5"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
    <section className={`grid gap-3 ${kpis.length>2?'grid-cols-2 xl:grid-cols-4':'grid-cols-2'}`}>{kpis.map(([copy,value,Icon,tab])=><button key={copy} onClick={()=>onNavigate(tab)} className="rounded-2xl border bg-white p-4 text-left shadow-sm"><Icon className="h-5 w-5 text-blue-600"/><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-xs font-semibold text-slate-500">{copy}</p></button>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-bold">Attention Required</h3><p className="text-xs text-slate-500">Only signals your role is allowed to see</p></div><div className="divide-y">{data.attention.length?data.attention.map((item,i)=><button key={`${item.kind}-${i}`} onClick={()=>onNavigate(item.target)} className="flex w-full items-start gap-3 px-5 py-4 text-left hover:bg-slate-50"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${item.severity==='critical'?'bg-red-500':item.severity==='warning'?'bg-amber-500':'bg-blue-500'}`}/><div className="flex-1"><p className="text-sm font-bold">{item.title}</p><p className="text-xs text-slate-500">{item.subtitle}</p></div><ArrowRight className="h-4 w-4 text-slate-300"/></button>):<div className="p-8 text-center text-sm text-slate-500">No current attention items.</div>}</div></div>{can('agent.use')&&<div className="rounded-2xl bg-slate-950 p-5 text-white"><Bot className="h-5 w-5 text-blue-300"/><h3 className="mt-3 font-bold">Fleet Agent</h3><p className="mt-1 text-xs text-slate-400">The agent inherits your FleetOS permissions.</p><div className="mt-4 grid gap-2">{['What needs attention?','Show open work orders','Summarize today’s operation'].map(p=><button key={p} onClick={()=>onAskAgent(p)} className="rounded-xl border border-white/10 bg-white/5 p-2.5 text-left text-sm">{p}</button>)}</div></div>}</section>
    <section className="grid gap-5 xl:grid-cols-2">{can('schedule.view')&&<div className="rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-bold">Next 24 Hours</h3></div><div className="divide-y">{data.upcomingOperations.map(item=><button key={item.id} onClick={()=>onNavigate('schedule')} className="grid w-full grid-cols-[90px_1fr_auto] gap-3 px-5 py-3 text-left"><span className="text-xs font-semibold text-blue-700">{when(item.startsAt)}</span><span className="truncate text-sm font-semibold">{item.customerName||'Fleet account'}{item.unitNumber?` · Unit ${item.unitNumber}`:''}</span><span className="text-[10px] font-bold text-slate-500">{label(item.status)}</span></button>)}{!data.upcomingOperations.length&&<div className="p-8 text-center text-sm text-slate-500">No scheduled work in the next 24 hours.</div>}</div></div>}{can('financials.view')&&<div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Financial Position</h3><div className="mt-4 grid grid-cols-3 gap-3"><Mini label="Outstanding" value={money(data.financials.outstanding)}/><Mini label="Overdue" value={money(data.financials.overdue)}/><Mini label="Collected" value={money(data.financials.collected)}/></div></div>}</section>
    <section><h3 className="mb-3 font-bold">Fleet OS</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{quick.map(([copy,tab,Icon])=><button key={tab} onClick={()=>onNavigate(tab)} className="flex items-center gap-3 rounded-xl border bg-white p-3 text-left shadow-sm"><Icon className="h-4 w-4 text-slate-500"/><span className="text-sm font-semibold">{copy}</span></button>)}</div></section>
  </div></main>;
}
function Mini({label:copy,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-500">{copy}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
