import React, { useMemo, useState } from 'react';
import {
  ArrowRight, BadgeDollarSign, Building2, CalendarClock, Car, CheckCircle2,
  ChevronDown, CircleDollarSign, ClipboardList, Clock3, Download, FileCheck2,
  FileText, Files, Filter, Inbox, MapPin, MoreHorizontal, PackageCheck,
  PackageSearch, Plus, Search, ShieldCheck, Sparkles, TrendingUp, Truck,
  UserRound, Warehouse, Wrench, XCircle
} from 'lucide-react';

export type FleetModuleId =
  | 'vehicles' | 'work-orders' | 'maintenance' | 'schedule' | 'dispatch'
  | 'parts' | 'customers' | 'financials' | 'documents';

interface FleetModuleViewProps { module: FleetModuleId; onOpenInbox: () => void; }
type Icon = React.ComponentType<{ className?: string }>;
type Tone = 'blue' | 'green' | 'amber' | 'red' | 'slate' | 'violet';
const tones: Record<Tone, string> = {
  blue:'bg-blue-50 text-blue-700 ring-blue-600/10', green:'bg-emerald-50 text-emerald-700 ring-emerald-600/10',
  amber:'bg-amber-50 text-amber-700 ring-amber-600/10', red:'bg-red-50 text-red-700 ring-red-600/10',
  slate:'bg-slate-100 text-slate-600 ring-slate-500/10', violet:'bg-violet-50 text-violet-700 ring-violet-600/10'
};

const Badge=({children,tone='slate'}:{children:React.ReactNode;tone?:Tone})=><span className={`inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-bold ring-1 ring-inset ${tones[tone]}`}>{children}</span>;
const Kpi=({label,value,detail,icon:Icon,tone='blue'}:{label:string;value:string;detail:string;icon:Icon;tone?:Tone})=><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-500">{label}</p><span className={`rounded-lg p-2 ${tones[tone]}`}><Icon className="h-4 w-4"/></span></div><p className="mt-3 text-2xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>;
const Header=({title,eyebrow,description,icon:Icon,primary}:{title:string;eyebrow:string;description:string;icon:Icon;primary:string})=><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-sm"><Icon className="h-6 w-6"/></div><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">{eyebrow}</p><h2 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></div></div><button className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white shadow-sm hover:bg-blue-700"><Plus className="h-4 w-4"/>{primary}</button></div>;
const Shell=({title,description,action,children}:{title:string;description:string;action?:React.ReactNode;children:React.ReactNode})=><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-0.5 text-xs text-slate-500">{description}</p></div>{action}</div>{children}</section>;
const Table=({headers,rows}:{headers:string[];rows:React.ReactNode[][]})=><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50"><tr>{headers.map(h=><th key={h} className="whitespace-nowrap px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr key={i} className="hover:bg-slate-50/70">{r.map((c,j)=><td key={j} className="whitespace-nowrap px-5 py-4 text-sm text-slate-600">{c}</td>)}</tr>)}</tbody></table></div>;
const Toolbar=({search,setSearch,filter,setFilter,options}:{search:string;setSearch:(x:string)=>void;filter:string;setFilter:(x:string)=>void;options:string[]})=><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…" className="h-9 w-44 rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></label><label className="relative"><Filter className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="h-9 appearance-none rounded-xl border border-slate-200 bg-white pl-9 pr-8 text-sm font-semibold"><option>All</option>{options.map(x=><option key={x}>{x}</option>)}</select><ChevronDown className="absolute right-2 top-2.5 h-4 w-4 text-slate-400"/></label></div>;
const Stats=({items}:{items:Array<[string,string,string,Icon,Tone?]>})=><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(x=><Kpi key={x[0]} label={x[0]} value={x[1]} detail={x[2]} icon={x[3]} tone={x[4]}/>)}</div>;

const WorkOrders=()=>{const[search,setSearch]=useState('');const[filter,setFilter]=useState('All');const data=[['WO-2048','2021 Ford Transit 250','Brake inspection','In progress','Maya R.','Today, 2:30 PM','$1,240'],['WO-2047','2022 Chevrolet Silverado','Oil + filter service','Awaiting approval','Unassigned','Today, 4:00 PM','$486'],['WO-2046','2020 Ram ProMaster','Cooling system repair','Parts hold','Jon B.','Sep 1','$2,860'],['WO-2045','2023 Ford F-150','30k preventive service','Scheduled','Elena G.','Sep 2','$735'],['WO-2044','2019 Isuzu NPR','DOT inspection','Completed','Maya R.','Aug 30','$390']];const rows=data.filter(r=>(filter==='All'||r[3]===filter)&&r.join(' ').toLowerCase().includes(search.toLowerCase()));return <><Header title="Work Orders" eyebrow="Service operations" description="Manage every repair from intake and authorization through completion." icon={ClipboardList} primary="New work order"/><Stats items={[[ 'Open work orders','28','6 need attention',ClipboardList],[ 'Awaiting approval','7','$14,280 pending',Clock3,'amber'],['In service','12','4 completing today',Wrench,'violet'],['Completed this month','84','+12% vs last month',CheckCircle2,'green']]}/><div className="mt-6"><Shell title="Active work orders" description="Prioritized by commitment date and service risk" action={<Toolbar {...{search,setSearch,filter,setFilter}} options={['In progress','Awaiting approval','Parts hold','Scheduled','Completed']}/>}><Table headers={['Work order','Vehicle','Service','Status','Technician','Promise','Estimate']} rows={rows.map(r=>[<b className="text-slate-900">{r[0]}</b>,<b className="text-slate-800">{r[1]}</b>,r[2],<Badge tone={r[3]==='Completed'?'green':r[3]==='Awaiting approval'||r[3]==='Parts hold'?'amber':r[3]==='In progress'?'blue':'violet'}>{r[3]}</Badge>,r[4],r[5],<b>{r[6]}</b>])}/></Shell></div></>};

const Maintenance=()=>{const rows=[['Unit 214','2021 Ford Transit','Oil & filter','Overdue','1,240 mi','WO-2042'],['Unit 088','2020 Ram ProMaster','Brake inspection','Due soon','320 mi','—'],['Unit 142','2022 Silverado 1500','Tire rotation','Due soon','9 days','WO-2049'],['Unit 301','2019 Isuzu NPR','DOT annual inspection','Upcoming','28 days','—'],['Unit 115','2023 Ford F-150','30k service','Upcoming','1,880 mi','WO-2045']];return <><Header title="Maintenance" eyebrow="Preventive maintenance" description="Stay ahead of downtime with mileage, time, and engine-hour service intervals." icon={Wrench} primary="Create service plan"/><Stats items={[[ 'Overdue','6','3 high-risk units',XCircle,'red'],['Due in 30 days','19','Across 14 vehicles',Clock3,'amber'],['PM compliance','94.2%','+2.4% this quarter',ShieldCheck,'green'],['Avoided downtime','38 hr','Estimated this month',TrendingUp]]}/><div className="mt-6"><Shell title="Maintenance forecast" description="Requirements calculated from odometer and calendar intervals"><Table headers={['Vehicle','Asset','Service','Timing','Remaining','Work order']} rows={rows.map(r=>[<b className="text-slate-900">{r[0]}</b>,r[1],r[2],<Badge tone={r[3]==='Overdue'?'red':r[3]==='Due soon'?'amber':'blue'}>{r[3]}</Badge>,r[4],<b className="text-blue-600">{r[5]}</b>])}/></Shell></div></>};

const Schedule=()=>{const[view,setView]=useState('Week');const days=[['MON 31','3 jobs','$2.8k'],['TUE 01','5 jobs','$6.1k'],['WED 02','4 jobs','$4.4k'],['THU 03','6 jobs','$7.9k'],['FRI 04','3 jobs','$3.2k']];const jobs=[['08:00','Acme Logistics','Unit 214 · Brake inspection','2h'],['10:30','Northstar Plumbing','Unit 088 · PM service','1.5h'],['13:00','Metro Foods','Unit 301 · DOT inspection','2h']];return <><Header title="Schedule" eyebrow="Service calendar" description="Balance service capacity, customer commitments, and technician availability." icon={CalendarClock} primary="Book appointment"/><div className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="font-bold">August 31 – September 4</h3><p className="text-xs text-slate-500">18 appointments · 72% bay utilization</p></div><div className="flex rounded-xl bg-slate-100 p-1">{['Day','Week','Month'].map(x=><button onClick={()=>setView(x)} key={x} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${view===x?'bg-white shadow-sm':'text-slate-500'}`}>{x}</button>)}</div></div><div className="grid min-w-[760px] grid-cols-5 divide-x divide-slate-100 overflow-x-auto">{days.map((d,di)=><div key={d[0]} className="min-h-[430px] p-3"><div className="mb-4 flex justify-between"><div><p className="text-[10px] font-bold tracking-widest text-slate-400">{d[0]}</p><p className="text-xs font-semibold">{d[1]}</p></div><Badge tone={di===1?'blue':'slate'}>{d[2]}</Badge></div>{jobs.slice(di%2,di%2+2).map((j,i)=><div key={j[0]} className={`mb-3 rounded-xl border-l-4 p-3 ${i?'border-violet-500 bg-violet-50':'border-blue-500 bg-blue-50'}`}><p className="text-[10px] font-bold text-slate-500">{Number(j[0].slice(0,2))+di}:00 · {j[3]}</p><p className="mt-2 text-xs font-bold">{j[1]}</p><p className="mt-1 text-[11px] text-slate-600">{j[2]}</p></div>)}</div>)}</div></div></>};

const Dispatch=()=>{const cols=[{n:'Ready',t:'slate' as Tone,j:[['WO-2049','Northstar Plumbing','Unit 142','9:30 AM'],['WO-2051','Acme Logistics','Unit 078','11:00 AM']]},{n:'En route',t:'blue' as Tone,j:[['WO-2048','Acme Logistics','Unit 214','ETA 14 min']]},{n:'On site',t:'violet' as Tone,j:[['WO-2046','Metro Foods','Unit 301','Arrived 10:18']]},{n:'Completed',t:'green' as Tone,j:[['WO-2044','Brightline HVAC','Unit 115','10:42 AM']]}];return <><Header title="Dispatch" eyebrow="Field operations" description="Coordinate technicians, routes, service windows, and live field status." icon={Truck} primary="Create dispatch"/><Stats items={[[ 'Jobs today','14','11 assigned',Truck],['On-time arrival','96%','Last 30 days',CheckCircle2,'green'],['Unassigned','3','Next window at 1 PM',UserRound,'amber']]}/><div className="mt-6 grid gap-4 xl:grid-cols-4">{cols.map(c=><section key={c.n} className="rounded-2xl bg-slate-100/80 p-3"><div className="mb-3 flex justify-between px-1"><h3 className="text-sm font-bold">{c.n}</h3><Badge>{c.j.length}</Badge></div>{c.j.map(j=><article key={j[0]} className="mb-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between"><b className="text-xs text-blue-600">{j[0]}</b><MoreHorizontal className="h-4 w-4 text-slate-400"/></div><p className="mt-3 text-sm font-bold">{j[1]}</p><p className="mt-1 text-xs text-slate-500">{j[2]}</p><div className="mt-4 flex justify-between border-t border-slate-100 pt-3"><span className="flex items-center gap-1 text-[11px]"><MapPin className="h-3 w-3"/>{j[3]}</span><span className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-900 text-[9px] font-bold text-white">MR</span></div></article>)}</section>)}</div></>};

const Parts=()=>{const[search,setSearch]=useState('');const[filter,setFilter]=useState('All');const data=[['BRK-4421','Front ceramic brake kit','Ford Transit 2020–24','12','4','Healthy'],['FLT-1098','Synthetic oil filter','Ford / GM light duty','3','8','Low stock'],['BEL-8830','Serpentine belt','Ram ProMaster 3.6L','0','2','Out of stock'],['PAD-2214','Heavy-duty rear pads','Isuzu NPR 2018–23','18','6','Healthy'],['CLN-3010','Fleet coolant concentrate','Universal · 1 gal','24','10','Healthy']];const rows=data.filter(r=>(filter==='All'||r[5]===filter)&&r.join(' ').toLowerCase().includes(search.toLowerCase()));return <><Header title="Parts" eyebrow="Inventory & procurement" description="Control stock, fitment, purchasing, and allocation to every work order." icon={PackageSearch} primary="Add part"/><Stats items={[[ 'Inventory value','$84,260','1,284 units on hand',Warehouse],['Low stock','8','5 with open demand',PackageSearch,'amber'],['On order','$12,480','9 purchase orders',Truck,'violet'],['Fill rate','96.8%','+1.2% this month',PackageCheck,'green']]}/><div className="mt-6"><Shell title="Parts inventory" description="Availability across the main warehouse and service vans" action={<Toolbar {...{search,setSearch,filter,setFilter}} options={['Healthy','Low stock','Out of stock']}/>}><Table headers={['Part no.','Description','Fitment','On hand','Reorder at','Status']} rows={rows.map(r=>[<b>{r[0]}</b>,<b>{r[1]}</b>,r[2],r[3],r[4],<Badge tone={r[5]==='Healthy'?'green':r[5]==='Low stock'?'amber':'red'}>{r[5]}</Badge>])}/></Shell></div></>};

const Customers=()=>{const[search,setSearch]=useState('');const data=[['Acme Logistics','42 vehicles','Jordan Lee','jordan@acmelogistics.com','$18,420','Active'],['Northstar Plumbing','18 vehicles','Priya Shah','priya@northstar.co','$6,280','Active'],['Metro Foods','31 vehicles','Luis Moreno','fleet@metrofoods.com','$12,940','Review'],['Brightline HVAC','12 vehicles','Sam Carter','sam@brightline.com','$4,870','Active'],['Citywide Electrical','24 vehicles','Avery Chen','ops@citywide.com','$9,115','Past due']];const rows=useMemo(()=>data.filter(r=>r.join(' ').toLowerCase().includes(search.toLowerCase())),[search]);return <><Header title="Customers" eyebrow="Fleet accounts" description="A complete view of fleet contacts, vehicles, service activity, and billing." icon={Building2} primary="New customer"/><Stats items={[[ 'Active accounts','126','+8 this quarter',Building2],['Vehicles managed','1,842','Across 19 locations',Car,'violet'],['30-day account value','$248k','6.2% growth',TrendingUp,'green']]}/><div className="mt-6"><Shell title="Fleet accounts" description="Customer health and recent service revenue" action={<label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers…" className="h-9 rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none"/></label>}><Table headers={['Account','Fleet size','Primary contact','Email','30-day spend','Standing']} rows={rows.map(r=>[<b>{r[0]}</b>,r[1],<b>{r[2]}</b>,r[3],<b>{r[4]}</b>,<Badge tone={r[5]==='Active'?'green':r[5]==='Past due'?'red':'amber'}>{r[5]}</Badge>])}/></Shell></div></>};

const Financials=()=>{const[tab,setTab]=useState('Invoices');const rows=[['INV-10984','Acme Logistics','WO-2044','$2,460.00','Sep 14','Sent'],['INV-10983','Metro Foods','WO-2041','$4,885.50','Sep 9','Viewed'],['INV-10982','Northstar Plumbing','WO-2039','$1,240.00','Aug 29','Overdue'],['INV-10981','Brightline HVAC','WO-2037','$735.00','—','Paid'],['INV-10980','Citywide Electrical','WO-2032','$3,190.00','—','Paid']];return <><Header title="Invoices & Financials" eyebrow="Billing & revenue" description="Move approved work into accurate invoices and keep cash flow visible." icon={BadgeDollarSign} primary="Create invoice"/><Stats items={[[ 'Open receivables','$86,420','Across 38 invoices',CircleDollarSign],['Overdue','$12,680','8 invoices',Clock3,'red'],['Collected this month','$214k','+9.8% month over month',TrendingUp,'green'],['Avg. days to pay','18.4','2.1 days faster',CheckCircle2,'violet']]}/><div className="mt-6"><Shell title="Billing activity" description="Invoices, estimates, purchase orders, and payment status" action={<div className="flex rounded-xl bg-slate-100 p-1">{['Invoices','Estimates','Payments'].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${tab===x?'bg-white shadow-sm':'text-slate-500'}`}>{x}</button>)}</div>}><Table headers={['Invoice','Customer','Work order','Amount','Due','Status']} rows={rows.map(r=>[<b className="text-blue-600">{r[0]}</b>,<b>{r[1]}</b>,r[2],<b>{r[3]}</b>,r[4],<Badge tone={r[5]==='Paid'?'green':r[5]==='Overdue'?'red':r[5]==='Viewed'?'blue':'slate'}>{r[5]}</Badge>])}/></Shell></div></>};

const Documents=()=>{const[view,setView]=useState('All');const docs=[['DOT inspection — Unit 301','Inspection','PDF · 2.8 MB','Metro Foods','Aug 30'],['Brake authorization — WO-2048','Authorization','PDF · 184 KB','Acme Logistics','Aug 30'],['Damage photos — Unit 088','Photos','8 files · 14 MB','Northstar Plumbing','Aug 29'],['Parts receipt — WO-2046','Receipt','PDF · 340 KB','Metro Foods','Aug 28'],['Service history — Unit 214','Service record','PDF · 1.2 MB','Acme Logistics','Aug 27'],['Signed estimate — WO-2041','Estimate','PDF · 220 KB','Metro Foods','Aug 26']];return <><Header title="Documents" eyebrow="Fleet records" description="Keep inspections, authorizations, photos, receipts, and service records connected." icon={Files} primary="Upload documents"/><div className="mt-7 flex justify-between"><div className="flex gap-2 overflow-auto">{['All','Inspections','Authorizations','Photos','Receipts'].map(x=><button key={x} onClick={()=>setView(x)} className={`rounded-xl px-3.5 py-2 text-xs font-bold ${view===x?'bg-slate-900 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{x}</button>)}</div><button className="flex items-center gap-2 text-xs font-bold"><Download className="h-4 w-4"/>Export</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{docs.map((d,i)=><article key={d[0]} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex justify-between"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600">{i%2?<FileText className="h-5 w-5"/>:<FileCheck2 className="h-5 w-5"/>}</span><MoreHorizontal className="h-5 w-5 text-slate-400"/></div><h3 className="mt-5 text-sm font-bold">{d[0]}</h3><p className="mt-1 text-xs text-slate-500">{d[2]}</p><div className="mt-5 flex justify-between border-t border-slate-100 pt-4"><div><p className="text-[10px] font-bold uppercase text-slate-400">{d[1]}</p><p className="mt-1 text-xs font-semibold">{d[3]}</p></div><span className="text-xs text-slate-400">{d[4]}</span></div></article>)}</div></>};

const Vehicles=({onOpenInbox}:{onOpenInbox:()=>void})=><><Header title="Vehicles" eyebrow="Fleet registry" description="Track every fleet asset, VIN, assignment, mileage, and service history." icon={Car} primary="Add vehicle"/><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-10 text-center shadow-sm"><Car className="mx-auto h-8 w-8 text-blue-600"/><h3 className="mt-4 font-bold">Fleet vehicle registry</h3><p className="mt-2 text-sm text-slate-500">Vehicle management is ready for VIN decoding and bulk import.</p><button onClick={onOpenInbox} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-600"><Inbox className="h-4 w-4"/>Open Fleet Inbox<ArrowRight className="h-4 w-4"/></button></section></>;

export const FleetModuleView:React.FC<FleetModuleViewProps>=({module,onOpenInbox})=>{const screens:Record<FleetModuleId,React.ReactNode>={vehicles:<Vehicles onOpenInbox={onOpenInbox}/>,'work-orders':<WorkOrders/>,maintenance:<Maintenance/>,schedule:<Schedule/>,dispatch:<Dispatch/>,parts:<Parts/>,customers:<Customers/>,financials:<Financials/>,documents:<Documents/>};return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1440px]">{screens[module]}<div className="mt-6 flex items-center justify-between rounded-2xl border border-slate-200 bg-white px-5 py-4 shadow-sm"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Fleet service lifecycle</p><p className="mt-1 text-xs font-semibold text-slate-700">Request → Schedule → Dispatch → Inspection → Authorization → Service → Invoice</p></div><Sparkles className="h-5 w-5 text-blue-500"/></div></div></main>};
