import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, Loader2, MapPin, Plus, RefreshCw, Truck, UserRound } from 'lucide-react';
import { getActiveNeonAuthSession } from '../lib/neonAuthClient';

type Mode = 'schedule' | 'dispatch';
type RecordRow = Record<string, any>;
interface Props { mode: Mode; organizationId?: string; }

const statusLabels: Record<string,string> = { assigned:'Ready', accepted:'Ready', en_route:'En route', arrived:'On site', working:'On site', completed:'Completed', cancelled:'Cancelled' };
const columns = ['Ready','En route','On site','Completed'];

async function api<T>(path: string, organizationId?: string, init: RequestInit = {}): Promise<T> {
  const token = getActiveNeonAuthSession().token;
  if (!token) throw new Error('Your session expired. Sign in again to continue.');
  const response = await fetch(`/api/fleet-operations${path}`, { ...init, headers: { 'Content-Type':'application/json', ...(organizationId ? { 'x-organization-id':organizationId } : {}), Authorization:`Bearer ${token}`, ...init.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`);
  return body;
}

const formatTime = (value?: string) => value ? new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(value)) : 'Unscheduled';
const formatDay = (date: Date) => new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(date);
const localInput = (date = new Date()) => new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);

export const ScheduleDispatchView: React.FC<Props> = ({ mode, organizationId }) => {
  const [rows,setRows]=useState<RecordRow[]>([]); const [refs,setRefs]=useState<Record<string,RecordRow[]>>({});
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showCreate,setShowCreate]=useState(false);
  const reload=useCallback(async()=>{ setLoading(true);setError('');try{const [records,references]=await Promise.all([api<RecordRow[]>(mode==='schedule'?'/appointments':'/dispatch',organizationId),api<Record<string,RecordRow[]>>('/references',organizationId)]);setRows(records);setRefs(references);}catch(e){setError(e instanceof Error?e.message:'Unable to load fleet operations');}finally{setLoading(false);}},[mode,organizationId]);
  useEffect(()=>{void reload();},[reload]);
  const lookup=useCallback((table:string,id?:string)=>refs[table]?.find(x=>x.id===id),[refs]);
  const week=useMemo(()=>{const today=new Date();const monday=new Date(today);monday.setHours(0,0,0,0);monday.setDate(today.getDate()-((today.getDay()+6)%7));return Array.from({length:5},(_,i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);return date;});},[]);
  const updateStatus=async(id:string,status:string)=>{try{await api(`/dispatch/${id}`,organizationId,{method:'PATCH',body:JSON.stringify({status})});await reload();}catch(e){setError(e instanceof Error?e.message:'Update failed');}};
  const title=mode==='schedule'?'Schedule':'Dispatch';
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="flex gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white">{mode==='schedule'?<CalendarClock/>:<Truck/>}</span><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">{mode==='schedule'?'Service calendar':'Field operations'}</p><h2 className="mt-1 text-3xl font-bold text-slate-950">{title}</h2><p className="mt-2 text-sm text-slate-600">{mode==='schedule'?'Live appointments from the fleet database.':'Assign technicians and update live field status.'}</p></div></div><div className="flex gap-2"><button onClick={()=>void reload()} className="grid h-10 w-10 place-items-center rounded-xl border bg-white"><RefreshCw className="h-4 w-4"/></button><button onClick={()=>setShowCreate(true)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>{mode==='schedule'?'Book appointment':'Create dispatch'}</button></div></div>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading?<div className="grid min-h-[360px] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-blue-600"/></div>:mode==='schedule'?<div className="mt-7 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid min-w-[800px] grid-cols-5 divide-x divide-slate-100">{week.map(day=>{const jobs=rows.filter(x=>new Date(x.starts_at).toDateString()===day.toDateString());return <section key={day.toISOString()} className="min-h-[430px] p-3"><div className="mb-4 flex justify-between"><b className="text-xs uppercase text-slate-500">{formatDay(day)}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{jobs.length}</span></div>{jobs.map(job=>{const customer=lookup('customers',job.customer_id),vehicle=lookup('vehicles',job.vehicle_id),work=lookup('work_orders',job.work_order_id);return <article key={job.id} className="mb-3 rounded-xl border-l-4 border-blue-500 bg-blue-50 p-3"><p className="text-[10px] font-bold text-slate-500">{formatTime(job.starts_at)} – {formatTime(job.ends_at)}</p><p className="mt-2 text-xs font-bold">{customer?.name||'Fleet appointment'}</p><p className="mt-1 text-[11px] text-slate-600">{vehicle?.unit_number?`Unit ${vehicle.unit_number}`:'No vehicle'}{work?.number?` · ${work.number}`:''}</p><span className="mt-2 inline-block rounded-full bg-white px-2 py-1 text-[10px] font-bold capitalize">{job.status?.replace('_',' ')}</span></article>})}</section>})}</div></div>:<div className="mt-6 grid gap-4 xl:grid-cols-4">{columns.map(column=>{const jobs=rows.filter(x=>statusLabels[x.status]===column);return <section key={column} className="rounded-2xl bg-slate-100/80 p-3"><div className="mb-3 flex justify-between px-1"><h3 className="text-sm font-bold">{column}</h3><span className="rounded-full bg-white px-2 py-1 text-xs font-bold">{jobs.length}</span></div>{jobs.map(job=>{const work=lookup('work_orders',job.work_order_id),tech=lookup('technicians',job.technician_id),appointment=lookup('appointments',job.appointment_id);return <article key={job.id} className="mb-3 rounded-xl border bg-white p-4 shadow-sm"><b className="text-xs text-blue-600">{work?.number||'Work order'}</b><p className="mt-3 text-sm font-bold">{tech?.name||'Unassigned'}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin className="h-3 w-3"/>{appointment?formatTime(appointment.starts_at):formatTime(job.starts_at)}</p><select value={job.status} onChange={e=>void updateStatus(job.id,e.target.value)} className="mt-4 h-9 w-full rounded-lg border bg-white px-2 text-xs font-semibold">{['assigned','accepted','en_route','arrived','working','completed','cancelled'].map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></article>})}</section>})}</div>}
    {showCreate&&<CreateDialog {...{mode,organizationId,refs,onClose:()=>setShowCreate(false),onCreated:reload}}/>}
  </div></main>;
};

const CreateDialog:React.FC<{mode:Mode;organizationId?:string;refs:Record<string,RecordRow[]>;onClose:()=>void;onCreated:()=>Promise<void>}>=({mode,organizationId,refs,onClose,onCreated})=>{
  const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [form,setForm]=useState<RecordRow>({startsAt:localInput(),endsAt:localInput(new Date(Date.now()+3600000))});
  const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setMessage('');try{await api(mode==='schedule'?'/appointments':'/dispatch',organizationId,{method:'POST',body:JSON.stringify(form)});await onCreated();onClose();}catch(err){setMessage(err instanceof Error?err.message:'Unable to save');}finally{setSaving(false);}};
  const select=(label:string,key:string,items:RecordRow[],render:(x:RecordRow)=>string,required=false)=><label className="text-xs font-bold text-slate-600">{label}<select required={required} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 h-10 w-full rounded-xl border px-3 font-normal"><option value="">Select…</option>{(items||[]).filter(Boolean).map(x=><option key={x.id} value={x.id}>{render(x)}</option>)}</select></label>;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2 text-blue-600">{mode==='schedule'?<CalendarClock/>:<UserRound/>}</span><h3 className="text-lg font-bold">{mode==='schedule'?'Book appointment':'Create dispatch'}</h3></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{mode==='schedule'?<>{select('Customer','customerId',refs.customers,x=>x.name,true)}{select('Vehicle','vehicleId',refs.vehicles,x=>`Unit ${x.unit_number}`,true)}{select('Work order','workOrderId',refs.work_orders,x=>x.number)}<label className="text-xs font-bold text-slate-600">Starts<input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} className="mt-1 h-10 w-full rounded-xl border px-3 font-normal"/></label><label className="text-xs font-bold text-slate-600">Ends<input required type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})} className="mt-1 h-10 w-full rounded-xl border px-3 font-normal"/></label></>:<>{select('Work order','workOrderId',refs.work_orders,x=>x.number,true)}{select('Technician','technicianId',refs.technicians,x=>x.name,true)}{select('Appointment','appointmentId',refs.appointments||[],x=>formatDay(new Date(x.starts_at)))}{select('Resource','resourceId',refs.resources,x=>x.name)}</>}</div>{message&&<p className="mt-4 text-sm text-red-600">{message}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="h-10 rounded-xl border px-4 text-sm font-bold">Cancel</button><button disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white disabled:opacity-60">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}Save</button></div></form></div>;
};
