import React, { useEffect, useState } from 'react';
import { Bell, Bot, Building2, Calendar, Check, Globe2, Mail, MapPin, RefreshCw, ShieldCheck, Sparkles, UserPlus, Users, XCircle } from 'lucide-react';
import type { PersonalizationSettings } from '../types';
import { fleetFetch } from '../lib/fleetApi';

interface SettingsViewProps { settings: PersonalizationSettings; onSaveSettings: (newSettings: PersonalizationSettings) => void; onCancel?: () => void }
const DEFAULT_BUSINESS = { businessName:'',businessEmail:'',businessPhone:'',website:'',address:'',city:'',region:'',postalCode:'',timezone:'America/New_York' };
const DEFAULT_AGENT = { allowWebResearch:true,allowNhtsaVinDecode:true,allowCameraOcr:true,requireConfirmationForWrites:true };

type Member={id:string;userId:string;role:string;status:string;name?:string;email:string};
type Invitation={id:string;email:string;role:string;status:string;expiresAt:string;deliveryStatus:string};
type TeamData={role:string;permissions:string[];canManage:boolean;members:Member[];invitations:Invitation[]};

export const SettingsView: React.FC<SettingsViewProps> = ({ settings,onSaveSettings,onCancel }) => {
  const [draft,setDraft]=useState<PersonalizationSettings>({...settings,businessProfile:settings.businessProfile||DEFAULT_BUSINESS,agentPreferences:settings.agentPreferences||DEFAULT_AGENT});
  const [saved,setSaved]=useState(false);
  const [google,setGoogle]=useState<{configured:boolean;connected:boolean;account?:{email:string;name?:string}}|null>(null);
  const [googleBusy,setGoogleBusy]=useState(false);
  useEffect(()=>setDraft({...settings,businessProfile:settings.businessProfile||DEFAULT_BUSINESS,agentPreferences:settings.agentPreferences||DEFAULT_AGENT}),[settings]);
  const loadGoogle=async()=>{try{const r=await fetch('/api/google/status');setGoogle(await r.json());}catch{setGoogle({configured:false,connected:false});}};
  useEffect(()=>{void loadGoogle();},[]);
  const setBusiness=(key:string,value:string)=>setDraft(c=>({...c,businessProfile:{...(c.businessProfile||DEFAULT_BUSINESS),[key]:value}}));
  const setAgent=(key:string,value:boolean)=>setDraft(c=>({...c,agentPreferences:{...(c.agentPreferences||DEFAULT_AGENT),[key]:value}}));
  const save=()=>{onSaveSettings(draft);try{localStorage.setItem('fleetos:user-settings',JSON.stringify(draft));}catch{}setSaved(true);setTimeout(()=>setSaved(false),2200);};
  const disconnectGoogle=async()=>{setGoogleBusy(true);try{await fetch('/api/google/disconnect',{method:'POST'});await loadGoogle();}finally{setGoogleBusy(false);}};

  return <div className="flex-1 overflow-y-auto bg-slate-50/60"><div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
    <div><h1 className="text-2xl font-bold text-slate-900">Settings</h1><p className="mt-1 text-sm text-slate-500">Business profile, team access, Fleet Agent controls, connected services, and notifications.</p></div>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-2.5 text-blue-700"><Building2 className="h-5 w-5"/></div><div><h2 className="font-bold text-slate-900">Business profile</h2><p className="text-xs text-slate-500">Used across Fleet OS communications and agent context.</p></div></div><div className="grid gap-4 md:grid-cols-2">{[['businessName','Business name','MOMS Mobile Oil Change'],['businessEmail','Business email','service@example.com'],['businessPhone','Business phone','(555) 555-0100'],['website','Website','https://example.com'],['address','Street address','123 Main St'],['city','City','Ambler'],['region','State / region','PA'],['postalCode','ZIP / postal code','19002']].map(([key,label,placeholder])=><label key={key} className="space-y-1.5 text-sm font-medium text-slate-700"><span>{label}</span><input value={(draft.businessProfile as any)?.[key]||''} onChange={e=>setBusiness(key,e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label>)}<label className="space-y-1.5 text-sm font-medium text-slate-700 md:col-span-2"><span>Timezone</span><select value={draft.businessProfile?.timezone||'America/New_York'} onChange={e=>setBusiness('timezone',e.target.value)} className="w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm"><option value="America/New_York">Eastern Time</option><option value="America/Chicago">Central Time</option><option value="America/Denver">Mountain Time</option><option value="America/Los_Angeles">Pacific Time</option></select></label></div></section>

    <TeamSettings />

    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-violet-50 p-2.5 text-violet-700"><Bot className="h-5 w-5"/></div><div><h2 className="font-bold text-slate-900">Fleet Agent</h2><p className="text-xs text-slate-500">The agent inherits the signed-in user's Fleet OS permissions. Consequential writes remain confirmation-gated.</p></div></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center gap-2"><Sparkles className="h-4 w-4 text-blue-600"/><span className="text-sm font-semibold">Response style</span></div><div className="grid grid-cols-3 gap-2">{(['Professional','Friendly','Concise'] as const).map(tone=><button key={tone} type="button" onClick={()=>setDraft(c=>({...c,personalityFocus:tone}))} className={`rounded-lg px-3 py-2 text-xs font-semibold ${draft.personalityFocus===tone?'bg-blue-600 text-white':'bg-slate-100 text-slate-700'}`}>{tone}</button>)}</div></div><Toggle label="Web research" detail="Allow Browserbase research for public company and prospect information." checked={draft.agentPreferences?.allowWebResearch??true} onChange={v=>setAgent('allowWebResearch',v)} icon={<Globe2 className="h-4 w-4"/>}/><Toggle label="NHTSA VIN decoding" detail="Allow the agent to decode VINs with NHTSA vPIC vehicle data." checked={draft.agentPreferences?.allowNhtsaVinDecode??true} onChange={v=>setAgent('allowNhtsaVinDecode',v)} icon={<ShieldCheck className="h-4 w-4"/>}/><Toggle label="Camera & OCR" detail="Allow camera scans and image extraction for cards, documents, and vehicles." checked={draft.agentPreferences?.allowCameraOcr??true} onChange={v=>setAgent('allowCameraOcr',v)} icon={<MapPin className="h-4 w-4"/>}/><Toggle label="Require confirmation for writes" detail="Email sends, scheduling, account changes, and other mutations require review unless a future approved automation policy allows them." checked={draft.agentPreferences?.requireConfirmationForWrites??true} onChange={v=>setAgent('requireConfirmationForWrites',v)} icon={<ShieldCheck className="h-4 w-4"/>}/></div></section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="mb-4 flex items-center gap-3"><Mail className="h-5 w-5 text-blue-600"/><div><h2 className="font-bold text-slate-900">Connected services</h2><p className="text-xs text-slate-500">Email and calendar connections used by Fleet OS.</p></div></div><div className="divide-y divide-slate-100"><div className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-semibold">AgentMail</p><p className="text-xs text-slate-500">{settings.connectedAccounts.find(a=>a.type==='agentmail')?.email||'Organization inbox'}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">Connected</span></div><div className="flex items-center justify-between gap-4 py-3"><div className="flex items-center gap-3"><Calendar className="h-4 w-4 text-slate-500"/><div><p className="text-sm font-semibold">Google Workspace</p><p className="text-xs text-slate-500">{google?.connected?`${google.account?.email||'Google'} · Gmail + Calendar`:'Connect Gmail and Google Calendar'}</p></div></div>{google?.connected?<button disabled={googleBusy} onClick={()=>void disconnectGoogle()} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Disconnect</button>:<a href="/api/google/oauth/start" className={`rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white ${!google?.configured?'pointer-events-none opacity-50':''}`}>Connect</a>}</div></div></section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><Bell className="h-5 w-5 text-blue-600"/><h2 className="font-bold text-slate-900">Notifications</h2></div><div className="grid gap-4 md:grid-cols-2"><Toggle label="Important emails only" detail="Reduce non-essential Fleet Inbox notifications." checked={draft.importantEmailsOnly} onChange={v=>setDraft(c=>({...c,importantEmailsOnly:v}))}/><Toggle label="Daily AI digest" detail="Receive a morning Fleet OS summary." checked={draft.dailyAIDigest} onChange={v=>setDraft(c=>({...c,dailyAIDigest:v}))}/></div></section>

    <div className="flex justify-end gap-3 pb-8"><button onClick={onCancel} className="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700">Cancel</button><button onClick={save} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Save changes</button></div>
  </div>{saved&&<div className="fixed bottom-6 right-6 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-xs font-semibold text-white shadow-xl"><Check className="h-4 w-4 text-emerald-400"/>Settings saved</div>}</div>;
};

function TeamSettings(){
  const [data,setData]=useState<TeamData|null>(null);const [email,setEmail]=useState('');const [role,setRole]=useState('technician');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const load=async()=>{try{const r=await fleetFetch('/api/team');if(r.ok)setData(await r.json());}catch{}};
  useEffect(()=>{void load();},[]);
  const invite=async()=>{if(!email.trim())return;setBusy(true);setMessage('');try{const r=await fleetFetch('/api/team/invitations',{method:'POST',body:JSON.stringify({email,role})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Invite failed');setEmail('');setMessage(body.sent?'Invitation sent.':'Invitation created; email delivery failed. Use Resend.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Invite failed');}finally{setBusy(false);}};
  const resend=async(id:string)=>{setBusy(true);try{await fleetFetch(`/api/team/invitations/${id}/resend`,{method:'POST'});await load();}finally{setBusy(false);}};
  const revoke=async(id:string)=>{setBusy(true);try{await fleetFetch(`/api/team/invitations/${id}`,{method:'DELETE'});await load();}finally{setBusy(false);}};
  const updateMember=async(id:string,nextRole:string)=>{setBusy(true);try{await fleetFetch(`/api/team/members/${id}`,{method:'PATCH',body:JSON.stringify({role:nextRole})});await load();}finally{setBusy(false);}};
  if(!data)return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="flex items-center gap-3"><Users className="h-5 w-5 text-blue-600"/><div><h2 className="font-bold">Team & access</h2><p className="text-xs text-slate-500">Loading workspace access…</p></div></div></section>;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-xl bg-teal-50 p-2.5 text-teal-700"><Users className="h-5 w-5"/></div><div><h2 className="font-bold text-slate-900">Team & access</h2><p className="text-xs text-slate-500">Neon Auth verifies identity; Fleet OS controls workspace roles and permissions.</p></div></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold capitalize text-slate-600">You: {data.role}</span></div>
    {data.canManage&&<div className="mb-5 grid gap-3 rounded-xl border border-blue-100 bg-blue-50/50 p-4 md:grid-cols-[1fr_180px_auto]"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="technician@company.com" className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"/><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="admin">Admin</option><option value="dispatcher">Dispatcher</option><option value="technician">Technician</option><option value="viewer">Viewer</option></select><button disabled={busy} onClick={()=>void invite()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><UserPlus className="h-4 w-4"/>Invite</button>{message&&<p className="text-xs text-slate-600 md:col-span-3">{message}</p>}</div>}
    <div className="space-y-2">{data.members.map(member=><div key={member.id} className="flex flex-col gap-3 rounded-xl border border-slate-100 p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{member.name||member.email}</p><p className="truncate text-xs text-slate-500">{member.email}</p></div>{data.canManage&&member.role!=='owner'?<select disabled={busy} value={member.role} onChange={e=>void updateMember(member.id,e.target.value)} className="rounded-lg border border-slate-200 px-2.5 py-2 text-xs font-semibold capitalize"><option value="admin">Admin</option><option value="dispatcher">Dispatcher</option><option value="technician">Technician</option><option value="viewer">Viewer</option></select>:<span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold capitalize text-slate-600">{member.role}</span>}</div>)}</div>
    {data.invitations.length>0&&<div className="mt-5"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-400">Pending invitations</p><div className="space-y-2">{data.invitations.map(inv=><div key={inv.id} className="flex flex-col gap-2 rounded-xl border border-dashed border-slate-200 p-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-sm font-semibold">{inv.email}</p><p className="text-xs text-slate-500 capitalize">{inv.role} · {inv.deliveryStatus}</p></div>{data.canManage&&<div className="flex gap-2"><button disabled={busy} onClick={()=>void resend(inv.id)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold"><RefreshCw className="h-3.5 w-3.5"/>Resend</button><button disabled={busy} onClick={()=>void revoke(inv.id)} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-700"><XCircle className="h-3.5 w-3.5"/>Revoke</button></div>}</div>)}</div></div>}
  </section>;
}

function Toggle({label,detail,checked,onChange,icon}:{label:string;detail:string;checked:boolean;onChange:(value:boolean)=>void;icon?:React.ReactNode}){return <div className="flex items-start justify-between gap-4 rounded-xl border border-slate-200 p-4"><div className="flex gap-2.5">{icon&&<span className="mt-0.5 text-slate-500">{icon}</span>}<div><p className="text-sm font-semibold text-slate-900">{label}</p><p className="mt-1 text-xs leading-relaxed text-slate-500">{detail}</p></div></div><button type="button" aria-pressed={checked} onClick={()=>onChange(!checked)} className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition ${checked?'bg-blue-600':'bg-slate-200'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${checked?'left-6':'left-1'}`}/></button></div>}
