import { Pool } from '@neondatabase/serverless';
import { randomUUID } from 'node:crypto';

export type FleetAccountMutationInput = {
  name: string;
  accountNumber?: string | null;
  primaryContactName?: string | null;
  primaryContactEmail?: string | null;
  phone?: string | null;
  notes?: string | null;
};
export type FleetContactMutationInput = { customerId: string; name: string; email?: string | null; phone?: string | null; role?: string | null; notes?: string | null; isPrimary?: boolean };
export type FleetVehicleMutationInput = { customerId: string; unitNumber: string; vin?: string | null; year?: number | null; make?: string | null; model?: string | null; engine?: string | null; mileage?: number | null; engineHours?: number | null; licensePlate?: string | null; registrationState?: string | null; assignedDriver?: string | null; department?: string | null; notes?: string | null };
export type FleetCustomerOnboardInput = { customerId?: string | null; account: FleetAccountMutationInput; contact?: Omit<FleetContactMutationInput, 'customerId'> | null; vehicles?: Array<Omit<FleetVehicleMutationInput, 'customerId'>> };

function databaseUrl() { const value=process.env.DATABASE_URL||process.env.NEON_DATABASE_URL; if(!value)throw new Error('Database is not configured'); return value; }
const text=(value:unknown,name:string,max=300)=>{const result=String(value??'').trim();if(!result)throw new Error(`${name} is required`);return result.slice(0,max)};
const optional=(value:unknown,max=2000)=>{const result=String(value??'').trim();return result?result.slice(0,max):null};
const optionalInteger=(value:unknown,name:string)=>{if(value===undefined||value===null||value==='')return null;const result=Number(value);if(!Number.isInteger(result)||result<0)throw new Error(`${name} must be a non-negative whole number`);return result};

async function withTransaction<T>(work:(client:any)=>Promise<T>){const pool=new Pool({connectionString:databaseUrl()});const client=await pool.connect();try{await client.query('BEGIN');const result=await work(client);await client.query('COMMIT');return result}catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release();await pool.end()}}
async function assertCustomer(client:any,organizationId:string,customerId:string){const result=await client.query('SELECT * FROM customers WHERE organization_id=$1 AND id=$2 LIMIT 1',[organizationId,customerId]);if(!result.rows[0])throw new Error('Fleet account not found');return result.rows[0]}
async function resolveOrCreateAccount(client:any,organizationId:string,raw:FleetAccountMutationInput,requestedCustomerId?:string|null){if(requestedCustomerId)return{customer:await assertCustomer(client,organizationId,requestedCustomerId),created:false};const name=text(raw.name,'Fleet account name');const email=optional(raw.primaryContactEmail,320);const existing=await client.query(`SELECT * FROM customers WHERE organization_id=$1 AND (lower(name)=lower($2) OR ($3::text IS NOT NULL AND lower(primary_contact_email)=lower($3))) ORDER BY updated_at DESC LIMIT 1`,[organizationId,name,email]);if(existing.rows[0])return{customer:existing.rows[0],created:false};const result=await client.query(`INSERT INTO customers(id,organization_id,name,account_number,primary_contact_name,primary_contact_email,billing_email,phone,status,notes) VALUES($1,$2,$3,$4,$5,$6,$6,$7,'active',$8) RETURNING *`,[randomUUID(),organizationId,name,optional(raw.accountNumber,80),optional(raw.primaryContactName,200),email,optional(raw.phone,50),optional(raw.notes)]);return{customer:result.rows[0],created:true}}
async function upsertContact(client:any,organizationId:string,customerId:string,raw:Omit<FleetContactMutationInput,'customerId'>){await assertCustomer(client,organizationId,customerId);const name=text(raw.name,'Contact name');const email=optional(raw.email,320);const existing=email?await client.query('SELECT * FROM contacts WHERE organization_id=$1 AND customer_id=$2 AND lower(email)=lower($3) LIMIT 1',[organizationId,customerId,email]):{rows:[]};if(existing.rows[0]){const result=await client.query(`UPDATE contacts SET name=$4,phone=COALESCE($5,phone),role=COALESCE($6,role),notes=COALESCE($7,notes),is_primary=$8,updated_at=now() WHERE organization_id=$1 AND customer_id=$2 AND id=$3 RETURNING *`,[organizationId,customerId,existing.rows[0].id,name,optional(raw.phone,50),optional(raw.role,120),optional(raw.notes),raw.isPrimary!==false]);return{contact:result.rows[0],created:false}}const result=await client.query(`INSERT INTO contacts(id,organization_id,customer_id,name,email,phone,role,is_primary,tags,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::text[],$10) RETURNING *`,[randomUUID(),organizationId,customerId,name,email,optional(raw.phone,50),optional(raw.role,120),raw.isPrimary!==false,[],optional(raw.notes)]);return{contact:result.rows[0],created:true}}
async function upsertVehicle(client:any,organizationId:string,customerId:string,raw:Omit<FleetVehicleMutationInput,'customerId'>){await assertCustomer(client,organizationId,customerId);const unitNumber=text(raw.unitNumber,'Vehicle unit number',100);const vin=optional(raw.vin,17)?.toUpperCase()||null;if(vin&&!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin))throw new Error('VIN must be 17 characters and cannot contain I, O, or Q');const year=optionalInteger(raw.year,'Vehicle year');const mileage=optionalInteger(raw.mileage,'Mileage');const engineHours=optionalInteger(raw.engineHours,'Engine hours');const existing=await client.query(`SELECT * FROM vehicles WHERE organization_id=$1 AND (unit_number=$2 OR ($3::text IS NOT NULL AND vin=$3)) ORDER BY updated_at DESC LIMIT 1`,[organizationId,unitNumber,vin]);if(existing.rows[0]){if(existing.rows[0].customer_id&&String(existing.rows[0].customer_id)!==customerId)throw new Error(`Vehicle ${unitNumber} already belongs to another Fleet account`);const result=await client.query(`UPDATE vehicles SET customer_id=$3,vin=COALESCE($4,vin),year=COALESCE($5,year),make=COALESCE($6,make),model=COALESCE($7,model),engine=COALESCE($8,engine),mileage=COALESCE($9,mileage),engine_hours=COALESCE($10,engine_hours),license_plate=COALESCE($11,license_plate),registration_state=COALESCE($12,registration_state),assigned_driver=COALESCE($13,assigned_driver),department=COALESCE($14,department),notes=COALESCE($15,notes),updated_at=now() WHERE organization_id=$1 AND id=$2 RETURNING *`,[organizationId,existing.rows[0].id,customerId,vin,year,optional(raw.make,100),optional(raw.model,100),optional(raw.engine,160),mileage,engineHours,optional(raw.licensePlate,50),optional(raw.registrationState,30),optional(raw.assignedDriver,160),optional(raw.department,120),optional(raw.notes)]);return{vehicle:result.rows[0],created:false}}const result=await client.query(`INSERT INTO vehicles(id,organization_id,customer_id,unit_number,vin,year,make,model,engine,mileage,engine_hours,status,license_plate,registration_state,assigned_driver,department,notes,metadata,specifications) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'active',$12,$13,$14,$15,$16,'{}'::jsonb,'{}'::jsonb) RETURNING *`,[randomUUID(),organizationId,customerId,unitNumber,vin,year,optional(raw.make,100),optional(raw.model,100),optional(raw.engine,160),mileage??0,engineHours,optional(raw.licensePlate,50),optional(raw.registrationState,30),optional(raw.assignedDriver,160),optional(raw.department,120),optional(raw.notes)]);return{vehicle:result.rows[0],created:true}}

export const fleetCustomerMutations={
  createAccount(organizationId:string,input:FleetAccountMutationInput){return withTransaction(client=>resolveOrCreateAccount(client,organizationId,input))},
  createContact(organizationId:string,input:FleetContactMutationInput){return withTransaction(client=>upsertContact(client,organizationId,text(input.customerId,'Fleet account',100),input))},
  createVehicle(organizationId:string,input:FleetVehicleMutationInput){return withTransaction(client=>upsertVehicle(client,organizationId,text(input.customerId,'Fleet account',100),input))},
  onboard(organizationId:string,input:FleetCustomerOnboardInput){return withTransaction(async client=>{const account=await resolveOrCreateAccount(client,organizationId,input.account,optional(input.customerId,100));const customerId=String(account.customer.id);const contact=input.contact?await upsertContact(client,organizationId,customerId,input.contact):null;const vehicles=[];for(const vehicle of input.vehicles||[])vehicles.push(await upsertVehicle(client,organizationId,customerId,vehicle));return{customer:account.customer,customerCreated:account.created,contact:contact?.contact||null,contactCreated:Boolean(contact?.created),vehicles:vehicles.map(item=>item.vehicle),vehiclesCreated:vehicles.filter(item=>item.created).length,vehiclesLinked:vehicles.filter(item=>!item.created).length}})},
};
