import { Pool } from '@neondatabase/serverless';
import { randomUUID } from 'node:crypto';

export class FleetServiceModelError extends Error { constructor(message:string, readonly status=400){super(message);} }
type Input=Record<string,unknown>;type Row=Record<string,any>;
const dbUrl=()=>{const value=process.env.DATABASE_URL||process.env.NEON_DATABASE_URL;if(!value)throw new FleetServiceModelError('Database is not configured',503);return value};
const required=(v:unknown,name:string,max=300)=>{const s=String(v??'').trim();if(!s)throw new FleetServiceModelError(`${name} is required`,400);return s.slice(0,max)};
const optional=(v:unknown,max=2000)=>{const s=String(v??'').trim();return s?s.slice(0,max):null};
const numberValue=(v:unknown,fallback=0)=>{const n=v==null||v===''?fallback:Number(v);if(!Number.isFinite(n)||n<0)throw new FleetServiceModelError('Numeric values must be zero or greater',400);return n};
const integerValue=(v:unknown,fallback=0)=>{const n=numberValue(v,fallback);if(!Number.isInteger(n))throw new FleetServiceModelError('Whole-number value required',400);return n};
const bool=(v:unknown, fallback=false)=>v==null?fallback:v===true||v==='true'||v==='on'||v==='1';
async function withPool<T>(work:(pool:Pool)=>Promise<T>){const pool=new Pool({connectionString:dbUrl()});try{return await work(pool)}finally{await pool.end()}}
async function withTx<T>(work:(client:any)=>Promise<T>){const pool=new Pool({connectionString:dbUrl()});const client=await pool.connect();try{await client.query('BEGIN');const value=await work(client);await client.query('COMMIT');return value}catch(e){try{await client.query('ROLLBACK')}catch{}throw e}finally{client.release();await pool.end()}}
async function one(client:any,sql:string,args:unknown[],message:string){const result=await client.query(sql,args);if(!result.rows[0])throw new FleetServiceModelError(message,404);return result.rows[0] as Row}

export async function fleetServiceBootstrap(organizationId:string){return withPool(async pool=>{const queries=[
 pool.query(`SELECT id,name,account_number,primary_contact_name,primary_contact_email,billing_email,phone,po_required,default_po_number,payment_terms,status FROM customers WHERE organization_id=$1 ORDER BY name`,[organizationId]),
 pool.query(`SELECT v.*,c.name AS customer_name FROM vehicles v JOIN customers c ON c.id=v.customer_id AND c.organization_id=v.organization_id WHERE v.organization_id=$1 ORDER BY c.name,v.unit_number`,[organizationId]),
 pool.query(`SELECT * FROM service_catalog WHERE organization_id=$1 AND active=true ORDER BY category,name`,[organizationId]),
 pool.query(`SELECT a.*,c.name AS customer_name FROM fleet_service_agreements a JOIN customers c ON c.id=a.customer_id AND c.organization_id=a.organization_id WHERE a.organization_id=$1 ORDER BY a.updated_at DESC`,[organizationId]),
 pool.query(`SELECT s.*,c.code,c.name AS service_name FROM fleet_agreement_services s JOIN service_catalog c ON c.id=s.service_id WHERE s.organization_id=$1 ORDER BY c.name`,[organizationId]),
 pool.query(`SELECT p.id,p.sku,p.name,p.description,p.unit_cost,p.unit_price,COALESCE(sum(i.quantity),0)::text AS quantity,COALESCE(sum(i.reorder_point),0)::text AS reorder_point FROM parts p LEFT JOIN inventory i ON i.part_id=p.id AND i.organization_id=p.organization_id WHERE p.organization_id=$1 GROUP BY p.id ORDER BY p.name`,[organizationId]),
 pool.query(`SELECT vp.*,p.sku,p.name AS part_name FROM vehicle_parts vp JOIN parts p ON p.id=vp.part_id WHERE vp.organization_id=$1 ORDER BY vp.updated_at DESC`,[organizationId]),
 pool.query(`SELECT vsp.*,s.code,s.name AS service_name,p.sku AS preferred_part_sku,p.name AS preferred_part_name FROM vehicle_service_profiles vsp JOIN service_catalog s ON s.id=vsp.service_id LEFT JOIN parts p ON p.id=vsp.preferred_part_id WHERE vsp.organization_id=$1 ORDER BY vsp.updated_at DESC`,[organizationId]),
 pool.query(`SELECT w.*,c.name AS customer_name,v.unit_number,v.year,v.make,v.model,a.name AS agreement_name,COALESCE((SELECT sum(sl.quantity*sl.unit_price) FROM service_lines sl WHERE sl.organization_id=w.organization_id AND sl.work_order_id=w.id),0)::text AS service_total FROM work_orders w JOIN customers c ON c.id=w.customer_id AND c.organization_id=w.organization_id JOIN vehicles v ON v.id=w.vehicle_id AND v.organization_id=w.organization_id LEFT JOIN fleet_service_agreements a ON a.id=w.service_agreement_id WHERE w.organization_id=$1 ORDER BY w.updated_at DESC`,[organizationId]),
 pool.query(`SELECT * FROM service_lines WHERE organization_id=$1 ORDER BY created_at`,[organizationId]),
 pool.query(`SELECT * FROM appointments WHERE organization_id=$1 ORDER BY starts_at DESC`,[organizationId]),
 pool.query(`SELECT d.*,t.name AS technician_name FROM dispatch_assignments d JOIN technicians t ON t.id=d.technician_id WHERE d.organization_id=$1 ORDER BY d.created_at DESC`,[organizationId]),
 pool.query(`SELECT id,name,active FROM technicians WHERE organization_id=$1 AND active=true ORDER BY name`,[organizationId])
 ];const [accounts,vehicles,catalog,agreements,agreementServices,parts,vehicleParts,vehicleServices,workOrders,serviceLines,appointments,dispatch,technicians]=await Promise.all(queries);return{accounts:accounts.rows,vehicles:vehicles.rows,catalog:catalog.rows,agreements:agreements.rows,agreementServices:agreementServices.rows,parts:parts.rows,vehicleParts:vehicleParts.rows,vehicleServices:vehicleServices.rows,workOrders:workOrders.rows,serviceLines:serviceLines.rows,appointments:appointments.rows,dispatch:dispatch.rows,technicians:technicians.rows}})}

export async function createConnectedVehicle(organizationId:string,input:Input){return withTx(async client=>{const customerId=required(input.customerId,'Fleet account');await one(client,'SELECT id FROM customers WHERE organization_id=$1 AND id=$2',[organizationId,customerId],'Fleet account not found');const unit=required(input.unitNumber,'Unit number',100);const vin=optional(input.vin,17)?.toUpperCase()||null;if(vin&&!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin))throw new FleetServiceModelError('VIN must be 17 characters and cannot contain I, O, or Q');const result=await client.query(`INSERT INTO vehicles(id,organization_id,customer_id,unit_number,vin,year,make,model,mileage,status,metadata,specifications) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'active','{}'::jsonb,'{}'::jsonb) RETURNING *`,[randomUUID(),organizationId,customerId,unit,vin,input.year?integerValue(input.year):null,optional(input.make,100),optional(input.model,100),integerValue(input.mileage,0)]);return result.rows[0]})}

export async function createCatalogService(organizationId:string,input:Input){return withPool(async pool=>{const result=await pool.query(`INSERT INTO service_catalog(id,organization_id,code,name,category,description,default_price,default_labor_minutes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[randomUUID(),organizationId,required(input.code,'Service code',80).toUpperCase(),required(input.name,'Service name'),optional(input.category,80)||'general',optional(input.description),numberValue(input.defaultPrice),integerValue(input.defaultLaborMinutes)]);return result.rows[0]})}

export async function createServiceAgreement(organizationId:string,input:Input){return withTx(async client=>{const customerId=required(input.customerId,'Fleet account');await one(client,'SELECT id FROM customers WHERE organization_id=$1 AND id=$2',[organizationId,customerId],'Fleet account not found');const result=await client.query(`INSERT INTO fleet_service_agreements(id,organization_id,customer_id,name,start_date,end_date,status,sla_hours,approval_mode,approval_threshold,approver_role,require_photo_evidence,billing_model,invoice_frequency,payment_terms,invoice_group,po_required,po_validate_remaining,enforce_location_windows,enforce_sla_window,min_dispatch_buffer_minutes,notes) VALUES($1,$2,$3,$4,$5::date,$6::date,'active',$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) RETURNING *`,[randomUUID(),organizationId,customerId,required(input.name,'Agreement name'),optional(input.startDate,30),optional(input.endDate,30),integerValue(input.slaHours,24),optional(input.approvalMode,30)||'hybrid',numberValue(input.approvalThreshold,500),optional(input.approverRole,60)||'fleet_manager',bool(input.requirePhotoEvidence),optional(input.billingModel,40)||'flat_rate',optional(input.invoiceFrequency,40)||'monthly',optional(input.paymentTerms,40)||'net_30',optional(input.invoiceGroup,100),bool(input.poRequired),bool(input.poValidateRemaining,true),bool(input.enforceLocationWindows,true),bool(input.enforceSlaWindow,true),integerValue(input.minDispatchBufferMinutes,15),optional(input.notes)]);return result.rows[0]})}

export async function setAgreementService(organizationId:string,agreementId:string,serviceId:string,input:Input){return withTx(async client=>{const agreement=await one(client,'SELECT id,customer_id FROM fleet_service_agreements WHERE organization_id=$1 AND id=$2',[organizationId,agreementId],'Service agreement not found');const service=await one(client,'SELECT id,default_price,default_labor_minutes FROM service_catalog WHERE organization_id=$1 AND id=$2',[organizationId,serviceId],'Service not found');const result=await client.query(`INSERT INTO fleet_agreement_services(id,organization_id,agreement_id,service_id,unit_price,labor_minutes,enabled,custom_label) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(agreement_id,service_id) DO UPDATE SET unit_price=EXCLUDED.unit_price,labor_minutes=EXCLUDED.labor_minutes,enabled=EXCLUDED.enabled,custom_label=EXCLUDED.custom_label,updated_at=now() RETURNING *`,[randomUUID(),organizationId,agreement.id,service.id,numberValue(input.unitPrice,Number(service.default_price||0)),integerValue(input.laborMinutes,Number(service.default_labor_minutes||0)),bool(input.enabled,true),optional(input.customLabel,200)]);return result.rows[0]})}

export async function setVehiclePart(organizationId:string,vehicleId:string,partId:string,input:Input){return withTx(async client=>{await one(client,'SELECT id FROM vehicles WHERE organization_id=$1 AND id=$2',[organizationId,vehicleId],'Vehicle not found');await one(client,'SELECT id FROM parts WHERE organization_id=$1 AND id=$2',[organizationId,partId],'Part not found');const purpose=optional(input.purpose,80)||'service';const result=await client.query(`INSERT INTO vehicle_parts(id,organization_id,vehicle_id,part_id,quantity,purpose,notes) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(vehicle_id,part_id,purpose) DO UPDATE SET quantity=EXCLUDED.quantity,notes=EXCLUDED.notes,updated_at=now() RETURNING *`,[randomUUID(),organizationId,vehicleId,partId,numberValue(input.quantity,1),purpose,optional(input.notes)]);return result.rows[0]})}

export async function setVehicleServiceProfile(organizationId:string,vehicleId:string,serviceId:string,input:Input){return withTx(async client=>{await one(client,'SELECT id FROM vehicles WHERE organization_id=$1 AND id=$2',[organizationId,vehicleId],'Vehicle not found');await one(client,'SELECT id FROM service_catalog WHERE organization_id=$1 AND id=$2',[organizationId,serviceId],'Service not found');const preferredPartId=optional(input.preferredPartId,128);if(preferredPartId)await one(client,'SELECT id FROM parts WHERE organization_id=$1 AND id=$2',[organizationId,preferredPartId],'Preferred part not found');const result=await client.query(`INSERT INTO vehicle_service_profiles(id,organization_id,vehicle_id,service_id,preferred_part_id,interval_miles,interval_engine_hours,interval_days,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(vehicle_id,service_id) DO UPDATE SET preferred_part_id=EXCLUDED.preferred_part_id,interval_miles=EXCLUDED.interval_miles,interval_engine_hours=EXCLUDED.interval_engine_hours,interval_days=EXCLUDED.interval_days,notes=EXCLUDED.notes,updated_at=now() RETURNING *`,[randomUUID(),organizationId,vehicleId,serviceId,preferredPartId,input.intervalMiles?integerValue(input.intervalMiles):null,input.intervalEngineHours?integerValue(input.intervalEngineHours):null,input.intervalDays?integerValue(input.intervalDays):null,optional(input.notes)]);return result.rows[0]})}

export async function createConnectedWorkOrder(organizationId:string,input:Input){return withTx(async client=>{const customerId=required(input.customerId,'Fleet account');const vehicleId=required(input.vehicleId,'Vehicle');const vehicle=await one(client,'SELECT id,customer_id,location_id FROM vehicles WHERE organization_id=$1 AND id=$2',[organizationId,vehicleId],'Vehicle not found');if(String(vehicle.customer_id)!==customerId)throw new FleetServiceModelError('Vehicle does not belong to the selected Fleet account',409);const agreementId=optional(input.serviceAgreementId,128);let agreement:Row|null=null;if(agreementId){agreement=await one(client,'SELECT * FROM fleet_service_agreements WHERE organization_id=$1 AND id=$2 AND customer_id=$3',[organizationId,agreementId,customerId],'Service agreement does not belong to this Fleet account');}
 const serviceIds=Array.isArray(input.serviceIds)?input.serviceIds.map(String).filter(Boolean):[];if(!serviceIds.length)throw new FleetServiceModelError('At least one service is required',400);const services=(await client.query(`SELECT s.id,s.name,s.default_price,s.default_labor_minutes,COALESCE(a.unit_price,s.default_price) AS price,COALESCE(a.labor_minutes,s.default_labor_minutes) AS labor_minutes FROM service_catalog s LEFT JOIN fleet_agreement_services a ON a.service_id=s.id AND a.agreement_id=$3 AND a.enabled=true WHERE s.organization_id=$1 AND s.id=ANY($2::text[]) AND s.active=true`,[organizationId,serviceIds,agreementId])).rows;if(services.length!==serviceIds.length)throw new FleetServiceModelError('One or more selected services are unavailable',400);const total=services.reduce((sum:any,s:any)=>sum+Number(s.price||0),0);const autoAuthorized=agreement?(agreement.approval_mode==='auto'||(agreement.approval_mode==='hybrid'&&total<=Number(agreement.approval_threshold||0))):false;const workId=randomUUID();const number=optional(input.number,80)||`WO-${new Date().getUTCFullYear()}-${Date.now().toString().slice(-6)}`;await client.query(`INSERT INTO work_orders(id,organization_id,customer_id,vehicle_id,location_id,number,status,priority,complaint,requested_services,purchase_order_number,service_agreement_id) VALUES($1,$2,$3,$4,$5,$6,'scheduled',$7,$8,$9::text[],$10,$11)`,[workId,organizationId,customerId,vehicleId,vehicle.location_id,number,optional(input.priority,30)||'routine',optional(input.complaint),services.map((s:any)=>s.name),optional(input.purchaseOrderNumber,100),agreementId]);for(const service of services)await client.query(`INSERT INTO service_lines(id,organization_id,work_order_id,service_id,description,kind,labor_minutes,quantity,unit_price,authorized) VALUES($1,$2,$3,$4,$5,'service',$6,1,$7,$8)`,[randomUUID(),organizationId,workId,service.id,service.name,Number(service.labor_minutes||0),Number(service.price||0),autoAuthorized]);return one(client,`SELECT w.*,c.name AS customer_name,v.unit_number FROM work_orders w JOIN customers c ON c.id=w.customer_id JOIN vehicles v ON v.id=w.vehicle_id WHERE w.organization_id=$1 AND w.id=$2`,[organizationId,workId],'Work order creation failed')})}

export async function workOrderChain(organizationId:string,workOrderId:string){return withPool(async pool=>one(pool,'SELECT id,customer_id,vehicle_id,location_id FROM work_orders WHERE organization_id=$1 AND id=$2',[organizationId,workOrderId],'Work order not found'))}
export async function syncWorkOrderSchedule(organizationId:string,workOrderId:string,startsAt:unknown){return withPool(async pool=>{await pool.query('UPDATE work_orders SET scheduled_at=$3::timestamptz,updated_at=now() WHERE organization_id=$1 AND id=$2',[organizationId,workOrderId,startsAt]);})}
export async function syncWorkOrderTechnician(organizationId:string,workOrderId:string,technicianId:string){return withPool(async pool=>{await one(pool,'SELECT id FROM technicians WHERE organization_id=$1 AND id=$2 AND active=true',[organizationId,technicianId],'Technician not found');await pool.query(`UPDATE work_orders SET technician_id=$3,status=CASE WHEN status IN ('draft','scheduled') THEN 'assigned' ELSE status END,updated_at=now() WHERE organization_id=$1 AND id=$2`,[organizationId,workOrderId,technicianId]);})}
export async function syncDispatchTechnician(organizationId:string,dispatchId:string){return withPool(async pool=>{const row=await one(pool,'SELECT work_order_id,technician_id,status FROM dispatch_assignments WHERE organization_id=$1 AND id=$2',[organizationId,dispatchId],'Dispatch not found');if(row.status==='cancelled')return;await pool.query(`UPDATE work_orders SET technician_id=$3,status=CASE WHEN status IN ('draft','scheduled') THEN 'assigned' ELSE status END,updated_at=now() WHERE organization_id=$1 AND id=$2`,[organizationId,row.work_order_id,row.technician_id]);})}
export async function deleteInventoryPart(organizationId:string,partId:string){return withTx(async client=>{await one(client,'SELECT id FROM parts WHERE organization_id=$1 AND id=$2',[organizationId,partId],'Part not found');const used=await client.query('SELECT 1 FROM part_usage WHERE organization_id=$1 AND part_id=$2 LIMIT 1',[organizationId,partId]);if(used.rowCount)throw new FleetServiceModelError('This part has service history and cannot be deleted. Deactivate it instead.',409);await client.query('DELETE FROM vehicle_service_profiles WHERE organization_id=$1 AND preferred_part_id=$2',[organizationId,partId]);await client.query('DELETE FROM vehicle_parts WHERE organization_id=$1 AND part_id=$2',[organizationId,partId]);await client.query('DELETE FROM inventory WHERE organization_id=$1 AND part_id=$2',[organizationId,partId]);const deleted=await client.query('DELETE FROM parts WHERE organization_id=$1 AND id=$2 RETURNING id',[organizationId,partId]);return{deleted:Boolean(deleted.rowCount),id:partId}})}
