import { Pool } from '@neondatabase/serverless';

type QueryValue=string|number|null;
type PageOptions={search?:unknown;cursor?:unknown;limit?:unknown;stage?:unknown;technicianId?:string|null};
type Cursor={updatedAt:string;id:string};

function databaseUrl(){const value=process.env.DATABASE_URL||process.env.NEON_DATABASE_URL;if(!value)throw new Error('Database is not configured');return value}
function limitOf(value:unknown){const n=Number(value||50);return Number.isFinite(n)?Math.min(100,Math.max(10,Math.round(n))):50}
function text(value:unknown,max=100){return String(value??'').trim().slice(0,max)}
function encodeCursor(row:any){const updated=row.updatedAt??row.updated_at;if(!updated||!row.id)return null;return Buffer.from(JSON.stringify({updatedAt:new Date(updated).toISOString(),id:String(row.id)})).toString('base64url')}
function decodeCursor(value:unknown):Cursor|null{const raw=text(value,1000);if(!raw)return null;try{const parsed=JSON.parse(Buffer.from(raw,'base64url').toString('utf8'));const d=new Date(String(parsed.updatedAt));if(Number.isNaN(d.getTime())||!parsed.id)throw new Error();return{updatedAt:d.toISOString(),id:String(parsed.id)}}catch{throw new Error('Invalid list cursor')}}
async function withPool<T>(work:(pool:Pool)=>Promise<T>){const pool=new Pool({connectionString:databaseUrl()});try{return await work(pool)}finally{await pool.end()}}
function page<T extends {id:string}>(rows:T[],limit:number){const hasMore=rows.length>limit;const items=hasMore?rows.slice(0,limit):rows;return{items,hasMore,nextCursor:hasMore?encodeCursor(items[items.length-1]):null}}
function addCursor(where:string[],values:QueryValue[],cursor:Cursor|null){if(!cursor)return;values.push(cursor.updatedAt,cursor.id);where.push(`(x.updated_at, x.id::text) < ($${values.length-1}::timestamptz, $${values.length}::text)`)}

export async function pagedCustomers(organizationId:string,options:PageOptions={}){return withPool(async pool=>{const limit=limitOf(options.limit),cursor=decodeCursor(options.cursor),search=text(options.search);const values:QueryValue[]=[organizationId],where=['x.organization_id=$1'];if(search){values.push(`%${search}%`);where.push(`(x.name ILIKE $${values.length} OR x.billing_email ILIKE $${values.length} OR x.primary_contact_name ILIKE $${values.length} OR x.primary_contact_email ILIKE $${values.length})`)}addCursor(where,values,cursor);values.push(limit+1);const result=await pool.query(`SELECT x.id,x.name,x.account_number AS "accountNumber",x.primary_contact_name AS "primaryContactName",x.primary_contact_email AS "primaryContactEmail",x.billing_contact_name AS "billingContactName",x.billing_address AS "billingAddress",x.po_required AS "poRequired",x.default_po_number AS "defaultPoNumber",x.payment_terms AS "paymentTerms",x.tax_status AS "taxStatus",x.billing_email AS "billingEmail",x.phone,x.status,x.notes,x.updated_at AS "updatedAt",(SELECT count(*)::int FROM vehicles v WHERE v.organization_id=$1 AND v.customer_id=x.id) AS "vehicleCount",coalesce(x.primary_contact_name,(SELECT c.name FROM contacts c WHERE c.organization_id=$1 AND c.customer_id=x.id AND c.is_primary=true ORDER BY c.updated_at DESC LIMIT 1)) AS "primaryContact",coalesce(x.primary_contact_email,(SELECT c.email FROM contacts c WHERE c.organization_id=$1 AND c.customer_id=x.id AND c.is_primary=true ORDER BY c.updated_at DESC LIMIT 1)) AS "contactEmail",(SELECT coalesce(sum(i.total),0)::text FROM invoices i WHERE i.organization_id=$1 AND i.customer_id=x.id AND i.created_at>=now()-interval '30 days' AND i.status NOT IN ('void','draft')) AS "spend30Days" FROM customers x WHERE ${where.join(' AND ')} ORDER BY x.updated_at DESC,x.id DESC LIMIT $${values.length}` ,values);return page(result.rows as any[],limit)})}

export async function pagedVehicles(organizationId:string,options:PageOptions={}){return withPool(async pool=>{const limit=limitOf(options.limit),cursor=decodeCursor(options.cursor),search=text(options.search);const values:QueryValue[]=[organizationId],where=['x.organization_id=$1'];if(search){values.push(`%${search}%`);where.push(`(x.unit_number ILIKE $${values.length} OR x.vin ILIKE $${values.length} OR x.make ILIKE $${values.length} OR x.model ILIKE $${values.length} OR EXISTS(SELECT 1 FROM customers c WHERE c.organization_id=$1 AND c.id=x.customer_id AND c.name ILIKE $${values.length}))`)}addCursor(where,values,cursor);values.push(limit+1);const result=await pool.query(`SELECT x.id,x.organization_id,x.customer_id,x.unit_number,x.vin,x.year,x.make,x.model,x.trim,x.engine,x.fuel_type,x.license_plate,x.registration_state,x.mileage,x.engine_hours,x.status,x.assigned_driver,x.department,x.in_service_date,x.notes,x.specifications,x.metadata,x.created_at,x.updated_at AS "updatedAt" FROM vehicles x WHERE ${where.join(' AND ')} ORDER BY x.updated_at DESC,x.id DESC LIMIT $${values.length}`,values);return page(result.rows as any[],limit)})}

export async function pagedProspects(organizationId:string,options:PageOptions={}){return withPool(async pool=>{const limit=limitOf(options.limit),cursor=decodeCursor(options.cursor),search=text(options.search),stage=text(options.stage,40);const values:QueryValue[]=[organizationId],where=['x.organization_id=$1'];if(stage){values.push(stage);where.push(`x.stage=$${values.length}`)}if(search){values.push(`%${search}%`);where.push(`(x.company_name ILIKE $${values.length} OR x.website ILIKE $${values.length} OR x.industry ILIKE $${values.length} OR x.service_area ILIKE $${values.length})`)}addCursor(where,values,cursor);values.push(limit+1);const result=await pool.query(`SELECT x.id,x.company_name AS "companyName",x.website,x.industry,x.service_area AS "serviceArea",x.estimated_fleet_size AS "estimatedFleetSize",x.stage,x.qualification_score AS "qualificationScore",x.opportunity_value AS "opportunityValue",x.probability,x.last_researched_at AS "lastResearchedAt",x.converted_customer_id AS "convertedCustomerId",x.updated_at AS "updatedAt" FROM prospects x WHERE ${where.join(' AND ')} ORDER BY x.updated_at DESC,x.id DESC LIMIT $${values.length}`,values);return page(result.rows as any[],limit)})}

export async function pagedWorkOrders(organizationId:string,options:PageOptions={}){return withPool(async pool=>{const limit=limitOf(options.limit),cursor=decodeCursor(options.cursor),search=text(options.search);const values:QueryValue[]=[organizationId],where=['x.organization_id=$1'];if(options.technicianId){values.push(options.technicianId);where.push(`x.technician_id=$${values.length}`)}if(search){values.push(`%${search}%`);where.push(`(x.number ILIKE $${values.length} OR x.complaint ILIKE $${values.length} OR v.unit_number ILIKE $${values.length} OR c.name ILIKE $${values.length})`)}addCursor(where,values,cursor);values.push(limit+1);const result=await pool.query(`SELECT x.id,x.number,x.status,x.priority,x.complaint,x.diagnosis,x.completed_at AS "completedAt",x.scheduled_at AS "scheduledAt",x.technician_id AS "technicianId",x.odometer,x.engine_hours AS "engineHours",x.purchase_order_number AS "purchaseOrderNumber",x.requested_services AS "requestedServices",x.customer_notes AS "customerNotes",x.technician_notes AS "technicianNotes",x.labor_minutes AS "laborMinutes",x.travel_minutes AS "travelMinutes",x.location_id AS "locationId",x.created_at AS "createdAt",x.updated_at AS "updatedAt",v.id AS "vehicleId",v.unit_number AS "unitNumber",v.year,v.make,v.model,c.id AS "customerId",c.name AS "customerName" FROM work_orders x LEFT JOIN vehicles v ON v.id=x.vehicle_id AND v.organization_id=$1 LEFT JOIN customers c ON c.id=x.customer_id AND c.organization_id=$1 WHERE ${where.join(' AND ')} ORDER BY x.updated_at DESC,x.id DESC LIMIT $${values.length}`,values);return page(result.rows as any[],limit)})}
