import { createHmac, timingSafeEqual, randomUUID } from 'node:crypto';
import { and, eq } from 'drizzle-orm';
import { getDb } from '../../db/index.js';
import { inboxes } from '../../db/drizzleSchema.js';
import { prospectActivities, prospectContacts, prospects } from '../../db/prospectSchema.js';

function database(){const db=getDb();if(!db)throw new Error('Database is not configured');return db;}
function address(value:unknown):string{if(typeof value==='string'){const match=value.match(/<([^>]+)>/);return (match?.[1]||value).trim().toLowerCase();}if(Array.isArray(value))return address(value[0]);return '';}
function text(value:unknown,max=10000){return String(value??'').trim().slice(0,max);}
export function verifyAgentMailWebhook(raw:Buffer,headers:Record<string,unknown>,secret:string){const id=text(headers['svix-id']||headers['Svix-Id'],300);const timestamp=text(headers['svix-timestamp']||headers['Svix-Timestamp'],50);const signature=text(headers['svix-signature']||headers['Svix-Signature'],2000);if(!id||!timestamp||!signature||!secret.startsWith('whsec_'))return false;const unix=Number(timestamp);if(!Number.isFinite(unix)||Math.abs(Date.now()/1000-unix)>300)return false;let key:Buffer;try{key=Buffer.from(secret.slice(6),'base64')}catch{return false}const expected=createHmac('sha256',key).update(`${id}.${timestamp}.${raw.toString('utf8')}`).digest('base64');return signature.split(' ').some(part=>{const candidate=part.startsWith('v1,')?part.slice(3):'';if(!candidate)return false;const a=Buffer.from(candidate);const b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b);});}
export class ProspectWebhookService{async handle(payload:any){if(payload?.event_type!=='message.received')return{handled:false,reason:'ignored_event'};const message=payload?.message||{};const inboxId=text(message.inbox_id,300);if(!inboxId)return{handled:false,reason:'missing_inbox'};const db=database();const [inbox]=await db.select().from(inboxes).where(eq(inboxes.externalInboxId,inboxId)).limit(1);if(!inbox)return{handled:false,reason:'unknown_inbox'};const organizationId=inbox.organizationId;const from=address(message.from_||message.from);if(!from)return{handled:false,reason:'missing_sender'};const contacts=await db.select().from(prospectContacts).where(eq(prospectContacts.organizationId,organizationId));const contact=contacts.find(c=>address(c.email)===from);const prospectRows=await db.select().from(prospects).where(eq(prospects.organizationId,organizationId));let prospectId=contact?.prospectId;let contactId=contact?.id;let prospect=prospectId?prospectRows.find(p=>p.id===prospectId):undefined;if(!prospect){prospect=prospectRows.find(p=>address(p.generalEmail)===from);prospectId=prospect?.id;contactId=undefined;}if(!prospect||!prospectId)return{handled:false,reason:'no_matching_prospect',organizationId};const externalMessageId=text(message.message_id||payload.event_id,300);if(externalMessageId){const [existing]=await db.select({id:prospectActivities.id}).from(prospectActivities).where(and(eq(prospectActivities.organizationId,organizationId),eq(prospectActivities.externalMessageId,externalMessageId))).limit(1);if(existing)return{handled:true,duplicate:true,prospectId,organizationId};}const occurredAt=message.timestamp||message.created_at||message.received_timestamp;await db.insert(prospectActivities).values({id:randomUUID(),organizationId,prospectId,kind:'reply_email',direction:'inbound',channel:'agentmail',subject:text(message.subject,998)||null,summary:text(message.text||message.extracted_text||message.preview,10000)||null,externalMessageId:externalMessageId||null,occurredAt:occurredAt?new Date(occurredAt):new Date(),metadata:{from,contactId:contactId||null,inboxId,threadId:message.thread_id||null,eventId:payload.event_id||null,source:'webhook'}});const nextStage=['new','researching','qualified','outreach'].includes(prospect.stage)?'engaged':prospect.stage;await db.update(prospects).set({stage:nextStage,nextFollowUpAt:new Date(),updatedAt:new Date()}).where(and(eq(prospects.organizationId,organizationId),eq(prospects.id,prospectId)));return{handled:true,duplicate:false,prospectId,organizationId,stage:nextStage};}}
export const prospectWebhookService=new ProspectWebhookService();
