import { Pool } from '@neondatabase/serverless';
import { randomUUID } from 'node:crypto';
import { normalizeVehicleServiceSpecifications, type VehicleServiceSpecifications } from './vehicleSpecifications.js';

export type VehicleStatus='active'|'down'|'out_of_service'|'retired';
export interface VehicleInput {id?:string;customerId:string;unitNumber:string;vin?:string|null;year?:number|null;make?:string|null;model?:string|null;engine?:string|null;mileage?:number|null;engineHours?:number|null;status?:VehicleStatus;trim?:string|null;fuelType?:string|null;licensePlate?:string|null;registrationState?:string|null;assignedDriver?:string|null;department?:string|null;inServiceDate?:string|null;notes?:string|null;specifications?:Partial<VehicleServiceSpecifications>|Record<string,unknown>|null;type?:string|null;assignment?:string|null}
const VIN_PATTERN=/^[A-HJ-NPR-Z0-9]{17}$/;const statuses=new Set<VehicleStatus>(['active','down','out_of_service','retired']);
function databaseUrl(){const value=process.env.DATABASE_URL||process.env.NEON_DATABASE_URL;if(!value)throw new VehicleStoreError('Database is not configured',503);return value}
export class VehicleStoreError extends Error{constructor(message:string,public readonly status=400){super(message)}}
function normalize(input:VehicleInput){const customerId=String(input.customerId||'').trim();const unitNumber=String(input.unitNumber||'').trim();const vin=input.vin?String(input.vin).trim().toUpperCase():null;const year=input.year==null||input.year===0?null:Number(input.year);const mileage=input.mileage==null?0:Number(input.mileage);const engineHours=input.engineHours==null?null:Number(input.engineHours);const status=input.status||'active';if(!customerId)throw new VehicleStoreError('Fleet account is required');if(!unitNumber)throw new VehicleStoreError('Unit number is required');if(vin&&!VIN_PATTERN.test(vin))throw new VehicleStoreError('VIN must be 17 characters and cannot contain I, O, or Q');if(year!==null&&(!Number.isInteger(year)||year<1886||year>new Date().getFullYear()+2))throw new VehicleStoreError('Vehicle year is invalid');if(!Number.isInteger(mileage)||mileage<0)throw new VehicleStoreError('Mileage must be a non-negative whole number');if(engineHours!==null&&(!Number.isInteger(engineHours)||engineHours<0))throw new VehicleStoreError('Engine hours must be a non-negative whole number');if(!statuses.has(status))throw new VehicleStoreError('Vehicle status is invalid');return{customerId,unitNumber,vin,year,mileage,engineHours,status,make:input.make?.trim()||null,model:input.model?.trim()||null,engine:input.engine?.trim()||null,trim:input.trim?.trim()||null,fuelType:input.fuelType?.trim()||null,licensePlate:input.licensePlate?.trim()||null,registrationState:input.registrationState?.trim()||null,assignedDriver:input.assignedDriver?.trim()||null,department:input.department?.trim()||null,inServiceDate:input.inServiceDate?.trim()||null,notes:input.notes?.trim()||null,specifications:normalizeVehicleServiceSpecifications(input.specifications),type:input.type?.trim()||null,assignment:input.assignment?.trim()||null}}
async function withPool<T>(work:(pool:Pool)=>Promise<T>){const pool=new Pool({connectionString:databaseUrl()});try{return await work(pool)}finally{await pool.end()}}
type Queryable=Pick<Pool,'query'>;
async function resolveOrganizationId(pool:Pool,requested?:string){const configured=process.env.FLEET_ORGANIZATION_ID?.trim();const candidate=requested?.trim()||configured;if(candidate){const found=await pool.query('SELECT id FROM organizations WHERE id=$1 AND status=$2 LIMIT 1',[candidate,'active']);if(!found.rows[0])throw new VehicleStoreError('Active organization not found',404);return String(found.rows[0].id)}const result=await pool.query('SELECT id FROM organizations WHERE status=$1 ORDER BY created_at LIMIT 2',['active']);if(result.rows.length===1)return String(result.rows[0].id);if(!result.rows.length)throw new VehicleStoreError('No active organization has been provisioned',503);throw new VehicleStoreError('Organization context is required',401)}
const selectColumns=`id, organization_id, customer_id, unit_number, vin, year, make, model, trim, engine, fuel_type, license_plate, registration_state, mileage, engine_hours, status, assigned_driver, department, in_service_date, notes, specifications, metadata, created_at, updated_at`;
async function assertCustomer(pool:Queryable,organizationId:string,customerId:string){const result=await pool.query('SELECT id FROM customers WHERE organization_id=$1 AND id=$2 LIMIT 1',[organizationId,customerId]);if(!result.rows[0])throw new VehicleStoreError('Fleet account not found',404)}
export async function listVehicles(requestedOrganizationId?:string){return withPool(async pool=>{const organizationId=await resolveOrganizationId(pool,requestedOrganizationId);const result=await pool.query(`SELECT ${selectColumns} FROM vehicles WHERE organization_id=$1 ORDER BY updated_at DESC`,[organizationId]);return{organizationId,vehicles:result.rows}})}
async function insertVehicle(pool:Queryable,organizationId:string,raw:VehicleInput){const value=normalize(raw);await assertCustomer(pool,organizationId,value.customerId);const metadata={type:value.type,assignment:value.assignment};try{const result=await pool.query(`INSERT INTO vehicles(id,organization_id,customer_id,unit_number,vin,year,make,model,trim,engine,fuel_type,license_plate,registration_state,mileage,engine_hours,status,assigned_driver,department,in_service_date,notes,specifications,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19::timestamptz,$20,$21::jsonb,$22::jsonb) RETURNING ${selectColumns}`,[randomUUID(),organizationId,value.customerId,value.unitNumber,value.vin,value.year,value.make,value.model,value.trim,value.engine,value.fuelType,value.licensePlate,value.registrationState,value.mileage,value.engineHours,value.status,value.assignedDriver,value.department,value.inServiceDate,value.notes,JSON.stringify(value.specifications),JSON.stringify(metadata)]);return result.rows[0]}catch(error){if(error instanceof Error&&/unique|duplicate/i.test(error.message))throw new VehicleStoreError(`Unit ${value.unitNumber} already exists`,409);throw error}}
export async function createVehicle(raw:VehicleInput,requestedOrganizationId?:string){return withPool(async pool=>insertVehicle(pool,await resolveOrganizationId(pool,requestedOrganizationId),raw))}
export async function importVehicles(raw:VehicleInput[],requestedOrganizationId?:string){if(!Array.isArray(raw)||!raw.length)throw new VehicleStoreError('At least one vehicle is required');if(raw.length>500)throw new VehicleStoreError('A maximum of 500 vehicles can be imported');return withPool(async pool=>{const organizationId=await resolveOrganizationId(pool,requestedOrganizationId);const client=await pool.connect();try{await client.query('BEGIN');const vehicles=[];for(const value of raw)vehicles.push(await insertVehicle(client,organizationId,value));await client.query('COMMIT');return vehicles}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}})}
export async function updateVehicle(id:string,raw:VehicleInput,requestedOrganizationId?:string){if(!id.trim())throw new VehicleStoreError('Vehicle id is required');return withPool(async pool=>{const organizationId=await resolveOrganizationId(pool,requestedOrganizationId);const value=normalize(raw);await assertCustomer(pool,organizationId,value.customerId);const metadata={type:value.type,assignment:value.assignment};const result=await pool.query(`UPDATE vehicles SET customer_id=$3,unit_number=$4,vin=$5,year=$6,make=$7,model=$8,trim=$9,engine=$10,fuel_type=$11,license_plate=$12,registration_state=$13,mileage=$14,engine_hours=$15,status=$16,assigned_driver=$17,department=$18,in_service_date=$19::timestamptz,notes=$20,specifications=$21::jsonb,metadata=$22::jsonb,updated_at=NOW() WHERE organization_id=$1 AND id=$2 RETURNING ${selectColumns}`,[organizationId,id,value.customerId,value.unitNumber,value.vin,value.year,value.make,value.model,value.trim,value.engine,value.fuelType,value.licensePlate,value.registrationState,value.mileage,value.engineHours,value.status,value.assignedDriver,value.department,value.inServiceDate,value.notes,JSON.stringify(value.specifications),JSON.stringify(metadata)]);if(!result.rows[0])throw new VehicleStoreError('Vehicle not found',404);return result.rows[0]})}
export async function deleteVehicle(id:string,requestedOrganizationId?:string){return withPool(async pool=>{const organizationId=await resolveOrganizationId(pool,requestedOrganizationId);const result=await pool.query('DELETE FROM vehicles WHERE organization_id=$1 AND id=$2',[organizationId,id]);if(!result.rowCount)throw new VehicleStoreError('Vehicle not found',404)})}
