import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, Eye, LoaderCircle, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { operationsApi, type CustomerRow } from './operationsApi';

const money=(value:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));

export function CustomersWorkspace(){
  const[rows,setRows]=useState<CustomerRow[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<CustomerRow|null>(null),[viewing,setViewing]=useState<CustomerRow|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setRows((await operationsApi.customers(search)).customers)}catch(e){setError(e instanceof Error?e.message:'Unable to load customers')}finally{setLoading(false)}},[search]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  const totals=useMemo(()=>({vehicles:rows.reduce((n,r)=>n+Number(r.vehicleCount||0),0),spend:rows.reduce((n,r)=>n+Number(r.spend30Days||0),0)}),[rows]);
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));try{if(editing)await operationsApi.updateCustomer(editing.id,data);else await operationsApi.createCustomer(data);setOpen(false);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save customer')}}
  async function remove(id:string){if(!window.confirm('Delete this customer? Linked fleet records may prevent deletion.'))return;try{await operationsApi.deleteCustomer(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete customer')}}
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Fleet accounts</p><h2 className="mt-1 text-3xl font-bold text-slate-950">Customers</h2><p className="mt-2 text-sm text-slate-600">Live customer, contact, vehicle, and billing data.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>New customer</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3">{[['Accounts',String(rows.length)],['Vehicles managed',String(totals.vehicles)],['30-day value',money(String(totals.spend))]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p></div>)}</div>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between gap-3 border-b p-5"><div><h3 className="font-bold">Fleet accounts</h3><p className="text-xs text-slate-500">Backed by Neon Postgres</p></div><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers…" className="h-9 rounded-xl border border-slate-200 pl-9 pr-3 text-sm"/></label></div>
      {loading?<div className="flex h-48 items-center justify-center"><LoaderCircle className="h-6 w-6 animate-spin text-blue-600"/></div>:rows.length===0?<div className="p-12 text-center"><Building2 className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-semibold">No customers found</p></div>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Account','Fleet size','Primary contact','Email','30-day spend','Standing','Actions'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-bold">{r.name}</td><td className="px-5 py-4">{r.vehicleCount} vehicles</td><td className="px-5 py-4">{r.primaryContact||'—'}</td><td className="px-5 py-4">{r.contactEmail||r.billingEmail||'—'}</td><td className="px-5 py-4 font-bold">{money(r.spend30Days)}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{r.status}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button aria-label="View customer" onClick={()=>setViewing(r)}><Eye className="h-4 w-4"/></button><button aria-label="Edit customer" onClick={()=>{setEditing(r);setOpen(true)}}><Pencil className="h-4 w-4"/></button><button aria-label="Delete customer" onClick={()=>remove(r.id)} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>}
    </section>
    {viewing&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><h3 className="text-lg font-bold">{viewing.name}</h3><button onClick={()=>setViewing(null)}><X/></button></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Account</dt><dd>{viewing.accountNumber||'—'}</dd></div><div><dt className="text-slate-500">Phone</dt><dd>{viewing.phone||'—'}</dd></div><div><dt className="text-slate-500">Email</dt><dd>{viewing.billingEmail||'—'}</dd></div><div><dt className="text-slate-500">Status</dt><dd>{viewing.status}</dd></div><div className="col-span-2"><dt className="text-slate-500">Notes</dt><dd>{viewing.notes||'—'}</dd></div></dl></div></div>}
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h3 className="text-lg font-bold">{editing?'Edit customer':'New customer'}</h3><button type="button" onClick={()=>{setOpen(false);setEditing(null)}}><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><input required name="name" defaultValue={editing?.name||''} placeholder="Company name" className="rounded-xl border p-3 sm:col-span-2"/><input name="accountNumber" defaultValue={editing?.accountNumber||''} placeholder="Account number" className="rounded-xl border p-3"/><input name="phone" defaultValue={editing?.phone||''} placeholder="Phone" className="rounded-xl border p-3"/><input name="billingEmail" defaultValue={editing?.billingEmail||''} type="email" placeholder="Billing email" className="rounded-xl border p-3 sm:col-span-2"/><textarea name="notes" defaultValue={editing?.notes||''} placeholder="Notes" className="rounded-xl border p-3 sm:col-span-2"/></div><button className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">{editing?'Save changes':'Create customer'}</button></form></div>}
  </div></main>
}
