import React,{useCallback,useEffect,useState}from'react';
import{Building2,ChevronRight,Loader2,Pencil,Plus,Search,Trash2,X}from'lucide-react';
import{fleetFetch}from'../../lib/fleetApi';
import{operationsApi,type CustomerRow}from'./operationsApi';
import{FleetAccount360Drawer}from'./FleetAccount360Drawer';
import{mergeUniqueById,readListParam,rememberListScroll,replaceListParams,restoreListScroll}from'../../lib/operationalListState';

type AccountRow=CustomerRow&{vehicleCount?:number;agreementName?:string|null;slaHours?:number|null;openWorkCount?:number};
type CustomerPage={customers:AccountRow[];nextCursor:string|null;hasMore:boolean};
type SetupStep='account'|'agreement'|'vehicle'|'done';
const initialAccount={name:'',primaryContactName:'',primaryContactEmail:'',phone:'',paymentTerms:'net_30',status:'active'};
const initialAgreement={name:'',slaHours:'24',approvalMode:'hybrid',approvalThreshold:'500',billingModel:'per_service',invoiceFrequency:'monthly',paymentTerms:'net_30',poRequired:false};
const initialVehicle={unitNumber:'',vin:'',year:'',make:'',model:'',mileage:''};
const field='h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const primary='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-50';
async function fleetApi<T>(path:string,init:RequestInit={}):Promise<T>{const r=await fleetFetch(path,{...init,headers:{'Content-Type':'application/json',...init.headers}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Request failed (${r.status})`);return b as T}
const emailOk=(v:string)=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const vinOk=(v:string)=>!v||/^[A-HJ-NPR-Z0-9]{17}$/i.test(v);

export function FleetAccountsCertifiedWorkspace(){
 const[rows,setRows]=useState<AccountRow[]>([]),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(()=>readListParam('q')),[nextCursor,setNextCursor]=useState<string|null>(null),[hasMore,setHasMore]=useState(false),[viewId,setViewId]=useState<string|null>(null),[setupOpen,setSetupOpen]=useState(false),[step,setStep]=useState<SetupStep>('account'),[accountId,setAccountId]=useState(''),[accountName,setAccountName]=useState(''),[editing,setEditing]=useState<AccountRow|null>(null);
 const[account,setAccount]=useState(initialAccount),[agreement,setAgreement]=useState(initialAgreement),[vehicle,setVehicle]=useState(initialVehicle),[saving,setSaving]=useState(false);
 const load=useCallback(async(cursor:string|null=null,append=false)=>{append?setLoadingMore(true):setLoading(true);setError('');try{const p=new URLSearchParams({limit:'50'});if(search.trim())p.set('search',search.trim());if(cursor)p.set('cursor',cursor);const page=await fleetApi<CustomerPage>(`/api/operations/customers?${p}`);setRows(current=>append?mergeUniqueById(current,page.customers||[]):page.customers||[]);setNextCursor(page.nextCursor||null);setHasMore(Boolean(page.hasMore))}catch(e){setError(e instanceof Error?e.message:'Unable to load fleet accounts')}finally{setLoading(false);setLoadingMore(false)}},[search]);
 useEffect(()=>{replaceListParams({q:search||null});const t=setTimeout(()=>void load(null,false),250);return()=>clearTimeout(t)},[load,search]);
 useEffect(()=>{restoreListScroll('fleet-accounts');return()=>rememberListScroll('fleet-accounts')},[]);
 const stats=(r:AccountRow)=>({vehicles:Number(r.vehicleCount||0),agreement:r.agreementName?{name:r.agreementName,sla_hours:r.slaHours}:null,open:Number(r.openWorkCount||0),complete:Boolean(r.agreementName)&&Number(r.vehicleCount||0)>0});
 function startNew(){setEditing(null);setAccount(initialAccount);setAgreement(initialAgreement);setVehicle(initialVehicle);setAccountId('');setAccountName('');setStep('account');setError('');setSetupOpen(true)}
 function resume(r:AccountRow){const s=stats(r);setEditing(null);setAccountId(r.id);setAccountName(r.name);setAgreement({...initialAgreement,name:r.agreementName||`${r.name} Service Agreement`,slaHours:String(r.slaHours||24),paymentTerms:r.paymentTerms||'net_30'});setVehicle(initialVehicle);setStep(!s.agreement?'agreement':s.vehicles===0?'vehicle':'done');setError('');setSetupOpen(true)}
 function edit(r:AccountRow){setEditing(r);setAccount({name:r.name,primaryContactName:r.primaryContactName||'',primaryContactEmail:r.primaryContactEmail||'',phone:r.phone||'',paymentTerms:r.paymentTerms||'net_30',status:r.status||'active'});setAccountId(r.id);setAccountName(r.name);setStep('account');setError('');setSetupOpen(true)}
 async function saveAccount(e:React.FormEvent){e.preventDefault();if(!account.name.trim())return setError('Fleet account name is required.');if(!emailOk(account.primaryContactEmail))return setError('Enter a valid primary email.');setSaving(true);setError('');try{if(editing){await operationsApi.updateCustomer(editing.id,account);setSetupOpen(false);setEditing(null);await load(null,false);return}const result:any=await operationsApi.createCustomer(account);const created=result.customer;setAccountId(created.id);setAccountName(created.name);setAgreement(v=>({...v,name:`${created.name} Service Agreement`,paymentTerms:account.paymentTerms}));setStep('agreement');await load(null,false)}catch(e){setError(e instanceof Error?e.message:'Unable to save fleet account')}finally{setSaving(false)}}
 async function saveAgreement(e:React.FormEvent){e.preventDefault();if(!agreement.name.trim()||Number(agreement.slaHours)<=0||Number(agreement.approvalThreshold)<0)return setError('Agreement name, SLA hours, and approval threshold are required.');setSaving(true);setError('');try{await fleetApi('/api/fleet-service/agreements',{method:'POST',body:JSON.stringify({...agreement,customerId:accountId})});setStep('vehicle');await load(null,false)}catch(e){setError(e instanceof Error?e.message:'Unable to save agreement')}finally{setSaving(false)}}
 async function saveVehicle(e:React.FormEvent){e.preventDefault();if(!vehicle.unitNumber.trim())return setError('Unit number is required.');if(!vinOk(vehicle.vin.trim()))return setError('VIN must be 17 valid characters and cannot contain I, O, or Q.');setSaving(true);setError('');try{await fleetApi('/api/fleet-service/vehicles',{method:'POST',body:JSON.stringify({...vehicle,customerId:accountId})});setStep('done');await load(null,false)}catch(e){setError(e instanceof Error?e.message:'Unable to add vehicle')}finally{setSaving(false)}}
 async function remove(r:AccountRow){if(!window.confirm(`Delete ${r.name}? Fleet records with service history may prevent deletion.`))return;setError('');try{const result:any=await operationsApi.deleteCustomer(r.id);if(!result.deleted)throw new Error('Fleet account was not deleted');await load(null,false)}catch(e){setError(e instanceof Error?e.message:'Unable to delete fleet account')}}
 if(loading&&!rows.length)return <div className="grid flex-1 place-items-center bg-[#f7f8fa]"><Loader2 className="h-6 w-6 animate-spin text-blue-600"/></div>;
 return <main className="min-w-0 flex-1 overflow-y-auto bg-[#f7f8fa]"><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8">
  <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Fleet accounts</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Fleet customers</h1><p className="mt-1.5 text-sm text-slate-500">Server-filtered, cursor-paged accounts with setup health summarized without loading the entire fleet graph.</p></div><button onClick={startNew} className={primary}><Plus className="h-4 w-4"/>Add Fleet Account</button></header>
  {error&&<div className="mt-4 border-l-2 border-red-500 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="mt-5 flex items-center justify-between gap-3"><label className="relative min-w-0 flex-1 sm:max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search fleet accounts…" className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></label><span className="text-xs font-semibold text-slate-500">Showing {rows.length}</span></div>
  <section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div data-hscroll className="w-full overflow-x-auto"><table className="min-w-[940px] w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-[.08em] text-slate-500"><tr>{['Fleet account','Vehicles','Agreement / SLA','Open work','Status','Actions'].map(h=><th key={h} className="border-b px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=>{const s=stats(r);return <tr key={r.id} className="border-b border-slate-100"><td className="sticky left-0 bg-white px-4 py-3 font-bold">{r.name}</td><td className="px-4 py-3">{s.vehicles}</td><td className="px-4 py-3">{s.agreement?<><span className="font-semibold">{s.agreement.name}</span><span className="ml-2 text-xs text-slate-500">{s.agreement.sla_hours}h SLA</span></>:<button onClick={()=>resume(r)} className="min-h-10 font-bold text-amber-700 underline underline-offset-2">Setup incomplete — continue</button>}</td><td className="px-4 py-3">{s.open}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${s.complete?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{s.complete?'Ready':'Incomplete'}</span></td><td className="px-4 py-3"><div className="flex items-center gap-2"><button onClick={()=>{rememberListScroll('fleet-accounts');setViewId(r.id)}} className="inline-flex min-h-11 items-center gap-1 rounded-lg border border-blue-200 px-3 text-xs font-bold text-blue-700">Open<ChevronRight className="h-3.5 w-3.5"/></button>{!s.complete&&<button onClick={()=>resume(r)} className="min-h-11 rounded-lg border border-amber-200 px-3 text-xs font-bold text-amber-700">Continue setup</button>}<button aria-label="Edit fleet account" onClick={()=>edit(r)} className="grid h-11 w-11 place-items-center rounded-lg border"><Pencil className="h-4 w-4"/></button><button aria-label="Delete fleet account" onClick={()=>remove(r)} className="grid h-11 w-11 place-items-center rounded-lg border text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></td></tr>})}</tbody></table></div>{rows.length===0&&<div className="p-12 text-center"><Building2 className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 font-semibold">No fleet accounts found</p></div>}{hasMore&&<div className="border-t p-4 text-center"><button disabled={loadingMore||!nextCursor} onClick={()=>void load(nextCursor,true)} className="min-h-11 w-full rounded-xl border bg-white px-5 text-sm font-bold disabled:opacity-50 sm:w-auto">{loadingMore?'Loading…':'Load more Fleet Accounts'}</button></div>}</section>
 </div>
 {viewId&&<FleetAccount360Drawer customerId={viewId} onClose={()=>setViewId(null)}/>} 
 {setupOpen&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-3 sm:p-5"><div className="max-h-[96vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b bg-white p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Fleet account onboarding</p><h2 className="mt-1 text-xl font-bold">{accountName||account.name||'New fleet account'}</h2></div><button aria-label="Close onboarding" onClick={()=>{setSetupOpen(false);setEditing(null)}} className="grid h-11 w-11 place-items-center rounded-lg border"><X className="h-4 w-4"/></button></div><div className="p-5 sm:p-6">{error&&<div className="mb-4 border-l-2 border-red-500 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  {step==='account'&&<form onSubmit={saveAccount} className="grid gap-4 sm:grid-cols-2"><h3 className="sm:col-span-2 text-lg font-bold">{editing?'Edit fleet account':'1. Create the fleet account'}</h3><input className={`${field} sm:col-span-2`} value={account.name} onChange={e=>setAccount(v=>({...v,name:e.target.value}))} placeholder="Company / fleet name"/><input className={field} value={account.primaryContactName} onChange={e=>setAccount(v=>({...v,primaryContactName:e.target.value}))} placeholder="Primary contact"/><input className={field} type="email" value={account.primaryContactEmail} onChange={e=>setAccount(v=>({...v,primaryContactEmail:e.target.value}))} placeholder="Primary email"/><input className={field} value={account.phone} onChange={e=>setAccount(v=>({...v,phone:e.target.value}))} placeholder="Phone"/><select className={field} value={account.paymentTerms} onChange={e=>setAccount(v=>({...v,paymentTerms:e.target.value}))}><option value="due_on_receipt">Due on receipt</option><option value="net_15">Net 15</option><option value="net_30">Net 30</option><option value="net_45">Net 45</option><option value="net_60">Net 60</option></select>{editing&&<select className={field} value={account.status} onChange={e=>setAccount(v=>({...v,status:e.target.value}))}><option value="active">Active</option><option value="on_hold">On hold</option><option value="inactive">Inactive</option></select>}<button disabled={saving} className={`${primary} sm:col-span-2`}>{saving?'Saving…':editing?'Save changes':'Save account & continue'}</button></form>}
  {step==='agreement'&&<form onSubmit={saveAgreement} className="grid gap-4 sm:grid-cols-2"><h3 className="sm:col-span-2 text-lg font-bold">2. Agreement, SLA & pricing rules</h3><input className={`${field} sm:col-span-2`} value={agreement.name} onChange={e=>setAgreement(v=>({...v,name:e.target.value}))} placeholder="Agreement name"/><input className={field} type="number" min="1" value={agreement.slaHours} onChange={e=>setAgreement(v=>({...v,slaHours:e.target.value}))} placeholder="SLA hours"/><input className={field} type="number" min="0" value={agreement.approvalThreshold} onChange={e=>setAgreement(v=>({...v,approvalThreshold:e.target.value}))} placeholder="Approval threshold"/><select className={field} value={agreement.approvalMode} onChange={e=>setAgreement(v=>({...v,approvalMode:e.target.value}))}><option value="manual">Manual approval</option><option value="hybrid">Hybrid threshold</option><option value="auto">Automatic approval</option></select><select className={field} value={agreement.billingModel} onChange={e=>setAgreement(v=>({...v,billingModel:e.target.value}))}><option value="per_service">Per service</option><option value="flat_rate">Flat rate</option><option value="time_and_materials">Time & materials</option><option value="blended">Blended</option></select><button disabled={saving} className={`${primary} sm:col-span-2`}>{saving?'Saving…':'Save agreement & continue'}</button></form>}
  {step==='vehicle'&&<form onSubmit={saveVehicle} className="grid gap-4 sm:grid-cols-2"><h3 className="sm:col-span-2 text-lg font-bold">3. Add the first vehicle</h3><input className={field} value={vehicle.unitNumber} onChange={e=>setVehicle(v=>({...v,unitNumber:e.target.value}))} placeholder="Unit number"/><input className={field} maxLength={17} value={vehicle.vin} onChange={e=>setVehicle(v=>({...v,vin:e.target.value.toUpperCase()}))} placeholder="17-character VIN"/><input className={field} type="number" value={vehicle.year} onChange={e=>setVehicle(v=>({...v,year:e.target.value}))} placeholder="Year"/><input className={field} value={vehicle.make} onChange={e=>setVehicle(v=>({...v,make:e.target.value}))} placeholder="Make"/><input className={field} value={vehicle.model} onChange={e=>setVehicle(v=>({...v,model:e.target.value}))} placeholder="Model"/><input className={field} type="number" min="0" value={vehicle.mileage} onChange={e=>setVehicle(v=>({...v,mileage:e.target.value}))} placeholder="Mileage"/><button disabled={saving} className={`${primary} sm:col-span-2`}>{saving?'Saving…':'Add vehicle & finish'}</button></form>}
  {step==='done'&&<div><h3 className="text-xl font-bold">Fleet account ready</h3><p className="mt-2 text-sm text-slate-500">{accountName} now has the minimum operational chain: account, service agreement, and vehicle.</p><button onClick={()=>{setSetupOpen(false);setViewId(accountId)}} className={`${primary} mt-6 w-full`}>Open {accountName}</button></div>}
 </div></div></div>}
 </main>
}
