import React, { useEffect, useState } from 'react';
import { Activity, Car, FileText, LoaderCircle, Mail, MapPin, Wrench, X } from 'lucide-react';
import { operationsApi, type FleetAccount360 } from './operationsApi';
import { Vehicle360Drawer } from './Vehicle360Drawer';

const money=(value:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0));
const when=(value?:string|null)=>value?new Date(value).toLocaleString():'—';

export function FleetAccount360Drawer({customerId,onClose}:{customerId:string;onClose:()=>void}){
  const[data,setData]=useState<FleetAccount360|null>(null),[error,setError]=useState('');
  const[vehicleId,setVehicleId]=useState<string|null>(null);
  useEffect(()=>{let cancelled=false;operationsApi.customerOverview(customerId).then(r=>{if(!cancelled)setData(r.account)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Unable to load fleet account')});return()=>{cancelled=true}},[customerId]);
  return <div className="fixed inset-0 z-50 bg-slate-950/40"><div className="absolute inset-y-0 right-0 w-full max-w-5xl overflow-y-auto bg-slate-50 shadow-2xl">
    {!data&&!error?<div className="grid h-full place-items-center"><LoaderCircle className="h-7 w-7 animate-spin text-blue-600"/></div>:error?<div className="p-8"><button onClick={onClose} className="float-right"><X/></button><div className="mt-16 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div></div>:data&&<>
      <header className="sticky top-0 z-10 border-b bg-white/95 p-5 backdrop-blur"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Fleet Account 360</p><h2 className="mt-1 text-2xl font-bold text-slate-950">{data.account.name}</h2><p className="mt-1 text-sm text-slate-500">{data.account.accountNumber||'No account number'} · {data.account.status}</p></div><button onClick={onClose} aria-label="Close fleet account"><X className="h-5 w-5"/></button></div></header>
      <div className="p-5 lg:p-7">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
          ['Vehicles',`${data.summary.activeVehicles}/${data.summary.vehicles} active`,Car],
          ['Open work orders',String(data.summary.openWorkOrders),Wrench],
          ['Outstanding',money(data.summary.outstandingBalance),FileText],
          ['Conversations',String(data.summary.communicationThreads),Mail],
        ].map(([label,value,Icon])=><div key={String(label)} className="rounded-2xl border bg-white p-4 shadow-sm"><Icon className="h-4 w-4 text-blue-600"/><p className="mt-3 text-xs font-semibold text-slate-500">{String(label)}</p><p className="mt-1 text-xl font-bold">{String(value)}</p></div>)}</div>

        <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border bg-white p-5 lg:col-span-2"><h3 className="font-bold">Account profile</h3><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[
          ['Primary contact',data.account.primaryContactName],['Primary email',data.account.primaryContactEmail],['Phone',data.account.phone],['Billing contact',data.account.billingContactName],['Billing email',data.account.billingEmail],['Payment terms',data.account.paymentTerms],['Tax status',data.account.taxStatus],['PO required',data.account.poRequired?'Yes':'No'],['Default PO',data.account.defaultPoNumber]
        ].map(([label,value])=><div key={String(label)}><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1">{String(value||'—')}</dd></div>)}</dl><div className="mt-4 border-t pt-4 text-sm"><p className="text-xs font-semibold text-slate-500">Notes</p><p className="mt-1 whitespace-pre-wrap">{data.account.notes||'—'}</p></div></section>
          <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Financial relationship</h3><p className="mt-4 text-xs text-slate-500">Lifetime invoiced</p><p className="text-2xl font-bold">{money(data.summary.lifetimeInvoiced)}</p><p className="mt-4 text-xs text-slate-500">Outstanding balance</p><p className="text-2xl font-bold">{money(data.summary.outstandingBalance)}</p></section></div>

        <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold">Vehicles</h3><span className="text-xs text-slate-500">{data.vehicles.length} units</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.vehicles.map(v=><button type="button" onClick={()=>setVehicleId(v.id)} key={v.id} className="rounded-xl border p-4 text-left transition hover:border-blue-300 hover:bg-blue-50/40"><div className="flex justify-between"><div><p className="font-bold">Unit {v.unitNumber}</p><p className="text-sm text-slate-600">{[v.year,v.make,v.model].filter(Boolean).join(' ')||'Vehicle details pending'}</p></div><span className="text-xs font-semibold text-slate-500">{v.status}</span></div><p className="mt-3 text-xs text-slate-500">{v.mileage!=null?`${v.mileage.toLocaleString()} mi`:'Mileage —'} · {v.engineHours!=null?`${v.engineHours.toLocaleString()} hrs`:'Hours —'} · Open Vehicle 360</p></button>)}{data.vehicles.length===0&&<p className="text-sm text-slate-500">No vehicles assigned yet.</p>}</div></section>

        <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Maintenance attention</h3><div className="mt-3 divide-y">{data.dueMaintenance.slice(0,12).map(s=><div key={s.id} className="py-3"><p className="font-semibold">{s.serviceCode}</p><p className="text-xs text-slate-500">Next date {when(s.nextDueAt)} · mileage {s.nextDueMileage??'—'} · hours {s.nextDueEngineHours??'—'}</p></div>)}{data.dueMaintenance.length===0&&<p className="text-sm text-slate-500">No maintenance currently due.</p>}</div></section>
          <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Active recommendations</h3><div className="mt-3 divide-y">{data.recommendations.slice(0,12).map(r=><div key={r.id} className="py-3"><div className="flex justify-between"><p className="font-semibold">{r.name}</p><span className="text-xs font-bold text-amber-700">{r.condition}</span></div><p className="text-xs text-slate-500">{r.recommendation||'Review inspection result'}</p></div>)}{data.recommendations.length===0&&<p className="text-sm text-slate-500">No active recommendations.</p>}</div></section></div>

        <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Contacts</h3><div className="mt-3 space-y-3">{data.contacts.map(c=><div key={c.id} className="rounded-xl border p-3"><div className="flex justify-between"><p className="font-semibold">{c.name}</p>{c.isPrimary&&<span className="text-xs font-bold text-blue-600">Primary</span>}</div><p className="text-xs text-slate-500">{c.role||'Contact'} · {c.email||'No email'} · {c.phone||'No phone'}</p></div>)}{data.contacts.length===0&&<p className="text-sm text-slate-500">No contacts yet.</p>}</div></section>
          <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Service locations</h3><div className="mt-3 space-y-3">{data.locations.map(l=><div key={l.id} className="flex gap-3 rounded-xl border p-3"><MapPin className="mt-0.5 h-4 w-4 text-blue-600"/><div><p className="font-semibold">{l.name}</p><p className="text-xs text-slate-500">{[l.address1,l.address2,l.city,l.region,l.postalCode].filter(Boolean).join(', ')}</p></div></div>)}{data.locations.length===0&&<p className="text-sm text-slate-500">No service locations yet.</p>}</div></section></div>

        <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Recent work orders</h3><div className="mt-3 divide-y">{data.workOrders.slice(0,10).map(w=><div key={w.id} className="py-3"><div className="flex justify-between gap-3"><p className="font-semibold">{w.number}</p><span className="text-xs font-semibold text-slate-500">{w.status}</span></div><p className="mt-1 text-xs text-slate-500">{w.requestedServices?.join(', ')||'No services listed'} · {when(w.scheduledAt)}</p></div>)}{data.workOrders.length===0&&<p className="text-sm text-slate-500">No work orders yet.</p>}</div></section>
          <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Invoices</h3><div className="mt-3 divide-y">{data.invoices.slice(0,10).map(i=><div key={i.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-semibold">{i.number}</p><p className="text-xs text-slate-500">{i.status} · due {when(i.dueAt)}</p></div><div className="text-right"><p className="font-bold">{money(i.total)}</p><p className="text-xs text-slate-500">{money(i.balanceDue)} due</p></div></div>)}{data.invoices.length===0&&<p className="text-sm text-slate-500">No invoices yet.</p>}</div></section></div>

        <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-blue-600"/><h3 className="font-bold">Communication history</h3></div><div className="mt-3 divide-y">{data.communications.slice(0,15).map(t=><div key={t.id} className="py-3"><p className="font-semibold">{t.subject||'(No subject)'}</p><p className="text-xs text-slate-500">Last activity {when(t.lastMessageAt||t.updatedAt)}{t.workOrderId?' · linked to work order':''}</p></div>)}{data.communications.length===0&&<p className="text-sm text-slate-500">No AgentMail conversation has been linked to this fleet account yet.</p>}</div></section>
        <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-600"/><h3 className="font-bold">Acquisition history</h3></div><p className="mt-1 text-xs text-slate-500">Preserved prospect research, contacts, outreach, replies, follow-ups, and conversion history.</p><div className="mt-3 space-y-4">{data.revenueHistory.map(h=><div key={h.prospect.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{h.prospect.companyName}</p><p className="text-xs text-slate-500">Source: {h.prospect.source||'unknown'} · Converted {when(h.prospect.convertedAt)}</p></div>{h.prospect.sourceUrl&&<a href={h.prospect.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-blue-600">Source</a>}</div>{h.prospect.researchSummary&&<p className="mt-3 text-sm text-slate-600">{h.prospect.researchSummary}</p>}<div className="mt-3 divide-y">{h.activities.slice(0,20).map(a=><div key={a.id} className="py-2"><div className="flex justify-between gap-2"><p className="text-sm font-semibold">{a.subject||a.kind.replaceAll('_',' ')}</p><span className="text-xs text-slate-400">{when(a.occurredAt)}</span></div><p className="text-xs text-slate-500">{[a.direction,a.channel].filter(Boolean).join(' · ')}{a.summary?` · ${a.summary}`:''}</p></div>)}</div></div>)}{data.revenueHistory.length===0&&<p className="text-sm text-slate-500">This account was not converted from a tracked prospect.</p>}</div></section>
      </div>
      {vehicleId&&<Vehicle360Drawer vehicleId={vehicleId} onClose={()=>setVehicleId(null)}/>}
    </>}
  </div></div>;
}
