import React,{useCallback,useEffect,useMemo,useState}from'react';
import{ArrowLeft,Building2,Check,ChevronRight,Loader2,Plus,Search,X}from'lucide-react';
import{fleetFetch}from'../../lib/fleetApi';
import{FleetAccount360Drawer}from'./FleetAccount360Drawer';

type R=Record<string,any>;
type Bootstrap={accounts:R[];vehicles:R[];catalog:R[];agreements:R[];agreementServices:R[];parts:R[];vehicleParts:R[];vehicleServices:R[];workOrders:R[];serviceLines:R[];appointments:R[];dispatch:R[];technicians:R[]};
const empty:Bootstrap={accounts:[],vehicles:[],catalog:[],agreements:[],agreementServices:[],parts:[],vehicleParts:[],vehicleServices:[],workOrders:[],serviceLines:[],appointments:[],dispatch:[],technicians:[]};
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fleetFetch(path,{...init,headers:{'Content-Type':'application/json',...init.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body as T}
const field='h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const primary='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-40';
const secondary='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50';

export function FleetAccountsWorkspace(){
 const[data,setData]=useState<Bootstrap>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[viewingId,setViewingId]=useState<string|null>(null),[wizardOpen,setWizardOpen]=useState(false),[wizardStep,setWizardStep]=useState(1),[accountId,setAccountId]=useState(''),[accountName,setAccountName]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api<Bootstrap>('/api/fleet-service/bootstrap'))}catch(e){setError(e instanceof Error?e.message:'Unable to load fleet accounts')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const rows=useMemo(()=>data.accounts.filter(a=>`${a.name||''} ${a.primary_contact_name||''} ${a.primary_contact_email||''}`.toLowerCase().includes(search.toLowerCase())),[data.accounts,search]);
 const stats=(id:string)=>{const vehicles=data.vehicles.filter(v=>v.customer_id===id);const agreements=data.agreements.filter(a=>a.customer_id===id);const work=data.workOrders.filter(w=>w.customer_id===id);return{vehicles:vehicles.length,agreement:agreements[0],open:work.filter(w=>!['complete','completed','cancelled'].includes(String(w.status))).length,total:work.length}};
 const begin=()=>{setWizardStep(1);setAccountId('');setAccountName('');setError('');setWizardOpen(true)};
 async function createAccount(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');try{const body=Object.fromEntries(new FormData(e.currentTarget));const result=await api<{customer:R}>('/api/operations/customers',{method:'POST',body:JSON.stringify(body)});setAccountId(result.customer.id);setAccountName(result.customer.name||String(body.name||''));setWizardStep(2);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to create fleet account')}}
 async function createAgreement(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');try{const body=Object.fromEntries(new FormData(e.currentTarget));await api('/api/fleet-service/agreements',{method:'POST',body:JSON.stringify({...body,customerId:accountId})});setWizardStep(3);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save agreement')}}
 async function createVehicle(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');try{const body=Object.fromEntries(new FormData(e.currentTarget));await api('/api/fleet-service/vehicles',{method:'POST',body:JSON.stringify({...body,customerId:accountId})});setWizardStep(4);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to add vehicle')}}
 function finish(){setWizardOpen(false);setWizardStep(1);if(accountId)setViewingId(accountId)}
 if(loading)return <div className="grid flex-1 place-items-center bg-[#f7f8fa]"><Loader2 className="h-6 w-6 animate-spin text-blue-600"/></div>;
 return <main className="min-w-0 flex-1 overflow-y-auto bg-[#f7f8fa]"><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8">
  <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Fleet accounts</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Fleet customers</h1><p className="mt-1.5 text-sm text-slate-500">Every agreement, vehicle, work order, schedule, dispatch, service event, and invoice starts from a fleet account.</p></div><button onClick={begin} className={primary}><Plus className="h-4 w-4"/>Add Fleet Account</button></header>
  {error&&<div className="mt-4 border-l-2 border-red-500 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="mt-5 flex items-center justify-between gap-3"><label className="relative min-w-0 flex-1 sm:max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search fleet accounts…" className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></label><span className="text-xs font-semibold text-slate-500">{rows.length} accounts</span></div>
  <section className="mt-4 overflow-hidden border border-slate-200 bg-white shadow-sm"><div data-hscroll className="w-full overflow-x-auto"><table className="min-w-[820px] w-full border-separate border-spacing-0 text-left text-sm"><thead><tr>{['Fleet account','Vehicles','Agreement / SLA','Open work','Total work','Status',''].map(h=><th key={h} className="border-b border-slate-200 bg-slate-50 px-4 py-3 text-[10px] font-bold uppercase tracking-[.08em] text-slate-500">{h}</th>)}</tr></thead><tbody>{rows.map(a=>{const s=stats(a.id);return <tr key={a.id} className="hover:bg-blue-50/30"><td className="sticky left-0 z-[2] border-b border-slate-100 bg-white px-4 py-3 font-bold text-slate-950">{a.name}</td><td className="border-b border-slate-100 px-4 py-3">{s.vehicles}</td><td className="border-b border-slate-100 px-4 py-3">{s.agreement?<><span className="font-semibold">{s.agreement.name}</span><span className="ml-2 text-xs text-slate-500">{s.agreement.sla_hours}h SLA</span></>:<span className="text-amber-700">Setup incomplete</span>}</td><td className="border-b border-slate-100 px-4 py-3">{s.open}</td><td className="border-b border-slate-100 px-4 py-3">{s.total}</td><td className="border-b border-slate-100 px-4 py-3"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Active</span></td><td className="border-b border-slate-100 px-4 py-3 text-right"><button onClick={()=>setViewingId(a.id)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-blue-200 bg-white px-3 text-xs font-bold text-blue-700 hover:bg-blue-50">Open account<ChevronRight className="h-3.5 w-3.5"/></button></td></tr>})}</tbody></table></div>{rows.length===0&&<div className="p-12 text-center"><Building2 className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 font-semibold text-slate-700">No fleet accounts found</p><button onClick={begin} className={`${primary} mt-4`}>Add Fleet Account</button></div>}</section>
 </div>
 {viewingId&&<FleetAccount360Drawer customerId={viewingId} onClose={()=>setViewingId(null)}/>} 
 {wizardOpen&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-3 sm:p-5"><div className="max-h-[96vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 border-b border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Fleet account onboarding</p><h2 className="mt-1 text-xl font-bold text-slate-950">{accountName||'New fleet account'}</h2></div><button onClick={()=>setWizardOpen(false)} aria-label="Close onboarding" className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200"><X className="h-4 w-4"/></button></div><div className="mt-4 grid grid-cols-4 gap-2">{['Account','SLA & pricing','Vehicle','Finish'].map((label,index)=>{const n=index+1;return <div key={label}><div className={`h-1.5 rounded-full ${n<=wizardStep?'bg-blue-600':'bg-slate-200'}`}/><p className={`mt-1 text-[10px] font-bold ${n===wizardStep?'text-blue-700':'text-slate-400'}`}>{label}</p></div>})}</div></div>
   <div className="p-5 sm:p-6">{error&&<div className="mb-4 border-l-2 border-red-500 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
    {wizardStep===1&&<form onSubmit={createAccount} className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><h3 className="text-lg font-bold">1. Create the fleet account</h3><p className="mt-1 text-sm text-slate-500">This becomes the parent record for everything that follows.</p></div><input required name="name" placeholder="Company / fleet name" className={`${field} sm:col-span-2`}/><input name="primaryContactName" placeholder="Primary contact" className={field}/><input name="primaryContactEmail" type="email" placeholder="Primary email" className={field}/><input name="phone" placeholder="Phone" className={field}/><select name="paymentTerms" defaultValue="net_30" className={field}><option value="due_on_receipt">Due on receipt</option><option value="net_15">Net 15</option><option value="net_30">Net 30</option><option value="net_45">Net 45</option></select><button className={`${primary} sm:col-span-2`}>Save account & continue<ChevronRight className="h-4 w-4"/></button></form>}
    {wizardStep===2&&<form onSubmit={createAgreement} className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><h3 className="text-lg font-bold">2. Agreement, SLA & pricing rules</h3><p className="mt-1 text-sm text-slate-500">Configure the service rules that belong to {accountName}.</p></div><input required name="name" defaultValue={`${accountName} Service Agreement`} className={`${field} sm:col-span-2`}/><input name="slaHours" type="number" defaultValue="24" placeholder="SLA hours" className={field}/><select name="approvalMode" defaultValue="hybrid" className={field}><option value="manual">Manual approval</option><option value="hybrid">Hybrid threshold</option><option value="auto">Automatic approval</option></select><input name="approvalThreshold" type="number" defaultValue="500" placeholder="Approval threshold" className={field}/><select name="billingModel" defaultValue="per_service" className={field}><option value="per_service">Per service</option><option value="flat_rate">Flat rate</option><option value="time_and_materials">Time & materials</option><option value="blended">Blended</option></select><select name="invoiceFrequency" defaultValue="monthly" className={field}><option value="per_service">Per service</option><option value="weekly">Weekly</option><option value="biweekly">Bi-weekly</option><option value="monthly">Monthly</option></select><select name="paymentTerms" defaultValue="net_30" className={field}><option value="due_on_receipt">Due on receipt</option><option value="net_15">Net 15</option><option value="net_30">Net 30</option><option value="net_45">Net 45</option></select><label className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm"><input type="checkbox" name="poRequired"/>PO required</label><button className={`${primary} sm:col-span-2`}>Save agreement & continue<ChevronRight className="h-4 w-4"/></button></form>}
    {wizardStep===3&&<form onSubmit={createVehicle} className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><h3 className="text-lg font-bold">3. Add the first vehicle</h3><p className="mt-1 text-sm text-slate-500">Vehicles are created inside {accountName}, never as orphan records.</p></div><input required name="unitNumber" placeholder="Unit number" className={field}/><input name="vin" maxLength={17} placeholder="VIN" className={field}/><input name="year" type="number" placeholder="Year" className={field}/><input name="make" placeholder="Make" className={field}/><input name="model" placeholder="Model" className={field}/><input name="mileage" type="number" placeholder="Mileage" className={field}/><div className="flex gap-3 sm:col-span-2"><button type="button" onClick={()=>setWizardStep(4)} className={`${secondary} flex-1`}>Skip for now</button><button className={`${primary} flex-1`}>Add vehicle & continue</button></div></form>}
    {wizardStep===4&&<div><div className="grid h-14 w-14 place-items-center rounded-full bg-blue-50 text-blue-600"><Check className="h-7 w-7"/></div><h3 className="mt-4 text-xl font-bold">Fleet account ready</h3><p className="mt-2 text-sm text-slate-500">{accountName} now owns its service agreement, SLA rules, pricing context, vehicles, and all future work. Open the account to manage its vehicles, work orders, service history, invoices, contacts, and locations.</p><button onClick={finish} className={`${primary} mt-6 w-full`}>Open {accountName}<ChevronRight className="h-4 w-4"/></button></div>}
   </div>
  </div></div>}
 </main>
}
