import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ClipboardList, Loader2, RefreshCw, Wrench } from 'lucide-react';
import { fleetFetch } from '../../lib/fleetApi';

type WorkOrder = { id:string; number:string; status:string; priority:string; complaint:string|null; customerName:string|null; unitNumber:string|null; year:number|null; make:string|null; model:string|null; updatedAt:string };
type Schedule = { id:string; serviceCode:string; dueState:'overdue'|'due_soon'|'upcoming'|'unknown'; unitNumber:string; year:number|null; make:string|null; model:string|null; mileage:number|null; nextDueMileage:number|null; nextDueAt:string|null };

const statusLabel = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g, letter => letter.toUpperCase());
const badge = (value:string) => value === 'completed' || value === 'upcoming' ? 'bg-emerald-50 text-emerald-700' : value === 'overdue' || value === 'cancelled' ? 'bg-red-50 text-red-700' : value === 'due_soon' || value.includes('pending') ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700';

async function jsonRequest<T>(url:string, init?:RequestInit):Promise<T> {
  const response = await fleetFetch(url, init);
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
}

function State({loading,error,empty,onReload}:{loading:boolean;error:string;empty:boolean;onReload:()=>void}) {
  if (loading) return <div className="flex items-center justify-center p-16 text-sm text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Loading live fleet data…</div>;
  if (error) return <div className="p-12 text-center"><p className="text-sm font-semibold text-red-700">{error}</p><button onClick={onReload} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Try again</button></div>;
  if (empty) return <div className="p-16 text-center text-sm text-slate-500">No records yet. Create the first record to begin tracking operations.</div>;
  return null;
}

export function WorkOrdersWorkspace() {
  const [items,setItems]=useState<WorkOrder[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await jsonRequest<{workOrders:WorkOrder[]}>('/api/operations/work-orders');setItems(data.workOrders);}catch(e){setError(e instanceof Error?e.message:'Unable to load work orders');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const rows=useMemo(()=>items.filter(item=>`${item.number} ${item.unitNumber} ${item.customerName} ${item.complaint}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const update=async(item:WorkOrder,status:string)=>{try{await jsonRequest(`/api/operations/work-orders/${item.id}`,{method:'PATCH',body:JSON.stringify({status})});await load();}catch(e){setError(e instanceof Error?e.message:'Update failed');}};
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Live service operations</p><h2 className="mt-1 text-3xl font-bold text-slate-950">Work Orders</h2><p className="mt-2 text-sm text-slate-600">Records are loaded from and saved to your Fleet OS database.</p></div><button onClick={()=>void load()} className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Open" value={String(items.filter(x=>!['completed','cancelled'].includes(x.status)).length)} icon={<ClipboardList/>}/><Metric label="Awaiting action" value={String(items.filter(x=>x.status.includes('pending')).length)} icon={<Wrench/>}/><Metric label="Completed" value={String(items.filter(x=>x.status==='completed').length)} icon={<CheckCircle2/>}/></div>
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="font-bold">Current work orders</h3><p className="text-xs text-slate-500">Update a status and it persists immediately</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search work orders…" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/></div>
      <State loading={loading} error={error} empty={!rows.length} onReload={()=>void load()}/>{!loading&&!error&&rows.length>0&&<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-widest text-slate-500"><tr>{['Work order','Vehicle','Customer','Concern','Priority','Status'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(item=><tr key={item.id}><td className="px-5 py-4 font-bold text-blue-700">{item.number}</td><td className="px-5 py-4 font-semibold">{[item.year,item.make,item.model].filter(Boolean).join(' ')||item.unitNumber||'Unassigned'}{item.unitNumber&&<small className="block text-slate-400">Unit {item.unitNumber}</small>}</td><td className="px-5 py-4">{item.customerName||'—'}</td><td className="max-w-xs truncate px-5 py-4">{item.complaint||'—'}</td><td className="px-5 py-4">{statusLabel(item.priority)}</td><td className="px-5 py-4"><select value={item.status} onChange={e=>void update(item,e.target.value)} className={`rounded-full border-0 px-3 py-1.5 text-xs font-bold ${badge(item.status)}`}>{['draft','intake','inspection_pending','inspection_complete','authorization_pending','authorized','service_in_progress','completed','cancelled'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></td></tr>)}</tbody></table></div>}
    </section></div></main>;
}

export function MaintenanceWorkspace() {
  const [items,setItems]=useState<Schedule[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await jsonRequest<{schedules:Schedule[]}>('/api/operations/maintenance');setItems(data.schedules);}catch(e){setError(e instanceof Error?e.message:'Unable to load maintenance');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const complete=async(item:Schedule)=>{const raw=window.prompt(`Current mileage for Unit ${item.unitNumber}`,String(item.mileage??''));if(raw==null)return;const mileage=Number(raw);if(!Number.isFinite(mileage))return setError('Enter a valid mileage');try{await jsonRequest(`/api/operations/maintenance/${item.id}/complete`,{method:'POST',body:JSON.stringify({mileage})});await load();}catch(e){setError(e instanceof Error?e.message:'Completion failed');}};
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1440px]"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Live preventive maintenance</p><h2 className="mt-1 text-3xl font-bold">Maintenance</h2><p className="mt-2 text-sm text-slate-600">Due status is calculated from each vehicle’s real odometer and service intervals.</p></div><section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><State loading={loading} error={error} empty={!items.length} onReload={()=>void load()}/>{!loading&&!error&&items.length>0&&<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-widest text-slate-500"><tr>{['Vehicle','Service','Odometer','Next mileage','Next date','Timing','Action'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.map(item=><tr key={item.id}><td className="px-5 py-4 font-bold">Unit {item.unitNumber}<small className="block font-normal text-slate-400">{[item.year,item.make,item.model].filter(Boolean).join(' ')}</small></td><td className="px-5 py-4 font-semibold">{statusLabel(item.serviceCode)}</td><td className="px-5 py-4">{item.mileage?.toLocaleString()??'—'}</td><td className="px-5 py-4">{item.nextDueMileage?.toLocaleString()??'—'}</td><td className="px-5 py-4">{item.nextDueAt?new Date(item.nextDueAt).toLocaleDateString():'—'}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${badge(item.dueState)}`}>{statusLabel(item.dueState)}</span></td><td className="px-5 py-4"><button onClick={()=>void complete(item)} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white">Complete service</button></td></tr>)}</tbody></table></div>}</section></div></main>;
}

function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactElement<{className?:string}>}) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between text-blue-600">{React.cloneElement(icon,{className:'h-5 w-5'})}<span className="text-2xl font-bold text-slate-950">{value}</span></div><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p></div>; }
