import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Eye, LoaderCircle, PackageSearch, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { operationsApi, type PartRow } from './operationsApi';

const status=(part:PartRow)=>Number(part.quantity)<=0?'Out of stock':Number(part.quantity)<=Number(part.reorderPoint)?'Low stock':'Healthy';
export function PartsWorkspace(){
  const[rows,setRows]=useState<PartRow[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setRows((await operationsApi.parts(search)).parts)}catch(e){setError(e instanceof Error?e.message:'Unable to load parts')}finally{setLoading(false)}},[search]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  const metrics=useMemo(()=>({units:rows.reduce((n,r)=>n+Number(r.quantity),0),value:rows.reduce((n,r)=>n+Number(r.quantity)*Number(r.unitCost||0),0),low:rows.filter(r=>status(r)!=='Healthy').length}),[rows]);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget));try{await operationsApi.createPart(raw);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create part')}}
  async function editStock(part:PartRow){const quantity=window.prompt(`On-hand quantity for ${part.sku}`,part.quantity);if(quantity===null)return;const reorder=window.prompt('Reorder point',part.reorderPoint);if(reorder===null)return;try{await operationsApi.updateInventory(part.id,{quantity:Number(quantity),reorderPoint:Number(reorder)});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update stock')}}
  function view(part:PartRow){window.alert(`${part.sku} — ${part.name}\n\n${part.description||'No description'}\nCost: $${Number(part.unitCost||0).toFixed(2)}\nPrice: $${Number(part.unitPrice||0).toFixed(2)}\nOn hand: ${part.quantity}\nReorder point: ${part.reorderPoint}`)}
  async function edit(part:PartRow){const name=window.prompt('Part name',part.name);if(name===null)return;const description=window.prompt('Description',part.description||'');if(description===null)return;const unitCost=window.prompt('Unit cost',String(part.unitCost||0));if(unitCost===null)return;const unitPrice=window.prompt('Unit price',String(part.unitPrice||0));if(unitPrice===null)return;try{await operationsApi.updatePart(part.id,{sku:part.sku,name,description,unitCost:Number(unitCost),unitPrice:Number(unitPrice)});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update part')}}
  async function remove(id:string){if(!window.confirm('Delete this part and its inventory record?'))return;try{await operationsApi.deletePart(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete part')}}
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Inventory & procurement</p><h2 className="mt-1 text-3xl font-bold">Parts</h2><p className="mt-2 text-sm text-slate-600">Live stock levels, costs, pricing, and reorder thresholds.</p></div><button onClick={()=>setOpen(true)} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Add part</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3">{[['Inventory value',metrics.value.toLocaleString('en-US',{style:'currency',currency:'USD'})],['Units on hand',String(metrics.units)],['Needs reorder',String(metrics.low)]].map(([l,v])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{l}</p><p className="mt-3 text-2xl font-bold">{v}</p></div>)}</div>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-bold">Parts inventory</h3><p className="text-xs text-slate-500">Select a quantity to update stock</p></div><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search parts…" className="h-9 rounded-xl border pl-9 pr-3 text-sm"/></label></div>
      {loading?<div className="flex h-48 items-center justify-center"><LoaderCircle className="h-6 w-6 animate-spin text-blue-600"/></div>:rows.length===0?<div className="p-12 text-center"><PackageSearch className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-semibold">No parts found</p></div>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{['SKU','Description','Cost','Price','On hand','Reorder at','Status','Actions'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=>{const state=status(r);return <tr key={r.id}><td className="px-5 py-4 font-bold">{r.sku}</td><td className="px-5 py-4 font-semibold">{r.name}</td><td className="px-5 py-4">${Number(r.unitCost||0).toFixed(2)}</td><td className="px-5 py-4">${Number(r.unitPrice||0).toFixed(2)}</td><td className="px-5 py-4"><button onClick={()=>editStock(r)} className="font-bold text-blue-600 hover:underline">{r.quantity}</button></td><td className="px-5 py-4">{r.reorderPoint}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${state==='Healthy'?'bg-emerald-50 text-emerald-700':state==='Low stock'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{state}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button aria-label="View part" onClick={()=>view(r)}><Eye className="h-4 w-4"/></button><button aria-label="Edit part" onClick={()=>void edit(r)}><Pencil className="h-4 w-4"/></button><button aria-label="Delete part" onClick={()=>remove(r.id)} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></td></tr>})}</tbody></table></div>}
    </section>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={create} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h3 className="text-lg font-bold">Add inventory part</h3><button type="button" onClick={()=>setOpen(false)}><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><input required name="sku" placeholder="SKU" className="rounded-xl border p-3"/><input required name="name" placeholder="Part name" className="rounded-xl border p-3"/><input name="description" placeholder="Description / fitment" className="rounded-xl border p-3 sm:col-span-2"/><input name="unitCost" type="number" min="0" step=".01" placeholder="Unit cost" className="rounded-xl border p-3"/><input name="unitPrice" type="number" min="0" step=".01" placeholder="Unit price" className="rounded-xl border p-3"/><input name="quantity" type="number" min="0" step=".001" placeholder="On hand" className="rounded-xl border p-3"/><input name="reorderPoint" type="number" min="0" step=".001" placeholder="Reorder point" className="rounded-xl border p-3"/></div><button className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">Save part</button></form></div>}
  </div></main>
}
