import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Pencil,Plus,Trash2,X}from'lucide-react';
import{fleetFetch}from'../../lib/fleetApi';
import{mergeUniqueById}from'../../lib/operationalListState';
import{ProspectCommandCenter}from'./ProspectCommandCenter';

type Prospect={id:string;companyName:string;website:string|null;industry:string|null;serviceArea:string|null;estimatedFleetSize:number|null;stage:string;opportunityValue:string|null;convertedCustomerId?:string|null};
type Draft={companyName:string;website:string;industry:string;serviceArea:string;estimatedFleetSize:string;opportunityValue:string;stage:string};
type ProspectPage={prospects:Prospect[];nextCursor:string|null;hasMore:boolean};
type DraftKey=keyof Draft;
const empty:Draft={companyName:'',website:'',industry:'',serviceArea:'',estimatedFleetSize:'',opportunityValue:'',stage:'new'};
const stages=['new','researching','qualified','outreach','engaged','meeting','proposal','won','lost'];

async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fleetFetch(path,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body as T}
function validWebsite(value:string){if(!value.trim())return true;try{const u=new URL(/^https?:\/\//i.test(value.trim())?value.trim():`https://${value.trim()}`);return ['http:','https:'].includes(u.protocol)&&Boolean(u.hostname)}catch{return false}}
function fieldError(key:DraftKey,value:string){
 if(key==='companyName'&&!value.trim())return 'Company name is required.';
 if(key==='companyName'&&value.trim().length>300)return 'Company name must be 300 characters or fewer.';
 if(key==='website'&&!validWebsite(value))return 'Enter a valid website, for example example.com.';
 if(key==='estimatedFleetSize'&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0))return 'Fleet size must be 0 or greater.';
 if(key==='opportunityValue'&&value!==''&&(!Number.isFinite(Number(value))||Number(value)<0))return 'Opportunity value must be 0 or greater.';
 if(key==='stage'&&!stages.includes(value))return 'Choose a valid stage.';
 return '';
}
function validateDraft(draft:Draft){return Object.fromEntries((Object.keys(draft) as DraftKey[]).map(key=>[key,fieldError(key,draft[key])])) as Record<DraftKey,string>}

export function ProspectCrudWorkspace(){
 const[items,setItems]=useState<Prospect[]>([]),[error,setError]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<Prospect|null>(null),[draft,setDraft]=useState<Draft>(empty),[touched,setTouched]=useState<Partial<Record<DraftKey,boolean>>>({}),[saving,setSaving]=useState(false),[loadingMore,setLoadingMore]=useState(false),[nextCursor,setNextCursor]=useState<string|null>(null),[hasMore,setHasMore]=useState(false),[refreshKey,setRefreshKey]=useState(0);
 const errors=useMemo(()=>validateDraft(draft),[draft]);
 const valid=useMemo(()=>Object.values(errors).every(v=>!v),[errors]);
 const load=useCallback(async(cursor:string|null=null,append=false)=>{append&&setLoadingMore(true);try{const p=new URLSearchParams({limit:'50'});if(cursor)p.set('cursor',cursor);const data=await request<ProspectPage>(`/api/operations/prospects?${p}`);setItems(current=>append?mergeUniqueById(current,data.prospects||[]):data.prospects||[]);setNextCursor(data.nextCursor||null);setHasMore(Boolean(data.hasMore))}catch(e){setError(e instanceof Error?e.message:'Unable to load prospect records')}finally{setLoadingMore(false)}},[]);
 useEffect(()=>{void load(null,false)},[load]);
 const openCreate=()=>{setEditing(null);setDraft(empty);setTouched({});setError('');setModal(true)};
 const openEdit=(p:Prospect)=>{setEditing(p);setDraft({companyName:p.companyName,website:p.website||'',industry:p.industry||'',serviceArea:p.serviceArea||'',estimatedFleetSize:p.estimatedFleetSize==null?'':String(p.estimatedFleetSize),opportunityValue:p.opportunityValue||'',stage:p.stage});setTouched({});setError('');setModal(true)};
 function change<K extends DraftKey>(key:K,value:Draft[K]){setDraft(d=>({...d,[key]:value}));setTouched(t=>({...t,[key]:true}));setError('')}
 async function save(e:React.FormEvent){e.preventDefault();setTouched(Object.fromEntries((Object.keys(draft) as DraftKey[]).map(k=>[k,true])));if(!valid)return;setSaving(true);setError('');try{const body={companyName:draft.companyName.trim(),website:draft.website.trim()||null,industry:draft.industry.trim()||null,serviceArea:draft.serviceArea.trim()||null,estimatedFleetSize:draft.estimatedFleetSize===''?null:Number(draft.estimatedFleetSize),opportunityValue:draft.opportunityValue===''?null:Number(draft.opportunityValue),stage:draft.stage,source:'manual'};await request(editing?`/api/operations/prospects/${editing.id}`:'/api/operations/prospects',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setModal(false);setEditing(null);await load(null,false);setRefreshKey(k=>k+1)}catch(e){setError(e instanceof Error?e.message:'Prospect could not be saved')}finally{setSaving(false)}}
 async function remove(p:Prospect){if(p.convertedCustomerId)return setError('Converted prospects are retained as acquisition history.');if(!window.confirm(`Delete prospect ${p.companyName}? Related prospect contacts and activities will also be removed.`))return;setError('');try{await request(`/api/operations/prospects/${p.id}`,{method:'DELETE'});await load(null,false);setRefreshKey(k=>k+1)}catch(e){setError(e instanceof Error?e.message:'Prospect could not be deleted')}}
 return <div className="flex min-h-0 flex-1 flex-col">
  <section className="border-b bg-white px-4 py-3 sm:px-6"><div className="mx-auto flex max-w-[1500px] flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Manual prospect records</p><p className="text-sm text-slate-600">Create, edit, and delete prospect records without using discovery. Showing {items.length} loaded records.</p></div><button onClick={openCreate} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Add prospect manually</button></div>{error&&<div className="mx-auto mt-3 max-w-[1500px] rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
   {items.length>0&&<div className="mx-auto mt-3 max-w-[1500px] overflow-x-auto"><div className="flex min-w-max gap-2">{items.map(p=><div key={p.id} className="flex items-center gap-2 rounded-xl border bg-slate-50 px-3 py-2"><span className="max-w-48 truncate text-xs font-semibold">{p.companyName}</span><button aria-label={`Edit ${p.companyName}`} onClick={()=>openEdit(p)} className="grid min-h-11 min-w-11 place-items-center rounded-lg border bg-white"><Pencil className="h-4 w-4"/></button><button aria-label={`Delete ${p.companyName}`} disabled={Boolean(p.convertedCustomerId)} onClick={()=>void remove(p)} className="grid min-h-11 min-w-11 place-items-center rounded-lg border bg-white text-red-600 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>}
   {hasMore&&<div className="mx-auto mt-3 max-w-[1500px]"><button disabled={loadingMore||!nextCursor} onClick={()=>void load(nextCursor,true)} className="min-h-11 w-full rounded-xl border bg-white px-4 text-sm font-bold disabled:opacity-50 sm:w-auto">{loadingMore?'Loading…':'Load more manual records'}</button></div>}
  </section>
  <ProspectCommandCenter key={refreshKey}/>
  {modal&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/45 p-3"><form noValidate onSubmit={save} className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Manual entry</p><h2 className="text-xl font-bold">{editing?'Edit prospect':'Add prospect'}</h2></div><button type="button" onClick={()=>setModal(false)} className="grid min-h-11 min-w-11 place-items-center rounded-xl border"><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field required label="Company name" value={draft.companyName} error={touched.companyName?errors.companyName:''} onChange={v=>change('companyName',v)}/><Field label="Website" value={draft.website} error={touched.website?errors.website:''} onChange={v=>change('website',v)}/><Field label="Industry" value={draft.industry} error={touched.industry?errors.industry:''} onChange={v=>change('industry',v)}/><Field label="Service area" value={draft.serviceArea} error={touched.serviceArea?errors.serviceArea:''} onChange={v=>change('serviceArea',v)}/><Field label="Estimated fleet size" type="number" value={draft.estimatedFleetSize} error={touched.estimatedFleetSize?errors.estimatedFleetSize:''} onChange={v=>change('estimatedFleetSize',v)}/><Field label="Opportunity value" type="number" value={draft.opportunityValue} error={touched.opportunityValue?errors.opportunityValue:''} onChange={v=>change('opportunityValue',v)}/><label className="sm:col-span-2"><span className="text-xs font-bold text-slate-600">Stage</span><select value={draft.stage} onChange={e=>change('stage',e.target.value)} className={`mt-1.5 min-h-11 w-full rounded-xl border px-3 ${touched.stage&&errors.stage?'border-red-500':'border-slate-300'}`}>{stages.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select>{touched.stage&&errors.stage&&<p className="mt-1 text-xs font-semibold text-red-600">{errors.stage}</p>}</label></div><button disabled={saving||!valid} className="mt-5 min-h-12 w-full rounded-xl bg-blue-600 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">{saving?'Saving…':editing?'Save prospect':'Add prospect'}</button></form></div>}
 </div>
}
function Field({label,value,onChange,type='text',required=false,error=''}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;error?:string}){return <label><span className="text-xs font-bold text-slate-600">{label}{required?' *':''}</span><input aria-invalid={Boolean(error)} type={type} value={value} onChange={e=>onChange(e.target.value)} className={`mt-1.5 min-h-11 w-full rounded-xl border px-3 outline-none ${error?'border-red-500 focus:border-red-600':'border-slate-300 focus:border-blue-600'}`}/>{error&&<p className="mt-1 text-xs font-semibold text-red-600">{error}</p>}</label>}
