import React, { useCallback, useEffect, useState } from 'react';
import { AlertCircle, Clock3, Loader2, Mail, RefreshCw } from 'lucide-react';
import { fleetFetch } from '../../lib/fleetApi';

type AttentionItem={id:string;companyName:string;stage:string;opportunityValue:string|null;nextFollowUpAt:string|null;attentionPriority:number;attentionReason:string;suggestedNextAction:string;lastActivityAt:string|null;lastActivityDirection:string|null;ageDays:number};
type AttentionResponse={items:AttentionItem[];summary:{needsAttention:number;overdue:number;repliesWaiting:number;dueSoon:number}};
const money=(value:string|null)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));

export function ProspectAttentionQueue({onOpen}:{onOpen:(id:string)=>void}){
 const[data,setData]=useState<AttentionResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fleetFetch('/api/operations/prospects-attention');const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to load follow-ups');setData(body)}catch(e){setError(e instanceof Error?e.message:'Unable to load follow-ups')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <section className="mt-6 grid h-32 place-items-center rounded-2xl border border-slate-200 bg-white"><Loader2 className="h-5 w-5 animate-spin text-blue-600"/></section>;
 if(error)return <section className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</section>;
 if(!data)return null;
 return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-amber-600">Attention today</p><h3 className="mt-1 font-bold text-slate-950">Follow-up intelligence</h3><p className="mt-1 text-xs text-slate-500">Replies and opportunities ranked by what needs action next.</p></div><button onClick={()=>void load()} className="grid h-9 w-9 place-items-center rounded-xl border"><RefreshCw className="h-4 w-4"/></button></div><div className="grid grid-cols-2 gap-px bg-slate-200 sm:grid-cols-4">{[[data.summary.needsAttention,'Need attention',AlertCircle],[data.summary.repliesWaiting,'Replies waiting',Mail],[data.summary.overdue,'Overdue',Clock3],[data.summary.dueSoon,'Due soon',Clock3]].map(([value,label,Icon])=><div key={String(label)} className="bg-white p-4"><Icon className="h-4 w-4 text-slate-500"/><p className="mt-2 text-xl font-bold">{String(value)}</p><p className="text-xs text-slate-500">{String(label)}</p></div>)}</div>{data.items.length===0?<div className="p-7 text-center text-sm text-slate-500">Nothing needs immediate follow-up.</div>:<div className="divide-y">{data.items.slice(0,8).map(item=><button key={item.id} onClick={()=>onOpen(item.id)} className="flex w-full items-center justify-between gap-4 p-4 text-left hover:bg-slate-50"><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate font-bold text-slate-950">{item.companyName}</span>{item.lastActivityDirection==='inbound'&&<span className="rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-bold text-violet-700">REPLIED</span>}</div><p className="mt-1 text-xs font-semibold text-amber-700">{item.attentionReason}</p><p className="mt-1 text-xs text-slate-500">Next: {item.suggestedNextAction}</p></div><div className="shrink-0 text-right"><p className="text-sm font-bold">{money(item.opportunityValue)}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">Priority {item.attentionPriority}</p></div></button>)}</div>}</section>;
}
