import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, CheckCircle2, Loader2, RefreshCw, Search, Sparkles, Target } from 'lucide-react';
import { fleetFetch } from '../../lib/fleetApi';
import { ProspectAttentionQueue } from './ProspectAttentionQueue';

type Prospect={id:string;companyName:string;website:string|null;industry:string|null;serviceArea:string|null;estimatedFleetSize:number|null;stage:string;qualificationScore:number;lastResearchedAt:string|null;opportunityValue:string|null};
const stages=['new','researching','qualified','outreach','engaged','meeting','proposal','won','lost','converted'];
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const money=(value:string|null)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString():'—';
const scoreClass=(score:number)=>score>=75?'bg-emerald-50 text-emerald-700':score>=50?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600';
const stageClass=(stage:string)=>['won','converted','qualified'].includes(stage)?'bg-emerald-50 text-emerald-700':stage==='lost'?'bg-red-50 text-red-700':['engaged','meeting','proposal'].includes(stage)?'bg-violet-50 text-violet-700':'bg-blue-50 text-blue-700';
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fleetFetch(`/api/operations${path}`,init);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}

export function ProspectingWorkspace(){
 const[items,setItems]=useState<Prospect[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[stage,setStage]=useState(''),[workingId,setWorkingId]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams();if(search.trim())params.set('search',search.trim());if(stage)params.set('stage',stage);setItems((await request<{prospects:Prospect[]}>(`/prospects?${params}`)).prospects)}catch(e){setError(e instanceof Error?e.message:'Unable to load prospects')}finally{setLoading(false)}},[search,stage]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
 const totals=useMemo(()=>({qualified:items.filter(p=>p.qualificationScore>=60&&!['lost','converted'].includes(p.stage)).length,engaged:items.filter(p=>['engaged','meeting','proposal'].includes(p.stage)).length,pipeline:items.filter(p=>!['lost','converted'].includes(p.stage)).reduce((sum,p)=>sum+Number(p.opportunityValue||0),0)}),[items]);
 async function updateStage(id:string,next:string){try{await request(`/prospects/${id}`,{method:'PATCH',body:JSON.stringify({stage:next})});await load()}catch(e){setError(e instanceof Error?e.message:'Stage update failed')}}
 async function research(id:string){setWorkingId(id);try{await request(`/prospects/${id}/research`,{method:'POST',body:'{}'});await load()}catch(e){setError(e instanceof Error?e.message:'Research failed')}finally{setWorkingId(null)}}
 return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1500px]">
  <div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Revenue engine</p><h2 className="mt-1 text-3xl font-bold text-slate-950">Prospects</h2><p className="mt-2 max-w-3xl text-sm text-slate-600">Research, qualify, contact, and convert fleet opportunities while keeping the next sales action visible.</p></div>
  <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Prospects',String(items.length),Target],['Qualified',String(totals.qualified),CheckCircle2],['Active conversations',String(totals.engaged),Building2],['Pipeline',money(String(totals.pipeline)),Sparkles]].map(([name,value,Icon])=><div key={String(name)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-4 w-4 text-blue-600"/><p className="mt-3 text-xs font-semibold text-slate-500">{String(name)}</p><p className="mt-1 text-2xl font-bold">{String(value)}</p></div>)}</div>
  <ProspectAttentionQueue onOpen={(id)=>{const row=document.getElementById(`prospect-${id}`);row?.scrollIntoView({behavior:'smooth',block:'center'})}}/>
  {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-bold">Fleet opportunity pipeline</h3><p className="text-xs text-slate-500">Firecrawl research is stored with source evidence.</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search companies…" className="h-9 rounded-xl border border-slate-200 pl-9 pr-3 text-sm"/></label><select value={stage} onChange={e=>setStage(e.target.value)} className="h-9 rounded-xl border border-slate-200 px-3 text-sm"><option value="">All stages</option>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button onClick={()=>void load()} className="grid h-9 w-9 place-items-center rounded-xl border"><RefreshCw className="h-4 w-4"/></button></div></div>
  {loading?<div className="grid h-52 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-blue-600"/></div>:items.length===0?<div className="p-16 text-center"><Target className="mx-auto h-9 w-9 text-slate-300"/><p className="mt-3 font-semibold">No prospects yet</p></div>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Company','Fleet','Score','Stage','Opportunity','Last research','Action'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{items.map(p=><tr id={`prospect-${p.id}`} key={p.id} className="hover:bg-slate-50/60"><td className="px-5 py-4"><p className="font-bold text-slate-950">{p.companyName}</p><p className="mt-1 text-xs text-slate-500">{p.industry||'Industry unknown'}{p.serviceArea?` · ${p.serviceArea}`:''}</p></td><td className="px-5 py-4">{p.estimatedFleetSize==null?'Unknown':`~${p.estimatedFleetSize} units`}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${scoreClass(p.qualificationScore)}`}>{p.qualificationScore}/100</span></td><td className="px-5 py-4"><select value={p.stage} onChange={e=>void updateStage(p.id,e.target.value)} className={`rounded-full border-0 px-2.5 py-1 text-xs font-bold ${stageClass(p.stage)}`}>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></td><td className="px-5 py-4 font-semibold">{money(p.opportunityValue)}</td><td className="px-5 py-4 text-xs text-slate-500">{date(p.lastResearchedAt)}</td><td className="px-5 py-4"><button disabled={!p.website||workingId===p.id} onClick={()=>void research(p.id)} className="rounded-lg border p-2 disabled:opacity-40">{workingId===p.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}</button></td></tr>)}</tbody></table></div>}</section>
 </div></main>;
}
