import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Building2, CheckCircle2, ExternalLink, Loader2, Plus, RefreshCw, Search, Sparkles, Target, UserPlus, X } from 'lucide-react';
import { fleetFetch } from '../../lib/fleetApi';

type Prospect = {
  id:string; companyName:string; website:string|null; industry:string|null; phone:string|null; generalEmail:string|null;
  serviceArea:string|null; estimatedFleetSize:number|null; vehicleTypes:string[]; source:string; sourceUrl:string|null;
  stage:string; qualificationScore:number; researchSummary:string|null; fleetEvidence:unknown; researchSources:unknown;
  lastResearchedAt:string|null; lastContactedAt:string|null; nextFollowUpAt:string|null; opportunityValue:string|null;
  probability:number; lostReason:string|null; convertedCustomerId:string|null; convertedAt:string|null; notes:string|null;
  metadata:unknown; createdAt:string; updatedAt:string;
};
type ProspectContact={id:string;name:string;email:string|null;phone:string|null;title:string|null;isDecisionMaker:boolean;sourceUrl:string|null;confidence:number;notes:string|null};
type ProspectActivity={id:string;kind:string;direction:string|null;channel:string|null;subject:string|null;summary:string|null;occurredAt:string};
type ProspectDetail={prospect:Prospect;contacts:ProspectContact[];activities:ProspectActivity[]};

const stages=['new','researching','qualified','outreach','engaged','meeting','proposal','won','lost','converted'];
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const money=(value:string|null)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString():'—';
const scoreClass=(score:number)=>score>=75?'bg-emerald-50 text-emerald-700':score>=50?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600';
const stageClass=(stage:string)=>['won','converted','qualified'].includes(stage)?'bg-emerald-50 text-emerald-700':['lost'].includes(stage)?'bg-red-50 text-red-700':['engaged','meeting','proposal'].includes(stage)?'bg-violet-50 text-violet-700':'bg-blue-50 text-blue-700';

async function request<T>(path:string,init?:RequestInit):Promise<T>{
  const response=await fleetFetch(`/api/operations${path}`,init);
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);
  return data;
}
function arrayStrings(value:unknown):string[]{return Array.isArray(value)?value.map(v=>typeof v==='string'?v:String((v as any)?.text||v)).filter(Boolean):[]}
function sources(value:unknown):Array<{url:string;title?:string}>{return Array.isArray(value)?value.filter(v=>v&&typeof v==='object'&&typeof (v as any).url==='string').map(v=>({url:(v as any).url,title:(v as any).title})):[]}

export function ProspectingWorkspace(){
  const[items,setItems]=useState<Prospect[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[stage,setStage]=useState('');
  const[createOpen,setCreateOpen]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<ProspectDetail|null>(null),[detailLoading,setDetailLoading]=useState(false),[workingId,setWorkingId]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams();if(search.trim())params.set('search',search.trim());if(stage)params.set('stage',stage);setItems((await request<{prospects:Prospect[]}>(`/prospects?${params}`)).prospects)}catch(e){setError(e instanceof Error?e.message:'Unable to load prospects')}finally{setLoading(false)}},[search,stage]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
  const openDetail=useCallback(async(id:string)=>{setSelectedId(id);setDetail(null);setDetailLoading(true);try{setDetail(await request<ProspectDetail>(`/prospects/${id}`))}catch(e){setError(e instanceof Error?e.message:'Unable to load prospect')}finally{setDetailLoading(false)}},[]);
  const totals=useMemo(()=>({qualified:items.filter(p=>p.qualificationScore>=60&&!['lost','converted'].includes(p.stage)).length,engaged:items.filter(p=>['engaged','meeting','proposal'].includes(p.stage)).length,pipeline:items.filter(p=>!['lost','converted'].includes(p.stage)).reduce((sum,p)=>sum+Number(p.opportunityValue||0),0)}),[items]);
  async function createProspect(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const body:any=Object.fromEntries(form);body.vehicleTypes=String(body.vehicleTypes||'').split(',').map((x:string)=>x.trim()).filter(Boolean);if(body.estimatedFleetSize==='')delete body.estimatedFleetSize;if(body.opportunityValue==='')delete body.opportunityValue;try{await request('/prospects',{method:'POST',body:JSON.stringify(body)});setCreateOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create prospect')}}
  async function research(id:string){setWorkingId(id);setError('');try{await request(`/prospects/${id}/research`,{method:'POST',body:'{}'});await load();if(selectedId===id)await openDetail(id)}catch(e){setError(e instanceof Error?e.message:'Research failed')}finally{setWorkingId(null)}}
  async function convert(id:string){if(!window.confirm('Convert this prospect into a Fleet Account? The prospect history will remain linked for audit.'))return;setWorkingId(id);setError('');try{await request(`/prospects/${id}/convert`,{method:'POST',body:'{}'});await load();if(selectedId===id)await openDetail(id)}catch(e){setError(e instanceof Error?e.message:'Conversion failed')}finally{setWorkingId(null)}}
  async function updateStage(id:string,next:string){try{await request(`/prospects/${id}`,{method:'PATCH',body:JSON.stringify({stage:next})});await load();if(selectedId===id)await openDetail(id)}catch(e){setError(e instanceof Error?e.message:'Stage update failed')}}
  async function addContact(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedId)return;const form=new FormData(event.currentTarget);const body:any=Object.fromEntries(form);body.isDecisionMaker=form.get('isDecisionMaker')==='on';if(body.confidence==='')delete body.confidence;try{await request(`/prospects/${selectedId}/contacts`,{method:'POST',body:JSON.stringify(body)});event.currentTarget.reset();await openDetail(selectedId)}catch(e){setError(e instanceof Error?e.message:'Unable to add contact')}}

  return <main className="flex-1 overflow-y-auto bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Revenue engine</p><h2 className="mt-1 text-3xl font-bold text-slate-950">Prospects</h2><p className="mt-2 max-w-3xl text-sm text-slate-600">Research, qualify, contact, and convert fleet opportunities without polluting the customer database before they are won.</p></div><button onClick={()=>setCreateOpen(true)} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>New prospect</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Prospects',String(items.length),Target],['Qualified',String(totals.qualified),CheckCircle2],['Active conversations',String(totals.engaged),Building2],['Pipeline',money(String(totals.pipeline)),Sparkles]].map(([name,value,Icon])=><div key={String(name)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-4 w-4 text-blue-600"/><p className="mt-3 text-xs font-semibold text-slate-500">{String(name)}</p><p className="mt-1 text-2xl font-bold">{String(value)}</p></div>)}</div>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-bold">Fleet opportunity pipeline</h3><p className="text-xs text-slate-500">Firecrawl research is stored with source evidence.</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search companies…" className="h-9 rounded-xl border border-slate-200 pl-9 pr-3 text-sm"/></label><select value={stage} onChange={e=>setStage(e.target.value)} className="h-9 rounded-xl border border-slate-200 px-3 text-sm"><option value="">All stages</option>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button onClick={()=>void load()} className="grid h-9 w-9 place-items-center rounded-xl border"><RefreshCw className="h-4 w-4"/></button></div></div>
      {loading?<div className="grid h-52 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-blue-600"/></div>:items.length===0?<div className="p-16 text-center"><Target className="mx-auto h-9 w-9 text-slate-300"/><p className="mt-3 font-semibold">No prospects yet</p><p className="mt-1 text-sm text-slate-500">Add a company manually now; automated discovery comes next.</p></div>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Company','Fleet','Score','Stage','Opportunity','Last research','Actions'].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{items.map(p=><tr key={p.id} className="hover:bg-slate-50/60"><td className="px-5 py-4"><button onClick={()=>void openDetail(p.id)} className="text-left font-bold text-slate-950 hover:text-blue-700">{p.companyName}</button><p className="mt-1 text-xs text-slate-500">{p.industry||'Industry unknown'}{p.serviceArea?` · ${p.serviceArea}`:''}</p></td><td className="px-5 py-4">{p.estimatedFleetSize==null?'Unknown':`~${p.estimatedFleetSize} units`}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${scoreClass(p.qualificationScore)}`}>{p.qualificationScore}/100</span></td><td className="px-5 py-4"><select value={p.stage} disabled={p.stage==='converted'} onChange={e=>void updateStage(p.id,e.target.value)} className={`rounded-full border-0 px-2.5 py-1 text-xs font-bold ${stageClass(p.stage)}`}>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></td><td className="px-5 py-4 font-semibold">{money(p.opportunityValue)}</td><td className="px-5 py-4 text-xs text-slate-500">{date(p.lastResearchedAt)}</td><td className="px-5 py-4"><div className="flex gap-2"><button title="Research prospect" disabled={!p.website||workingId===p.id} onClick={()=>void research(p.id)} className="rounded-lg border p-2 disabled:opacity-40">{workingId===p.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}</button><button title="View prospect" onClick={()=>void openDetail(p.id)} className="rounded-lg border px-3 py-2 text-xs font-bold">View</button></div></td></tr>)}</tbody></table></div>}
    </section>
    {selectedId&&<div className="fixed inset-0 z-50 bg-slate-950/40"><div className="absolute inset-y-0 right-0 w-full max-w-4xl overflow-y-auto bg-slate-50 shadow-2xl">{detailLoading||!detail?<div className="grid h-full place-items-center"><Loader2 className="h-6 w-6 animate-spin text-blue-600"/></div>:<><header className="sticky top-0 z-10 border-b bg-white/95 p-5 backdrop-blur"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Prospect intelligence</p><h3 className="mt-1 text-2xl font-bold">{detail.prospect.companyName}</h3><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${stageClass(detail.prospect.stage)}`}>{label(detail.prospect.stage)}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${scoreClass(detail.prospect.qualificationScore)}`}>{detail.prospect.qualificationScore}/100</span></div></div><button onClick={()=>{setSelectedId(null);setDetail(null)}}><X className="h-5 w-5"/></button></div></header><div className="space-y-5 p-5 lg:p-7">
      <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">Estimated fleet</p><p className="mt-1 text-xl font-bold">{detail.prospect.estimatedFleetSize==null?'Unknown':`${detail.prospect.estimatedFleetSize} units`}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">Opportunity</p><p className="mt-1 text-xl font-bold">{money(detail.prospect.opportunityValue)}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">Probability</p><p className="mt-1 text-xl font-bold">{detail.prospect.probability}%</p></div></div>
      <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-bold">Company intelligence</h4><div className="flex gap-2">{detail.prospect.website&&<a href={detail.prospect.website} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold">Website <ExternalLink className="h-3 w-3"/></a>}<button disabled={!detail.prospect.website||workingId===detail.prospect.id} onClick={()=>void research(detail.prospect.id)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><Sparkles className="h-3.5 w-3.5"/>Research</button></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-700">{detail.prospect.researchSummary||'No research has been completed yet.'}</p>{arrayStrings(detail.prospect.fleetEvidence).length>0&&<div className="mt-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Fleet evidence</p><ul className="mt-2 space-y-2">{arrayStrings(detail.prospect.fleetEvidence).map((item,i)=><li key={i} className="rounded-xl bg-slate-50 p-3 text-sm">{item}</li>)}</ul></div>}{sources(detail.prospect.researchSources).length>0&&<div className="mt-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Sources</p><div className="mt-2 space-y-2">{sources(detail.prospect.researchSources).map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer" className="block truncate text-sm font-medium text-blue-700 hover:underline">{s.title||s.url}</a>)}</div></div>}</section>
      <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><UserPlus className="h-4 w-4 text-blue-600"/><h4 className="font-bold">Decision makers</h4></div><div className="mt-3 space-y-3">{detail.contacts.map(c=><div key={c.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><p className="font-semibold">{c.name}</p>{c.isDecisionMaker&&<span className="text-xs font-bold text-blue-600">Decision maker</span>}</div><p className="mt-1 text-xs text-slate-500">{c.title||'Role unknown'} · {c.email||'No email'} · {c.phone||'No phone'}</p></div>)}{detail.contacts.length===0&&<p className="text-sm text-slate-500">No contacts recorded yet.</p>}</div><form onSubmit={addContact} className="mt-4 grid gap-2 border-t pt-4"><input required name="name" placeholder="Contact name" className="rounded-xl border p-2.5 text-sm"/><input name="title" placeholder="Title / role" className="rounded-xl border p-2.5 text-sm"/><input name="email" type="email" placeholder="Email" className="rounded-xl border p-2.5 text-sm"/><input name="phone" placeholder="Phone" className="rounded-xl border p-2.5 text-sm"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="isDecisionMaker"/>Decision maker</label><button className="rounded-xl border bg-slate-950 py-2 text-xs font-bold text-white">Add contact</button></form></section>
      <section className="rounded-2xl border bg-white p-5"><h4 className="font-bold">Activity timeline</h4><div className="mt-3 space-y-3">{detail.activities.map(a=><div key={a.id} className="border-l-2 border-slate-200 pl-3"><div className="flex justify-between gap-2"><p className="text-sm font-semibold">{label(a.kind)}</p><p className="text-[10px] text-slate-400">{date(a.occurredAt)}</p></div><p className="mt-1 text-xs text-slate-500">{a.channel||'Fleet OS'}{a.direction?` · ${a.direction}`:''}</p>{a.summary&&<p className="mt-1 text-sm text-slate-700">{a.summary}</p>}</div>)}{detail.activities.length===0&&<p className="text-sm text-slate-500">No activity yet.</p>}</div></section></div>
      <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h4 className="font-bold text-blue-950">Convert to Fleet Account</h4><p className="mt-1 text-sm text-blue-800">Carries the company and contacts into the canonical Fleet OS customer model while preserving this prospect history.</p></div><button disabled={detail.prospect.stage==='converted'||workingId===detail.prospect.id} onClick={()=>void convert(detail.prospect.id)} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{detail.prospect.stage==='converted'?'Converted':'Convert'}</button></div></section>
    </div></>}</div></div>}
    {createOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={createProspect} className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-blue-600">Revenue engine</p><h3 className="text-lg font-bold">New prospect</h3></div><button type="button" onClick={()=>setCreateOpen(false)}><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required name="companyName" placeholder="Company name" className="rounded-xl border p-3 sm:col-span-2"/><input name="website" placeholder="Website" className="rounded-xl border p-3"/><input name="industry" placeholder="Industry" className="rounded-xl border p-3"/><input name="phone" placeholder="Phone" className="rounded-xl border p-3"/><input name="generalEmail" type="email" placeholder="General email" className="rounded-xl border p-3"/><input name="serviceArea" placeholder="Service area" className="rounded-xl border p-3"/><input name="estimatedFleetSize" type="number" min="0" placeholder="Estimated fleet size" className="rounded-xl border p-3"/><input name="vehicleTypes" placeholder="Vehicle types, comma separated" className="rounded-xl border p-3 sm:col-span-2"/><input name="opportunityValue" type="number" min="0" step="0.01" placeholder="Estimated opportunity value" className="rounded-xl border p-3"/><select name="stage" defaultValue="new" className="rounded-xl border p-3">{stages.filter(s=>s!=='converted').map(s=><option key={s} value={s}>{label(s)}</option>)}</select><textarea name="notes" placeholder="Notes" className="rounded-xl border p-3 sm:col-span-2"/></div><button className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">Create prospect</button></form></div>}
  </div></main>;
}
