import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ClipboardCheck, Loader2, Plus, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { fleetFetch } from '../../lib/fleetApi';
import { WorkOrdersWorkspace } from './OperationsWorkspace';

type WorkOrder = { id:string; number:string; status:string; complaint:string|null; unitNumber:string|null; customerName:string|null };
type InspectionItem = { id:string; name:string; condition:string; measurement?:string|null; recommendation?:string|null; severity?:string|null };
type Inspection = { id:string; status:string; odometer?:number|null; engineHours?:number|null; items:InspectionItem[] };
type Authorization = { id:string; status:string; amount?:string|null; purchaseOrderNumber?:string|null; authorizedBy?:string|null; authorizationMethod?:string|null; notes?:string|null };
type ServiceLine = { id:string; description:string; kind:string; laborMinutes?:number|null; quantity?:string|null; unitPrice?:string|null; authorized:boolean; completedAt?:string|null };
type Execution = { workOrder:any; inspections:Inspection[]; authorizations:Authorization[]; serviceLines:ServiceLine[]; partUsage:any[]; fluidUsage:any[] };

async function request<T>(url:string, init?:RequestInit):Promise<T>{
  const response=await fleetFetch(url,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});
  const body=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(body.error||`Request failed (${response.status})`);
  return body as T;
}
const label=(value:string)=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const tone=(value:string)=>['complete','completed','authorized','good','pass'].includes(String(value).toLowerCase())?'bg-emerald-50 text-emerald-700':['rejected','cancelled','failed','poor','critical'].includes(String(value).toLowerCase())?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700';

function TechnicianExecutionWorkspace(){
  const[orders,setOrders]=useState<WorkOrder[]>([]),[selectedId,setSelectedId]=useState(''),[execution,setExecution]=useState<Execution|null>(null);
  const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const[inspectionName,setInspectionName]=useState('Multi-point inspection'),[condition,setCondition]=useState('good'),[measurement,setMeasurement]=useState(''),[recommendation,setRecommendation]=useState(''),[severity,setSeverity]=useState('');
  const[serviceDescription,setServiceDescription]=useState(''),[servicePrice,setServicePrice]=useState(''),[serviceMinutes,setServiceMinutes]=useState(''),[authorizationAmount,setAuthorizationAmount]=useState(''),[authorizationNotes,setAuthorizationNotes]=useState('');

  const loadOrders=useCallback(async()=>{setLoading(true);setError('');try{const data=await request<{workOrders:WorkOrder[]}>('/api/operations/work-orders');const active=(data.workOrders||[]).filter(x=>!['complete','completed','cancelled'].includes(x.status));setOrders(active);setSelectedId(current=>current&&active.some(x=>x.id===current)?current:(active[0]?.id||''));}catch(e){setError(e instanceof Error?e.message:'Unable to load work orders');}finally{setLoading(false)}},[]);
  const loadExecution=useCallback(async(id:string)=>{if(!id){setExecution(null);return;}setError('');try{const data=await request<{execution:Execution}>(`/api/operations/work-orders/${id}/execution`);setExecution(data.execution);}catch(e){setError(e instanceof Error?e.message:'Unable to load execution packet');}},[]);
  useEffect(()=>{void loadOrders();},[loadOrders]);
  useEffect(()=>{void loadExecution(selectedId);},[selectedId,loadExecution]);
  const selected=useMemo(()=>orders.find(x=>x.id===selectedId)||null,[orders,selectedId]);
  const currentInspection=execution?.inspections.find(x=>x.status!=='complete')||execution?.inspections[0]||null;
  const refresh=async()=>{await Promise.all([loadOrders(),loadExecution(selectedId)]);};
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(false)}};

  const startInspection=()=>act(async()=>{if(!selectedId)return;await request(`/api/operations/work-orders/${selectedId}/inspections`,{method:'POST',body:JSON.stringify({odometer:execution?.workOrder?.odometer,engineHours:execution?.workOrder?.engineHours})});});
  const addItem=()=>act(async()=>{if(!currentInspection)return;await request(`/api/operations/inspections/${currentInspection.id}/items`,{method:'POST',body:JSON.stringify({name:inspectionName,condition,measurement:measurement||null,recommendation:recommendation||null,severity:severity||null,position:currentInspection.items.length})});setMeasurement('');setRecommendation('');setSeverity('');});
  const completeInspection=()=>act(async()=>{if(!currentInspection)return;await request(`/api/operations/inspections/${currentInspection.id}/complete`,{method:'POST',body:'{}'});});
  const createAuthorization=()=>act(async()=>{if(!selectedId)return;await request(`/api/operations/work-orders/${selectedId}/authorizations`,{method:'POST',body:JSON.stringify({amount:authorizationAmount||null,notes:authorizationNotes||null})});setAuthorizationAmount('');setAuthorizationNotes('');});
  const decide=(id:string,decision:'authorized'|'rejected')=>act(()=>request(`/api/operations/authorizations/${id}/decision`,{method:'POST',body:JSON.stringify({decision})}));
  const addServiceLine=()=>act(async()=>{if(!selectedId||!serviceDescription.trim())return;await request(`/api/operations/work-orders/${selectedId}/service-lines`,{method:'POST',body:JSON.stringify({description:serviceDescription,kind:'labor',laborMinutes:Number(serviceMinutes||0),quantity:1,unitPrice:Number(servicePrice||0),authorized:true})});setServiceDescription('');setServicePrice('');setServiceMinutes('');});
  const completeLine=(id:string)=>act(()=>request(`/api/operations/service-lines/${id}/complete`,{method:'POST',body:'{}'}));
  const completeWorkOrder=()=>act(()=>request(`/api/operations/work-orders/${selectedId}/complete-validated`,{method:'POST',body:'{}'}));

  return <main className="flex-1 overflow-y-auto bg-slate-50 p-4 lg:p-8"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Technician execution</p><h2 className="mt-1 text-3xl font-bold text-slate-950">Inspection → Authorization → Service</h2><p className="mt-2 max-w-3xl text-sm text-slate-600">One canonical work-order packet for inspection findings, recommendations, approvals, service lines and validated completion.</p></div><button onClick={()=>void refresh()} className="flex h-10 items-center justify-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
    {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
    <section className="mt-6 rounded-2xl border bg-white p-4 shadow-sm"><label className="text-xs font-bold uppercase tracking-wider text-slate-500">Active work order</label>{loading?<Loader2 className="mt-3 h-5 w-5 animate-spin"/>:<select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="mt-2 w-full rounded-xl border p-3 text-sm font-semibold"><option value="">Select work order…</option>{orders.map(order=><option key={order.id} value={order.id}>{order.number} · {order.unitNumber?`Unit ${order.unitNumber}`:'No unit'} · {order.customerName||'Fleet account'} · {label(order.status)}</option>)}</select>}
    {selected&&<div className="mt-3 flex flex-wrap gap-2 text-xs"><span className={`rounded-full px-3 py-1 font-bold ${tone(selected.status)}`}>{label(selected.status)}</span><span className="rounded-full bg-slate-100 px-3 py-1 font-semibold text-slate-700">{selected.complaint||'No concern recorded'}</span></div>}</section>
    {!selectedId?<div className="mt-6 rounded-2xl border border-dashed bg-white p-12 text-center text-sm text-slate-500">No active work order selected.</div>:!execution?<div className="mt-6 flex justify-center p-12"><Loader2 className="h-6 w-6 animate-spin text-slate-400"/></div>:<div className="mt-6 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">1 · Inspection</p><h3 className="mt-1 font-bold">Condition & recommendations</h3></div><ClipboardCheck className="h-5 w-5 text-blue-600"/></div>
      {!currentInspection||currentInspection.status==='complete'?<button disabled={busy} onClick={startInspection} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus className="h-4 w-4"/>Start inspection</button>:<><div className="mt-4 grid gap-2 sm:grid-cols-2"><input value={inspectionName} onChange={e=>setInspectionName(e.target.value)} placeholder="Inspection item" className="rounded-xl border p-2.5 text-sm"/><select value={condition} onChange={e=>setCondition(e.target.value)} className="rounded-xl border p-2.5 text-sm"><option value="good">Good</option><option value="monitor">Monitor</option><option value="needs_service">Needs service</option><option value="failed">Failed</option></select><input value={measurement} onChange={e=>setMeasurement(e.target.value)} placeholder="Measurement" className="rounded-xl border p-2.5 text-sm"/><input value={severity} onChange={e=>setSeverity(e.target.value)} placeholder="Severity" className="rounded-xl border p-2.5 text-sm"/><textarea value={recommendation} onChange={e=>setRecommendation(e.target.value)} placeholder="Recommendation" className="rounded-xl border p-2.5 text-sm sm:col-span-2"/></div><button disabled={busy||!inspectionName.trim()} onClick={addItem} className="mt-3 w-full rounded-xl border border-blue-200 bg-blue-50 py-2.5 text-sm font-bold text-blue-700 disabled:opacity-50">Add inspection item</button></>}
      <div className="mt-4 space-y-2">{(currentInspection?.items||[]).map(item=><div key={item.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.measurement||'No measurement'}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${tone(item.condition)}`}>{label(item.condition)}</span></div>{item.recommendation&&<p className="mt-2 text-sm text-amber-800"><strong>Recommend:</strong> {item.recommendation}</p>}</div>)}</div>
      {currentInspection&&currentInspection.status!=='complete'&&<button disabled={busy||!currentInspection.items.length} onClick={completeInspection} className="mt-4 w-full rounded-xl bg-slate-900 py-3 text-sm font-bold text-white disabled:opacity-40">Complete inspection → Review</button>}</section>

      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">2 · Authorization</p><h3 className="mt-1 font-bold">Approval gate</h3></div><ShieldCheck className="h-5 w-5 text-blue-600"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><input value={authorizationAmount} onChange={e=>setAuthorizationAmount(e.target.value)} inputMode="decimal" placeholder="Amount" className="rounded-xl border p-2.5 text-sm"/><input value={authorizationNotes} onChange={e=>setAuthorizationNotes(e.target.value)} placeholder="Approval notes / PO" className="rounded-xl border p-2.5 text-sm"/></div><button disabled={busy} onClick={createAuthorization} className="mt-3 w-full rounded-xl border border-blue-200 bg-blue-50 py-2.5 text-sm font-bold text-blue-700 disabled:opacity-50">Request authorization</button><div className="mt-4 space-y-2">{execution.authorizations.map(auth=><div key={auth.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-bold">{auth.amount?`$${auth.amount}`:'Authorization'}</p><p className="text-xs text-slate-500">{auth.purchaseOrderNumber||auth.notes||'No PO / note'}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${tone(auth.status)}`}>{label(auth.status)}</span></div>{auth.status==='pending'&&<div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>decide(auth.id,'authorized')} className="rounded-lg bg-emerald-600 py-2 text-xs font-bold text-white">Authorize</button><button disabled={busy} onClick={()=>decide(auth.id,'rejected')} className="rounded-lg bg-red-50 py-2 text-xs font-bold text-red-700">Reject</button></div>}</div>)}</div></section>

      <section className="rounded-2xl border bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">3 · Service lines</p><h3 className="mt-1 font-bold">Authorized work & completion</h3></div><Wrench className="h-5 w-5 text-blue-600"/></div><div className="mt-4 grid gap-2 md:grid-cols-4"><input value={serviceDescription} onChange={e=>setServiceDescription(e.target.value)} placeholder="Service description" className="rounded-xl border p-2.5 text-sm md:col-span-2"/><input value={serviceMinutes} onChange={e=>setServiceMinutes(e.target.value)} inputMode="numeric" placeholder="Labor minutes" className="rounded-xl border p-2.5 text-sm"/><input value={servicePrice} onChange={e=>setServicePrice(e.target.value)} inputMode="decimal" placeholder="Unit price" className="rounded-xl border p-2.5 text-sm"/></div><button disabled={busy||!serviceDescription.trim()} onClick={addServiceLine} className="mt-3 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Add authorized service line</button><div className="mt-4 grid gap-3 md:grid-cols-2">{execution.serviceLines.map(line=><div key={line.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{line.description}</p><p className="mt-1 text-xs text-slate-500">{label(line.kind)} · {line.laborMinutes||0} min · ${line.unitPrice||'0.00'}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${line.completedAt?'bg-emerald-50 text-emerald-700':line.authorized?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'}`}>{line.completedAt?'Completed':line.authorized?'Authorized':'Not authorized'}</span></div>{line.authorized&&!line.completedAt&&<button disabled={busy} onClick={()=>completeLine(line.id)} className="mt-3 w-full rounded-lg bg-slate-900 py-2 text-xs font-bold text-white">Mark service complete</button>}</div>)}</div><div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-700"/><p className="font-bold text-emerald-900">Validated work-order completion</p></div><p className="mt-1 text-sm text-emerald-800">Completion is accepted only after the inspection, authorization and unresolved service-line gates pass server-side.</p><button disabled={busy} onClick={completeWorkOrder} className="mt-3 rounded-xl bg-emerald-700 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Complete work order</button></div></section>
    </div>}
  </div></main>;
}

export function WorkOrderOperationsHub(){
  const[mode,setMode]=useState<'orders'|'technician'>('orders');
  return <div className="flex min-h-0 flex-1 flex-col"><div className="border-b bg-white px-5 pt-3 lg:px-8"><div className="flex gap-2"><button onClick={()=>setMode('orders')} className={`rounded-t-xl px-4 py-2.5 text-sm font-bold ${mode==='orders'?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-100'}`}>Work orders</button><button onClick={()=>setMode('technician')} className={`rounded-t-xl px-4 py-2.5 text-sm font-bold ${mode==='technician'?'bg-blue-600 text-white':'text-slate-600 hover:bg-slate-100'}`}>Technician execution</button></div></div>{mode==='orders'?<WorkOrdersWorkspace/>:<TechnicianExecutionWorkspace/>}</div>;
}
