import React, { useEffect, useMemo, useState } from 'react';
import { Activity, CalendarClock, ClipboardCheck, Gauge, LoaderCircle, MapPin, Settings2, Wrench, X } from 'lucide-react';
import { operationsApi, type Vehicle360 } from './operationsApi';

const when=(value?:string|null)=>value?new Date(value).toLocaleString():'—';
const value=(input:unknown)=>input===null||input===undefined||input===''?'—':String(input);

export function Vehicle360Drawer({vehicleId,onClose}:{vehicleId:string;onClose:()=>void}){
  const[data,setData]=useState<Vehicle360|null>(null),[error,setError]=useState('');
  useEffect(()=>{let cancelled=false;operationsApi.vehicleOverview(vehicleId).then(r=>{if(!cancelled)setData(r.vehicle)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Unable to load vehicle')});return()=>{cancelled=true}},[vehicleId]);
  const specs=useMemo(()=>Object.entries(data?.vehicle.specifications||{}).filter(([,v])=>v!==null&&v!==''),[data]);
  return <div className="fixed inset-0 z-[60] bg-slate-950/50"><div className="absolute inset-y-0 right-0 w-full max-w-4xl overflow-y-auto bg-slate-50 shadow-2xl">
    {!data&&!error?<div className="grid h-full place-items-center"><LoaderCircle className="h-7 w-7 animate-spin text-blue-600"/></div>:error?<div className="p-8"><button onClick={onClose} className="float-right"><X/></button><div className="mt-16 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div></div>:data&&<>
      <header className="sticky top-0 z-10 border-b bg-white/95 p-5 backdrop-blur"><div className="flex justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">Vehicle 360</p><h2 className="mt-1 text-2xl font-bold">Unit {data.vehicle.unitNumber}</h2><p className="text-sm text-slate-500">{[data.vehicle.year,data.vehicle.make,data.vehicle.model,data.vehicle.trim].filter(Boolean).join(' ')||'Vehicle details pending'} · {data.account?.name||'Unassigned fleet'}</p></div><button onClick={onClose} aria-label="Close vehicle"><X className="h-5 w-5"/></button></div></header>
      <div className="space-y-5 p-5 lg:p-7">
        <div className="grid gap-3 sm:grid-cols-3">{[{Icon:Gauge,label:'Mileage',value:data.vehicle.mileage!=null?`${data.vehicle.mileage.toLocaleString()} mi`:'—'},{Icon:CalendarClock,label:'Due maintenance',value:data.summary.dueMaintenance},{Icon:Wrench,label:'Open work orders',value:data.summary.openWorkOrders}].map(({Icon,label,value})=><div key={label} className="rounded-2xl border bg-white p-4"><Icon className="h-4 w-4 text-blue-600"/><p className="mt-3 text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{String(value)}</p></div>)}</div>
        <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Identity and assignment</h3><dl className="mt-4 grid grid-cols-2 gap-4 text-sm">{[['VIN',data.vehicle.vin],['Plate',[data.vehicle.licensePlate,data.vehicle.registrationState].filter(Boolean).join(' ')],['Engine',data.vehicle.engine],['Fuel',data.vehicle.fuelType],['Driver',data.vehicle.assignedDriver],['Department',data.vehicle.department],['Engine hours',data.vehicle.engineHours]].map(([k,v])=><div key={String(k)}><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-1 font-medium">{value(v)}</dd></div>)}</dl>{data.location&&<div className="mt-4 flex gap-2 border-t pt-4 text-sm"><MapPin className="h-4 w-4 text-blue-600"/><span>{data.location.name}: {[data.location.address1,data.location.city,data.location.region,data.location.postalCode].filter(Boolean).join(', ')}</span></div>}</section>
          <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Settings2 className="h-4 w-4 text-blue-600"/><h3 className="font-bold">Cached service specifications</h3></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{specs.map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{k.replace(/([A-Z])/g,' $1')}</dt><dd className="font-medium">{value(v)}</dd></div>)}{specs.length===0&&<p className="col-span-2 text-sm text-slate-500">No cached specifications yet.</p>}</dl></section></div>
        <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Preventive maintenance</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{data.maintenanceSchedules.map(s=><div key={s.id} className="rounded-xl border p-3"><div className="flex justify-between"><p className="font-semibold">{s.serviceCode}</p><span className="text-xs text-slate-500">{s.active?'Active':'Paused'}</span></div><p className="mt-1 text-xs text-slate-500">Date {when(s.nextDueAt)} · Mileage {value(s.nextDueMileage)} · Hours {value(s.nextDueEngineHours)}</p></div>)}{data.maintenanceSchedules.length===0&&<p className="text-sm text-slate-500">No maintenance schedules.</p>}</div></section>
        <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-600"/><h3 className="font-bold">Service history</h3></div><div className="mt-3 divide-y">{data.maintenanceHistory.slice(0,20).map(e=><div key={e.id} className="py-3"><p className="font-semibold">{e.eventType}</p><p className="text-xs text-slate-500">{when(e.occurredAt)}{e.mileage!=null?` · ${e.mileage.toLocaleString()} mi`:''}</p></div>)}{data.maintenanceHistory.length===0&&<p className="text-sm text-slate-500">No maintenance history.</p>}</div></section>
          <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-blue-600"/><h3 className="font-bold">Active recommendations</h3></div><div className="mt-3 divide-y">{data.recommendations.map(r=><div key={r.id} className="py-3"><div className="flex justify-between"><p className="font-semibold">{r.name}</p><span className="text-xs font-bold text-amber-700">{r.condition}</span></div><p className="text-xs text-slate-500">{r.recommendation||'Review inspection item'}</p></div>)}{data.recommendations.length===0&&<p className="text-sm text-slate-500">No active recommendations.</p>}</div></section></div>
      </div>
    </>}
  </div></div>;
}
